import type { AppLocale } from "@/shared/i18n/locales";
const en = {
  wallet: "Your wallet", connect: "Connect wallet", change: "Change wallet", cancel: "Cancel", close: "Close wallet setup",
  walletHelp: "Connect once for your race and league rewards.", saved: "Wallet saved", held: "Wallet needs review",
  empty: "No wallet connected yet. Your rewards stay reserved.", loading: "Checking your wallet…",
  unavailable: "Your wallet could not be loaded. Refresh to try again.", history: "Wallet history", profile: "Athlete profile",
  choose: "Choose an athlete profile", singleProfile: "For your athlete profile", more: "Load remaining wallets",
  replaceHelp: "Remove this address before connecting its replacement. Existing signed claims and past payments keep their original address. Unpaid rewards remain reserved.",
  remove: "Remove current wallet", replacing: "Updating wallet…", failed: "Could not confirm the change. Refresh your wallet before trying again.",
  intro: "Your race and league rewards, in one place.", rewardDetails: "Reward details", claim: "Claim reward",
  confirmClaim: "Confirm claim in wallet", submitClaim: "Submit claim", claimHistory: "Claim history", viewReceipt: "View receipt",
  claimHelp: "Confirm the amount and receiving wallet. Payment follows organizer approval.",
  pending: "Awaiting organizer preparation", pendingHelp: "No action needed yet. You can claim when the organizer finishes the checks.",
  explorer: "View on MonadVision", organiserTitle: "Organizer workspace", organiserHelp: "Funding, race mapping and distribution settings require an organizer account.",
  athleteBack: "Back to my rewards", calculator: "Try the reward calculator", organizerLink: "Organizer setup", previewOnly: "Preview only — no wallet or payment required.",
  example: "Example league", small: "Small test · 20 athletes · 100 MON", full: "Full league · 100,000 MON",
  stage: "League progress", four: "After four rounds", five: "Season complete · five rounds", advanced: "Test an exception",
  distanceHold: "Missing distance data", normal: "Use complete distance data", sizeHelp: "Choose a sample league, then select the round or league pot below.",
  savedWallets: "Saved wallets", refreshWallet: "Refresh wallet", removedWallet: "Previous wallet", walletDetails: "Wallet details",
  saveWallet: "Save wallet", saveWalletHelp: "Use this wallet for future reward claims on this profile.",
  claimSaved: "Claim submitted", claimReady: "Ready to claim", claimReview: "Claim needs review", approvalPending: "Waiting for organizer approval.", approved: "Approved for payment.", signatureHelp: "Your signature confirms this claim, not the payment.",
};
const hr: typeof en = {
  wallet: "Tvoj novčanik", connect: "Poveži novčanik", change: "Promijeni novčanik", cancel: "Odustani", close: "Zatvori postavljanje novčanika",
  walletHelp: "Poveži ga jednom za nagrade iz utrka i lige.", saved: "Novčanik je spremljen", held: "Potrebna je provjera novčanika",
  empty: "Još nema povezanog novčanika. Tvoje nagrade ostaju rezervirane.", loading: "Provjera novčanika…",
  unavailable: "Novčanik nije učitan. Osvježi za ponovni pokušaj.", history: "Povijest novčanika", profile: "Profil natjecatelja",
  choose: "Odaberi profil natjecatelja", singleProfile: "Za tvoj profil natjecatelja", more: "Učitaj preostale novčanike",
  replaceHelp: "Ukloni ovu adresu prije povezivanja nove. Već potpisani zahtjevi i ranije isplate zadržavaju izvornu adresu. Neisplaćene nagrade ostaju rezervirane.",
  remove: "Ukloni trenutačni novčanik", replacing: "Ažuriranje novčanika…", failed: "Promjena nije potvrđena. Osvježi novčanik prije novog pokušaja.",
  intro: "Tvoje nagrade iz utrka i lige na jednom mjestu.", rewardDetails: "Pojedinosti nagrade", claim: "Preuzmi nagradu",
  confirmClaim: "Potvrdi zahtjev u novčaniku", submitClaim: "Pošalji zahtjev", claimHistory: "Povijest preuzimanja", viewReceipt: "Pogledaj potvrdu",
  claimHelp: "Provjeri iznos i novčanik za primitak. Isplata slijedi nakon odobrenja organizatora.",
  pending: "Organizator priprema preuzimanje", pendingHelp: "Zasad ne trebaš ništa učiniti. Preuzimanje će biti dostupno nakon provjera organizatora.",
  explorer: "Pogledaj na MonadVisionu", organiserTitle: "Radni prostor organizatora", organiserHelp: "Uplate, povezivanje utrka i postavke raspodjele dostupni su organizatorskom računu.",
  athleteBack: "Natrag na moje nagrade", calculator: "Isprobaj izračun nagrada", organizerLink: "Postavke organizatora", previewOnly: "Samo pregled — bez novčanika i isplate.",
  example: "Primjer lige", small: "Mali test · 20 natjecatelja · 100 MON", full: "Cijela liga · 100.000 MON",
  stage: "Tijek lige", four: "Nakon četiri kola", five: "Završena sezona · pet kola", advanced: "Isprobaj iznimku",
  distanceHold: "Nedostaju podaci o udaljenosti", normal: "Upotrijebi potpune podatke o udaljenosti", sizeHelp: "Odaberi primjer lige, a zatim fond kola ili lige ispod.",
  savedWallets: "Spremljeni novčanici", refreshWallet: "Osvježi novčanik", removedWallet: "Prijašnji novčanik", walletDetails: "Pojedinosti novčanika",
  saveWallet: "Spremi novčanik", saveWalletHelp: "Koristi ovaj novčanik za buduća preuzimanja nagrada ovog profila.",
  claimSaved: "Zahtjev je poslan", claimReady: "Spremno za preuzimanje", claimReview: "Potrebna je provjera zahtjeva", approvalPending: "Čeka se odobrenje organizatora.", approved: "Isplata je odobrena.", signatureHelp: "Potpis potvrđuje ovaj zahtjev, a ne isplatu.",
};
export const athleteUxCopy = (locale: AppLocale) => locale === "hr" ? hr : en;
