import type {ClaimStep} from '../components/RewardClaimChecklist';
type Context={hr:boolean;loading:boolean;failed:boolean};
export function athleteClaimSteps({hr,loading,failed,walletSelected,signatureCollected,consented,approved,payment,held,expired}:Context&{
 walletSelected:boolean;signatureCollected:boolean;consented:boolean;approved:boolean;payment:'unknown'|'waiting'|'submitted'|'confirmed';held:boolean;expired:boolean;
}):ClaimStep[]{
 const text=(en:string,cr:string)=>hr?cr:en;
 if(loading||failed)return [{title:text('Check this award','Provjera ove nagrade'),state:'unverified',detail:text(loading?'Checking the exact award and its current status…':'Status could not be verified. Refresh this review before continuing.',loading?'Provjeravamo točnu nagradu i njezino stanje…':'Stanje nije provjereno. Osvježi ovaj pregled prije nastavka.')}];
 const stopped=held||expired;
 return [
  {title:text('Award & destination','Nagrada i odredište'),state:'complete',detail:text('The amount and receiving address above belong to this reviewed claim.','Iznos i adresa primatelja iznad pripadaju ovom provjerenom zahtjevu.')},
  {title:text('Wallet control','Kontrola novčanika'),state:consented||signatureCollected?'complete':stopped?'waiting':'current',detail:text(consented||signatureCollected?'Wallet control was verified for this claim.':walletSelected?'Confirm the exact receiving address in your wallet. Selection alone does not prove control.':'Choose the receiving wallet below. Your award stays reserved while you complete the checks.',consented||signatureCollected?'Kontrola novčanika potvrđena je za ovaj zahtjev.':walletSelected?'Potvrdi točnu adresu primatelja u novčaniku. Sam odabir nije dokaz kontrole.':'Odaberi novčanik za primitak ispod. Nagrada ostaje rezervirana dok dovršiš provjere.')},
  {title:text('Your consent','Tvoj pristanak'),state:consented?'complete':signatureCollected&&!stopped?'current':'waiting',detail:text(consented?'Consent is recorded for this exact amount and destination.':signatureCollected?'Signature collected. Submit it to record your consent; retry does not require another signature.':'Review the amount and destination, then explicitly confirm this claim.',consented?'Pristanak je zabilježen za ovaj točan iznos i odredište.':signatureCollected?'Potpis je prikupljen. Pošalji ga za bilježenje pristanka; ponovni pokušaj ne traži novi potpis.':'Provjeri iznos i odredište, zatim izričito potvrdi ovaj zahtjev.')},
  {title:text('Approval & payment','Odobrenje i isplata'),state:payment==='confirmed'?'complete':consented&&!stopped?'current':'waiting',detail:text(payment==='confirmed'?'Controller approval and payment are confirmed. The receipt is shown below.':held?'The award needs review. Its share remains reserved.':expired?'This claim window has ended. Refresh to check the current award status.':payment==='submitted'?'Payment is processing. Check its receipt below.':approved?'Controller approval is recorded. Payment still requires a confirmed receipt.':'The rewards team and controller finish the required approval before payment.',payment==='confirmed'?'Odobrenje kontrolora i isplata su potvrđeni. Potvrda je prikazana ispod.':held?'Nagrada zahtijeva provjeru. Njezin udio ostaje rezerviran.':expired?'Rok ovog zahtjeva je istekao. Osvježi za provjeru trenutačnog stanja nagrade.':payment==='submitted'?'Isplata se obrađuje. Provjeri potvrdu ispod.':approved?'Odobrenje kontrolora je zabilježeno. Isplata i dalje zahtijeva potvrđenu transakciju.':'Tim za nagrade i kontrolor dovršavaju potrebna odobrenja prije isplate.')},
  {title:text('Confirmed receipt','Potvrda isplate'),state:payment==='confirmed'?'complete':'waiting',detail:text(payment==='confirmed'?'Payment is confirmed. The transaction and block are shown below.':'A submitted claim or transaction hash does not confirm payment.',payment==='confirmed'?'Isplata je potvrđena. Transakcija i blok prikazani su ispod.':'Poslani zahtjev ili hash transakcije ne potvrđuje isplatu.')},
 ];
}
export function clubClaimSteps({hr,loading,failed,signatures,recorded,stopped}:Context&{signatures:number;recorded:boolean;stopped:boolean}):ClaimStep[]{
 const text=(en:string,cr:string)=>hr?cr:en;
 if(loading||failed||stopped)return[{title:text('Review club award','Pregled klupske nagrade'),state:'unverified',detail:text(loading?'Checking the award and reviewed Safe…':'Close and reopen this award to get a fresh review. No new consent is available until checks succeed.',loading?'Provjeravamo nagradu i pregledani Safe…':'Zatvori i ponovno otvori ovu nagradu za novi pregled. Novi pristanak nije dostupan dok provjere ne uspiju.')}];
 return[
  {title:text('Club award & Safe','Klupska nagrada i Safe'),state:'complete',detail:text('This exact award pays the reviewed club treasury shown above.','Ova točna nagrada isplaćuje se na pregledanu klupsku riznicu prikazanu iznad.')},
  {title:text('Two Safe owners','Dva vlasnika Safea'),state:recorded||signatures>=2?'complete':'current',detail:text(recorded?"The required owner signatures were recorded for this claim.":`${signatures} / 2 signatures collected. Use two different reviewed owners.`,recorded?"Potrebni potpisi vlasnika zabilježeni su za ovaj zahtjev.":`${signatures} / 2 potpisa prikupljeno. Koristi dva različita pregledana vlasnika.`)},
  {title:text('Record club consent','Zabilježi klupski pristanak'),state:recorded?'complete':signatures>=2?'current':'waiting',detail:text(recorded?'Club consent is recorded.':'Collected signatures stay in this session until you explicitly submit them.',recorded?'Klupski pristanak je zabilježen.':'Prikupljeni potpisi ostaju u ovoj sesiji dok ih izričito ne pošalješ.')},
  {title:text('Approval & confirmed payment','Odobrenje i potvrđena isplata'),state:'waiting',detail:text('Return to the award to check controller approval and the payment receipt. Consent alone does not pay the club.','Vrati se na nagradu za provjeru odobrenja kontrolora i potvrde isplate. Sam pristanak ne isplaćuje klub.')},
 ];
}
