import type { AppLocale } from "@/shared/i18n/locales";

// Task 2 owns this additive dictionary; the shared catalog has concurrent owners.
const en = {
  clubSigning: {
    sourceHold: "The claim, source results or treasury review changed. Ask the organizer to check this exact claim; no signature or replacement payment is authorized here.",
    nextOwner: "Ask a different Safe owner to select their wallet account, then connect / refresh the signer. Never share or enter private keys.",
    open: "Review club consent", title: "Two-owner club consent", help: "Review this exact award before signing. Two different owners of the reviewed 2-of-3 Safe must authorize it. This records consent only; it does not send MON or spend the Safe balance.",
    network: "Network", amount: "Exact award", pot: "Reward pot", safe: "Receiving club Safe", expiry: "Signature expires (local time)",
    progress: "Signatures collected", memory: "These signatures are kept only in this open flow. Closing or reloading discards unsent signatures. Two collected signatures are not a verified Safe quorum until the server accepts them.",
    wallet: "Owner wallet", choose: "Choose a wallet", browser: "Browser wallet", noWallet: "No browser wallet detected. Open this demo in a browser with an owner’s wallet; never enter a private key here.",
    connect: "Connect / refresh signer", acknowledge: "I recognize the signer address shown above and approve signing this exact award to the displayed Safe.", sign: "Sign with this owner",
    submit: "Submit two-owner consent", recorded: "Club consent recorded — organizer approval/payment processing remains separate.", back: "Return to refreshed club rewards",
    duplicate: "This owner has already signed. Connect a different Safe owner.", needTwo: "Two different owner signatures are required.", collected: "Two signatures collected. Submit them for Safe-quorum verification; no payment has been sent.",
    busy: "Checking the exact claim or waiting for your wallet…", restart: "This signing session is closed. Close this panel and reopen a fresh review; the reward remains reserved.",
  },
  clubProgrammeAwards: "Programme club rewards (V3)", clubProgrammeHelp: "Reserved awards from the five rounds and league. Superseded revisions are history, not extra prizes. This view does not sign or send transactions.",
  clubRefresh: "Refresh programme club rewards", clubNoAwards: "No programme awards are recorded for this club.",
  clubSuperseded: "Superseded allocation · history only", clubLatest: "Latest recorded allocation · readiness checked separately",
  clubSynthetic: "Synthetic test results · not a real club award", clubPaid: "Test payment confirmed", clubPending: "Payment not confirmed",
  clubNotPrepared: "Share reserved · payment not prepared", clubOwnerReview: "An organizer must review the club ownership or treasury change. Previous private claim details are not shared.",
  clubConsentRecorded: "Club consent recorded. Consent alone does not confirm payment.",
  clubConsentNeeded: "Payment needs a reviewed 2-of-3 club Safe, two owner signatures and separate operator approval. Funds remain reserved.",
  clubEvidence: "Allocation and receipt evidence",
  clubPaymentStates: { prepared: "prepared, not sent", signed: "signed, not sent", queued: "queued", leased: "processing", broadcasting: "sending", submitted: "submitted, awaiting receipt", confirmed: "confirmed" },
  breakdownTitle: "Why this amount?", breakdownHelp: "These rows come from your saved allocation approval and add up to this award. They do not show current payment eligibility or replace the payment receipt.",
  placing: "Category placing", distanceReward: "Distance participation", approvedPool: "Approved pool",
  distanceFormula: "Your completed distance / all eligible completed distance", finishes: "finishes",
  roundingHelp: "The approved split includes deterministic rounding to whole wei.",
  placingHelp: "The saved rank curve sets the prize. Ties share the occupied prize slots; unused places keep their reserve.",
  sourceIdentifiers: "Approved source identifiers", categoryIdentifier: "Category ID", contributingResults: "Contributing result IDs",
  sourceApproved: "Frozen approved calculation · see ‘Why this amount?’ for your result rows.",
  awaitingOperator: "Use Authorized execution to review and authorize the exact operator signing plan. This requires a separately configured private runtime.",
  actionBoundary: "Demo only. Preparation, operator signing, scheduling and receipt confirmation are separate actions. No athlete wallets are created. Source holds block new actions; confirmed history is retained.",
  tree: "Allocation hierarchy", treeHelp: "Widths show each amount as a share of its parent. This is an allocation view, not a cryptographic proof or payment receipt.", remaining: "Retained / unassigned",
  execution: "Authorized execution", inspectPlan: "Inspect operator signing plan", signPlan: "Authorize this exact signature", signConfirm: "I approve the displayed plan, contract, operator and fee ceiling. Signing does not submit a transaction.",
  unavailable: "Execution is unavailable. Configure the isolated private runtime or retry the same action after the service recovers.",
  signed: "Signature recorded · not submitted", schedule: "Schedule the queued transaction", scheduleConfirm: "I authorize execution of this exact queued transaction within the displayed limits.",
  scheduled: "Scheduled · awaiting a verified receipt", executionStatus: "Refresh execution status", plan: "Exact signing plan", planHash: "Plan hash",
  reconciliationRequired: "This transaction may already have been sent. Check the original receipt; do not create a replacement or send it again.",
  operatorSessionRequired: "Execution is paused: a current authorized operator session is required. The saved transaction is retained.",
  executionHeld: "Execution needs operator review. Refresh the original transaction status; a scheduled job is not a confirmed payment.",
  profile: "Reward profile", chooseProfile: "Choose the profile that earned this reward", selectProfile: "Select a profile",
  profileHelp: "Wallet nomination applies only to the profile shown here. Check its identifier before continuing.",
  existingDestination: "Existing wallet destination", reuseDestination: "This profile already has a wallet destination. Use it for this profile’s prepared rewards; review or withdraw it in destination history before choosing another.",
  exact: "Exact amount", rounded: "Rounded to 4 decimals", wei: "Wei (exact)",
  activity: "Consent and receipt history", historyHelp: "These are attempts for this award, not additional earnings.",
  reserved: "Allocated share · payment not verified", unknown: "Payment status unavailable", retry: "Retry status check",
  noClaim: "Your allocated share is retained. A prepared claim and the required checks are needed before you can give consent.",
  source: "Source result", sourceUnavailable: "Result, rank and reward breakdown are not supplied by this allocation API yet.",
  reason: "Reward reason", reasonRound: "Approved round allocation", reasonLeague: "Approved league allocation",
  recovery: "Your selection is retained. Refresh to check current access and status; wallet authorization must be reviewed again.",
  refreshReview: "Reload consent review", historical: "Other prepared claim history", noExtra: "Prepared claims are history, not a second reward balance.",
  planned: "Planned", funded: "Funded", allocated: "Allocated", held: "Held", paid: "Paid", unallocated: "Unallocated", unknownAmount: "Not available",
  balancesHelp: "Funding and payment observations are separate from planned awards. Missing allocation and hold totals are not zero.",
  share: "Share of programme", attemptsIncomplete: "Load all prepared claims before reviewing consent. A receipt may be on another page.",
};
const hr: typeof en = {
  clubSigning: {
    sourceHold: "Zahtjev, izvorni rezultati ili pregled klupskog novčanika su promijenjeni. Organizator treba provjeriti ovaj točan zahtjev; ovdje se ne odobrava potpis ni zamjenska isplata.",
    nextOwner: "Drugi vlasnik Safe novčanika treba odabrati svoj račun, a zatim povezati ili osvježiti potpisnika. Nikada ne dijelite niti unosite privatne ključeve.",
    open: "Pregledaj suglasnost kluba", title: "Suglasnost dvaju vlasnika kluba", help: "Prije potpisa provjerite ovu nagradu. Moraju je odobriti dva različita vlasnika pregledanog Safe novčanika 2-od-3. Ovdje se bilježi samo suglasnost; MON se ne šalje niti se troši stanje Safe novčanika.",
    network: "Mreža", amount: "Točan iznos nagrade", pot: "Nagradni fond", safe: "Klupski Safe za primitak", expiry: "Istek potpisa (lokalno vrijeme)",
    progress: "Prikupljeni potpisi", memory: "Potpisi ostaju samo u ovom otvorenom postupku. Zatvaranje ili ponovno učitavanje odbacuje neposlane potpise. Dva prikupljena potpisa nisu potvrđen kvorum Safe novčanika dok ih poslužitelj ne prihvati.",
    wallet: "Novčanik vlasnika", choose: "Odaberite novčanik", browser: "Novčanik preglednika", noWallet: "Novčanik preglednika nije pronađen. Otvorite demo u pregledniku s novčanikom vlasnika; ovdje nikada ne unosite privatni ključ.",
    connect: "Poveži / osvježi potpisnika", acknowledge: "Prepoznajem gore prikazanu adresu potpisnika i odobravam potpis ove nagrade za prikazani Safe.", sign: "Potpiši kao ovaj vlasnik",
    submit: "Pošalji suglasnost dvaju vlasnika", recorded: "Suglasnost kluba je zabilježena — odobrenje organizatora i obrada isplate ostaju zasebni koraci.", back: "Vrati se na osvježene klupske nagrade",
    duplicate: "Ovaj vlasnik već je potpisao. Povežite drugog vlasnika Safe novčanika.", needTwo: "Potrebni su potpisi dvaju različitih vlasnika.", collected: "Prikupljena su dva potpisa. Pošaljite ih na provjeru kvoruma Safe novčanika; isplata nije poslana.",
    busy: "Provjera točnog zahtjeva ili čekanje novčanika…", restart: "Ovaj postupak potpisivanja je zatvoren. Zatvorite prikaz i otvorite novi pregled; nagrada ostaje rezervirana.",
  },
  clubProgrammeAwards: "Klupske nagrade iz programa (V3)", clubProgrammeHelp: "Rezervirane nagrade za pet kola i ligu. Zamijenjene verzije su povijest, a ne dodatne nagrade. Ovaj prikaz ne potpisuje ni šalje transakcije.",
  clubRefresh: "Osvježi klupske nagrade iz programa", clubNoAwards: "Za ovaj klub nema zabilježenih nagrada iz programa.",
  clubSuperseded: "Zamijenjena dodjela · samo povijest", clubLatest: "Najnovija zabilježena dodjela · spremnost se provjerava zasebno",
  clubSynthetic: "Sintetički testni rezultati · nije nagrada stvarnog kluba", clubPaid: "Testna isplata je potvrđena", clubPending: "Isplata nije potvrđena",
  clubNotPrepared: "Udio je rezerviran · isplata nije pripremljena", clubOwnerReview: "Organizator mora pregledati promjenu vlasništva kluba ili novčanika. Privatni podaci prethodnog zahtjeva nisu dostupni.",
  clubConsentRecorded: "Suglasnost kluba je zabilježena. Sama suglasnost ne potvrđuje isplatu.",
  clubConsentNeeded: "Za isplatu su potrebni provjereni klupski Safe 2-od-3, potpisi dvaju vlasnika i zasebno odobrenje operatora. Sredstva ostaju rezervirana.",
  clubEvidence: "Podaci o dodjeli i potvrdi isplate",
  clubPaymentStates: { prepared: "pripremljeno, nije poslano", signed: "potpisano, nije poslano", queued: "u redu čekanja", leased: "u obradi", broadcasting: "slanje", submitted: "poslano, čeka potvrdu", confirmed: "potvrđeno" },
  breakdownTitle: "Zašto ovaj iznos?", breakdownHelp: "Stavke su iz spremljenog odobrenja dodjele i njihov je zbroj jednak ovoj nagradi. Ne potvrđuju trenutačnu spremnost za isplatu i ne zamjenjuju potvrdu isplate.",
  placing: "Poredak u kategoriji", distanceReward: "Nagrada za prijeđenu udaljenost", approvedPool: "Odobreni fond",
  distanceFormula: "Vaša završena udaljenost / ukupna završena udaljenost svih sudionika koji ispunjavaju uvjete", finishes: "završetaka",
  roundingHelp: "Odobrena podjela uključuje determinističko zaokruživanje na cijeli wei.",
  placingHelp: "Spremljeni omjeri po mjestima određuju nagradu. Izjednačeni dijele zauzeta mjesta; nepopunjena mjesta zadržavaju pričuvu.",
  sourceIdentifiers: "Identifikatori odobrenih izvora", categoryIdentifier: "ID kategorije", contributingResults: "ID-jevi rezultata koji doprinose nagradi",
  sourceApproved: "Zaključani odobreni izračun · svoje rezultate pogledajte pod „Zašto ovaj iznos?”.",
  awaitingOperator: "U odjeljku Odobreno izvršavanje pregledajte i odobrite točan plan potpisa operatora. Potrebno je zasebno postavljeno privatno izvršavanje.",
  actionBoundary: "Samo demonstracija. Priprema, potpis operatora, zakazivanje i potvrda isplate odvojene su radnje. Ovdje nema stvaranja novčanika natjecatelja. Zadržavanje izvora sprječava nove radnje; potvrđena povijest ostaje sačuvana.",
  tree: "Hijerarhija dodjele", treeHelp: "Širine prikazuju udio svakog iznosa u nadređenoj grani. Ovo je prikaz dodjele, a ne kriptografski dokaz ili potvrda isplate.", remaining: "Sačuvano / neraspoređeno",
  execution: "Odobreno izvršavanje", inspectPlan: "Pregledaj plan potpisa operatora", signPlan: "Odobri ovaj točan potpis", signConfirm: "Odobravam prikazani plan, ugovor, operatora i gornju granicu naknade. Potpis ne šalje transakciju.",
  unavailable: "Izvršavanje nije dostupno. Postavite izolirano privatno izvršavanje ili ponovite istu radnju nakon oporavka usluge.",
  signed: "Potpis zabilježen · nije poslano", schedule: "Zakaži transakciju iz reda", scheduleConfirm: "Odobravam izvršavanje ove točne transakcije iz reda unutar prikazanih ograničenja.",
  scheduled: "Zakazano · čeka provjerenu potvrdu", executionStatus: "Osvježi status izvršavanja", plan: "Točan plan potpisa", planHash: "Sažetak plana",
  reconciliationRequired: "Ova je transakcija možda već poslana. Provjerite izvornu potvrdu; nemojte stvarati zamjenu ni ponovno slati transakciju.",
  operatorSessionRequired: "Izvršavanje je zaustavljeno: potrebna je važeća sesija ovlaštenog operatora. Spremljena transakcija ostaje sačuvana.",
  executionHeld: "Izvršavanje zahtijeva pregled operatora. Osvježite status izvorne transakcije; zakazani zadatak nije potvrđena isplata.",
  profile: "Profil za nagradu", chooseProfile: "Odaberite profil koji je osvojio nagradu", selectProfile: "Odaberite profil",
  profileHelp: "Odredište novčanika odnosi se samo na prikazani profil. Provjerite identifikator prije nastavka.",
  existingDestination: "Postojeće odredište novčanika", reuseDestination: "Ovaj profil već ima odredište novčanika. Koristite ga za pripremljene nagrade ovog profila; pregledajte ili povucite ga u povijesti prije odabira drugog.",
  exact: "Točan iznos", rounded: "Zaokruženo na 4 decimale", wei: "Wei (točno)",
  activity: "Povijest suglasnosti i potvrda", historyHelp: "Ovo su pokušaji za ovu nagradu, a ne dodatna zarada.",
  reserved: "Dodijeljeni udio · isplata nije provjerena", unknown: "Status isplate nije dostupan", retry: "Ponovi provjeru statusa",
  noClaim: "Vaš dodijeljeni udio ostaje sačuvan. Za suglasnost su potrebni pripremljeni zahtjev i propisane provjere.",
  source: "Izvorni rezultat", sourceUnavailable: "API dodjele još ne daje rezultat, poredak ni raščlambu nagrade.",
  reason: "Razlog nagrade", reasonRound: "Odobrena dodjela za kolo", reasonLeague: "Odobrena dodjela za ligu",
  recovery: "Odabir je sačuvan. Osvježite pristup i status; odobrenje u novčaniku treba ponovno pregledati.",
  refreshReview: "Ponovno učitaj pregled suglasnosti", historical: "Ostala povijest pripremljenih zahtjeva", noExtra: "Pripremljeni zahtjevi su povijest, a ne drugo stanje nagrada.",
  planned: "Planirano", funded: "Uplaćeno", allocated: "Dodijeljeno", held: "Zadržano", paid: "Isplaćeno", unallocated: "Nedodijeljeno", unknownAmount: "Nije dostupno",
  balancesHelp: "Opažanja uplata i isplata odvojena su od plana nagrada. Nepoznati iznosi dodjele i zadržavanja nisu nula.",
  share: "Udio programa", attemptsIncomplete: "Učitajte sve pripremljene zahtjeve prije pregleda suglasnosti. Potvrda može biti na drugoj stranici.",
};
export const productCopy = (locale: AppLocale) => locale === "hr" ? hr : en;
