import type {AppLocale} from "@/shared/i18n/locales";
const hr:Record<string,string> = {
  "Loading account…": "Učitavanje računa…",
  "Wallet administration": "Administracija novčanika",
  "Sign in with your RacesOn master-admin account.": "Prijavi se svojim glavnim administratorskim računom RacesOn.",
  "Sign in": "Prijavi se",
  "Master-admin access required": "Potreban je pristup glavnog administratora",
  "Only an active master administrator can change Podium’s operational wallets.": "Samo aktivni glavni administrator može promijeniti operativne novčanike Podiuma.",
  "Back to Podium": "Natrag na Podium",
  "Master administration · Monad testnet": "Glavna administracija · testna mreža Monad",
  "Operational wallets": "Operativni novčanici",
  "Separate gas for campaign creation from reviewed reward distribution.": "Odvoji gas za stvaranje kampanja od pregledane raspodjele nagrada.",
  "Reload settings": "Ponovno učitaj postavke",
  "Verifying your current access and wallet settings…": "Provjera trenutačnog pristupa i postavki novčanika…",
  "Loading wallet settings…": "Učitavanje postavki novčanika…",
  "The initial provider configuration is not ready. Configure the existing controller and restricted deployment service before choosing replacements.": "Početna konfiguracija pružatelja nije spremna. Postavi postojećeg kontrolora i ograničenu uslugu stvaranja kampanja prije odabira zamjene.",
  "Both roles currently use the same wallet. Replace the deployment wallet to give campaign creation its own transaction queue.": "Obje uloge trenutačno koriste isti novčanik. Zamijeni novčanik za stvaranje kampanja kako bi ono imalo vlastiti red transakcija.",
  "Automatic creation": "Automatsko stvaranje",
  "Explicit review & signing": "Izričit pregled i potpisivanje",
  "Deployment wallet": "Novčanik za stvaranje kampanja",
  "Distribution controller": "Kontrolor raspodjele",
  "Pays creation gas. Its service access is restricted to the verified factory on Monad testnet.": "Plaća gas za stvaranje kampanja. Pristup usluge ograničen je na potvrđenu tvornicu na testnoj mreži Monad.",
  "Signs approved allocations and opens claims. Sponsor funds remain in campaign contracts.": "Potpisuje odobrene raspodjele i otvara preuzimanje. Sredstva sponzora ostaju u ugovorima kampanja.",
  "Changes apply to new work. Existing campaigns keep their original controller; pending transactions keep their original signer and nonce. Changing these settings does not transfer funds or cancel transactions.": "Promjene vrijede za novi rad. Postojeće kampanje zadržavaju izvornog kontrolora; transakcije na čekanju zadržavaju izvornog potpisnika i nonce. Promjena postavki ne prenosi sredstva ni otkazuje transakcije.",
  "Create a new wallet in Privy, or enter an existing wallet ID. The wallet owner approves restricted campaign-creation access before Podium verifies the replacement.": "Stvori novi novčanik u Privyju ili unesi ID postojećeg novčanika. Vlasnik novčanika odobrava ograničeni pristup stvaranju kampanja prije nego što Podium provjeri zamjenu.",
  "Choose an existing native Privy wallet owned by a user. Podium verifies its address and owner with Privy.": "Odaberi postojeći izvorni Privy novčanik u vlasništvu korisnika. Podium provjerava adresu i vlasnika s Privyjem.",
  "Create with Privy": "Stvori s Privyjem",
  "Sign in as the current deployment policy’s owner. Creating a wallet does not activate it or move funds.": "Prijavi se kao vlasnik trenutačnih pravila stvaranja kampanja. Stvaranje novčanika ne aktivira ga ni prenosi sredstva.",
  "Create new wallet with Privy": "Stvori novi novčanik s Privyjem",
  "Privy creation is unavailable in this environment. You can still enter an existing wallet ID.": "Stvaranje kroz Privy nije dostupno u ovom okruženju. I dalje možeš unijeti ID postojećeg novčanika.",
  "New Privy wallet ID": "ID novog Privy novčanika",
  "This is the wallet’s public provider ID, not a private key or recovery phrase.": "Ovo je javni ID novčanika kod pružatelja, a ne privatni ključ ili fraza za oporavak.",
  "Verify replacement": "Provjeri zamjenu",
  "Review wallet change": "Pregledaj promjenu novčanika",
  "Current": "Trenutačni",
  "Replacement": "Zamjena",
  "Network": "Mreža",
  "Monad testnet · 10143": "Testna mreža Monad · 10143",
  "Reason for change": "Razlog promjene",
  "I reviewed the address and understand that existing campaigns and pending transactions keep their original authority.": "Pregledao/la sam adresu i razumijem da postojeće kampanje i transakcije na čekanju zadržavaju izvornu ovlast.",
  "Activate replacement": "Aktiviraj zamjenu",
  "Cancel edit": "Odustani od uređivanja",
  "Change history": "Povijest promjena",
  "Date": "Datum",
  "Changed by": "Promijenio/la",
  "Reason": "Razlog",
  "Wallets": "Novčanici",
  "Wallet change history": "Povijest promjena novčanika",
  "Scroll horizontally for reasons and wallet addresses.": "Pomakni vodoravno za razloge i adrese novčanika.",
  "View addresses": "Pogledaj adrese",
  "Open this controller": "Otvori ovog kontrolora",
  "No wallet changes have been recorded. Current settings come from the initial server configuration.": "Nijedna promjena novčanika nije zabilježena. Trenutačne postavke dolaze iz početne konfiguracije poslužitelja.",
  "Wallet settings could not be loaded. Your current master-admin session is required.": "Postavke novčanika nisu učitane. Potrebna je važeća sesija glavnog administratora.",
  "The wallet could not be verified or settings changed. Reload settings and check the wallet’s ownership and restricted deployment access. No change was confirmed.": "Novčanik nije provjeren ili su postavke promijenjene. Ponovno učitaj postavke i provjeri vlasništvo te ograničeni pristup stvaranju kampanja. Promjena nije potvrđena.",
  "Privy did not confirm this step. Check the wallets below before trying again. Nothing has been activated.": "Privy nije potvrdio ovaj korak. Provjeri novčanike ispod prije novog pokušaja. Ništa nije aktivirano.",
  "Connecting to Privy…": "Povezivanje s Privyjem…",
  "Connect the native Privy account that owns the deployment policy. Your Podium login remains separate.": "Poveži izvorni Privy račun vlasnika pravila stvaranja kampanja. Tvoja prijava u Podium ostaje zasebna.",
  "Sign in with Privy": "Prijavi se s Privyjem",
  "This is a sponsor or athlete wallet session. Switch to the native deployment-owner account.": "Ovo je sesija novčanika sponzora ili natjecatelja. Prebaci se na izvorni račun vlasnika pravila stvaranja kampanja.",
  "This Privy account does not own the current deployment policy. Switch to its owner to create a replacement.": "Ovaj Privy račun nije vlasnik trenutačnih pravila stvaranja kampanja. Prebaci se na vlasnikov račun za stvaranje zamjene.",
  "Switch Privy account": "Promijeni Privy račun",
  "Connected to the deployment policy’s owner.": "Povezano s vlasnikom pravila stvaranja kampanja.",
  "Create deployment wallet": "Stvori novčanik za stvaranje kampanja",
  "Creation has been requested. If no wallet appears, reconnect this Privy account to refresh its wallet list before creating another.": "Stvaranje je zatraženo. Ako se novčanik ne pojavi, ponovno poveži ovaj Privy račun radi osvježavanja popisa prije stvaranja drugog.",
  "Or use another wallet on this account": "Ili koristi drugi novčanik na ovom računu",
  "Choose a wallet": "Odaberi novčanik",
  "Replacement wallet": "Zamjenski novčanik",
  "Allow Podium’s deployment service to call the approved factory on Monad testnet (10143), with zero MON transferred by the call. Gas is paid from this wallet.": "Dopusti Podiumovoj usluzi stvaranja kampanja poziv odobrene tvornice na testnoj mreži Monad (10143), bez prijenosa MON-a pozivom. Gas se plaća iz ovog novčanika.",
  "View restricted permission": "Pogledaj ograničeno dopuštenje",
  "I approve this restricted campaign-creation permission for the displayed wallet.": "Odobravam ovo ograničeno dopuštenje stvaranja kampanja za prikazani novčanik.",
  "Permission submitted": "Dopuštenje poslano",
  "Approve restricted access in Privy": "Odobri ograničeni pristup u Privyju",
  "Privy confirmed the permission request. Podium will independently verify it before activation.": "Privy je potvrdio zahtjev za dopuštenje. Podium će ga neovisno provjeriti prije aktivacije.",
  "Use this wallet for verification": "Koristi ovaj novčanik za provjeru",
  "Waiting for Privy’s wallet ID. Reconnect to refresh this wallet; do not create another.": "Čeka se ID Privy novčanika. Ponovno se poveži radi osvježavanja ovog novčanika; nemoj stvarati drugi.",
  "Waiting for Privy…": "Čekanje Privyja…",
  "Sponsor self-service": "Samostalno stvaranje za sponzore",
  "Automatic campaign creation": "Automatsko stvaranje kampanja",
  "Campaign creation is waiting for this controller request.": "Stvaranje kampanja čeka dovršetak ovog zahtjeva kontrolora.",
  "Provider access verified · separate deployment wallet": "Pristup pružatelju potvrđen · zaseban novčanik za stvaranje kampanja",
  "Ready · deployment-only controller access verified": "Spremno · potvrđen pristup kontrolora samo za stvaranje kampanja",
  "The separate deployment wallet needs verified provider access. A master administrator can review it in Wallet administration.": "Zasebni novčanik za stvaranje kampanja treba potvrđen pristup pružatelju. Glavni administrator može ga pregledati u Administraciji novčanika.",
  "One-time setup lets sponsors create campaigns automatically using your controller’s gas. Every distribution still requires your review and Privy confirmation.": "Jednokratne postavke omogućuju sponzorima automatsko stvaranje kampanja uz gas kontrolora. Svaka raspodjela i dalje zahtijeva tvoj pregled i potvrdu u Privyju.",
  "Review one-time setup": "Pregledaj jednokratne postavke",
  "Deployment contract verified on Monad testnet.": "Ugovor za stvaranje kampanja potvrđen je na testnoj mreži Monad.",
  "Enable automatic campaign creation": "Omogući automatsko stvaranje kampanja",
  "Deployment-only Privy access is being configured for this contract.": "Za ovaj ugovor postavlja se pristup Privyju samo za stvaranje kampanja.",
  "Distribution requests use your controller wallet. Campaign creation uses": "Zahtjevi raspodjele koriste novčanik kontrolora. Stvaranje kampanja koristi",
  "and has its own transaction queue.": "i ima vlastiti red transakcija.",
  "One-time deployment setup": "Jednokratne postavke stvaranja kampanja",
  "Distribution transaction": "Transakcija raspodjele",
  "receipt verification needed": "potrebna provjera potvrde transakcije",
  "no signature recorded by the server": "poslužitelj nije zabilježio potpis",
  "The reserved nonce has not been used on the checked chain. A signature may still be saved in another browser.": "Rezervirani nonce nije korišten na provjerenom lancu. Potpis još može biti spremljen u drugom pregledniku.",
  "The network reports a pending transaction at this nonce. Recover the saved transaction to verify its outcome.": "Mreža prijavljuje transakciju na čekanju za ovaj nonce. Oporavi spremljenu transakciju za provjeru ishoda.",
  "The reserved nonce has been used on-chain. This does not confirm this distribution. Verify its saved receipt before continuing.": "Rezervirani nonce je korišten na lancu. To ne potvrđuje ovu raspodjelu. Provjeri spremljenu potvrdu transakcije prije nastavka.",
  "Chain status is unavailable. The distribution request remains reserved; check setup status to retry.": "Stanje lanca nije dostupno. Zahtjev raspodjele ostaje rezerviran; provjeri stanje postavki za novi pokušaj.",
  "Chain status is unavailable. The saved request still holds campaign creation; check setup status to retry.": "Stanje lanca nije dostupno. Spremljeni zahtjev i dalje zadržava stvaranje kampanja; provjeri stanje postavki za novi pokušaj.",
  "Request and network details": "Pojedinosti zahtjeva i mreže",
  "Request": "Zahtjev",
  "Campaign": "Kampanja",
  "Action": "Radnja",
  "Upload approved awards": "Pošalji odobrene nagrade",
  "Stage approved distribution": "Pripremi odobrenu raspodjelu",
  "Open claims": "Otvori preuzimanje",
  "Controller": "Kontrolor",
  "Destination": "Odredište",
  "Contract creation": "Stvaranje ugovora",
  "Reserved nonce": "Rezervirani nonce",
  "Finalized / pending nonce": "Finalizirani / nonce na čekanju",
  "Checked at (UTC)": "Provjereno (UTC)",
  "This check cannot cancel a request or prove a reward payment. The reservation stays in place until its outcome is verified.": "Ova provjera ne može otkazati zahtjev ni dokazati isplatu nagrade. Rezervacija ostaje dok se ne potvrdi ishod.",
  "Maximum fee:": "Najveća naknada:",
  "test MON. Reward deposit: 0.": "testni MON. Polog nagrada: 0.",
  "Deployment contract:": "Ugovor za stvaranje kampanja:",
  "Open the saved campaign to review its awards before wallet confirmation.": "Otvori spremljenu kampanju za pregled nagrada prije potvrde u novčaniku.",
  "Review pending distribution": "Pregledaj raspodjelu na čekanju",
  "Verify saved transaction": "Provjeri spremljenu transakciju",
  "Confirm setup with Privy": "Potvrdi postavke s Privyjem",
  "Recover a saved signature": "Oporavi spremljeni potpis",
  "Already confirmed in this browser? Recover the saved signature without signing again. If no signature was saved, return to campaign review.": "Već potvrđeno u ovom pregledniku? Oporavi spremljeni potpis bez ponovnog potpisivanja. Ako potpis nije spremljen, vrati se na pregled kampanje.",
  "RacesOn pays creation and distribution gas. Sponsors deposit their own reward funds into campaign contracts.": "RacesOn plaća gas za stvaranje kampanja i raspodjelu. Sponzori polažu vlastita sredstva za nagrade u ugovore kampanja.",
  "Check setup status": "Provjeri stanje postavki",
  "Setup status could not be checked. Refresh to retry.": "Stanje postavki nije provjereno. Osvježi za novi pokušaj.",
  "No signature is saved in this browser. Check setup status for a transaction saved by the server. Otherwise, use the browser where you confirmed or return to campaign review. The request remains reserved.": "U ovom pregledniku nema spremljenog potpisa. Provjeri stanje postavki za transakciju spremljenu na poslužitelju. Inače koristi preglednik u kojem si potvrdio/la ili se vrati na pregled kampanje. Zahtjev ostaje rezerviran.",
  "Your controller session changed. Sign in with the assigned controller account before recovering this request.": "Sesija kontrolora se promijenila. Prijavi se dodijeljenim računom kontrolora prije oporavka ovog zahtjeva.",
  "Another controller transaction is pending. Complete it before continuing.": "Druga transakcija kontrolora je na čekanju. Dovrši je prije nastavka.",
  "The step is not confirmed. Refresh or retry the saved transaction.": "Korak nije potvrđen. Osvježi ili ponovno pokušaj spremljenu transakciju.",
  "Controller wallet balance": "Stanje novčanika kontrolora",
  "Operations wallet": "Operativni novčanik",
  "Controller funds": "Sredstva kontrolora",
  "Checking…": "Provjera…",
  "Refresh balance": "Osvježi stanje",
  "test MON": "testni MON",
  "Pays explicitly approved distribution fees. Campaign creation uses its configured deployment wallet. These costs never come from sponsor reward pots.": "Plaća izričito odobrene naknade raspodjele. Stvaranje kampanja koristi postavljeni novčanik za stvaranje. Ti troškovi nikad ne dolaze iz nagradnih fondova sponzora.",
  "Balance unavailable. Refresh to try again.": "Stanje nije dostupno. Osvježi za novi pokušaj.",
  "Add test MON to cover campaign fees.": "Dodaj testni MON za naknade kampanja.",
  "Add funds to this wallet": "Dodaj sredstva u ovaj novčanik",
  "Send test MON on": "Pošalji testni MON putem",
  "Monad testnet": "testne mreže Monad",
  "to this address, then refresh the balance.": "na ovu adresu, zatim osvježi stanje.",
  "Address copied": "Adresa kopirana",
  "Copy wallet address": "Kopiraj adresu novčanika"
};
export const walletAdminText = (locale:AppLocale, text:string) => {
  if(locale !== "hr") return text;
  if(/^The wallet changed the prepared .+\. Nothing was sent\.$/.test(text)) return "Novčanik je promijenio pripremljenu transakciju. Ništa nije poslano.";
  return hr[text] ?? text;
};
