/** Copy for the shared rewards workspace. Both demo presentations use this vocabulary. */
const en = {
  public: "Public programme", organizer: "Organizer", tools: "Demo tools", calculator: "Planning calculator",
  trial: "Contract trials", private: "Private workspace", overview: "Overview", rules: "Rules & setup",
  results: "Results & allocations", recipients: "Recipients", funding: "Funding & contract", activity: "Activity",
  programme: "Reward programme", planned: "Planned budget", funded: "Programme deposits", allocated: "Uploaded allocations",
  paid: "Confirmed paid", unknown: "Not verified", refresh: "Refresh overview", pots: "Five rounds and league",
  pot: "Pot", budget: "Budget", state: "Contract state", next: "Next step", inspect: "Inspect pot",
  attention: "Needs attention", fundingNext: "Check programme funding and contract registration.",
  resultsNext: "Verify the selected sources and review the exact allocation for each pot.",
  observation: "Observed at block", scope: "Saved rules and observed contract facts are shown separately.",
  mapping: "Race and category mapping", viewPublic: "Public demo prospectus", technical: "Programme identifiers",
  activityHelp: "Saved revision and contract observations. Exact approval and payment histories remain attached to their allocation or recipient.",
  updated: "Rules last saved", revision: "Saved revision", noRuntime: "Execution capability is checked when you inspect an exact operation.",
  allocationHelp: "Uploaded allocations are on-chain amounts, not a sum of draft previews. Unpaid shares remain reserved.",
  sourceUnknown: "Source review required", unpublished: "Not published", publicTitle: "Follow every reward",
  publicIntro: "Explore the programme rules, each round’s allocation and the rewards athletes and clubs earn.",
  publicationPending: "Programme publication pending", publicationHelp: "The target budget and suggested split are shown below. An organizer has not published an approved athlete distribution here yet.",
  athletes: "Athlete distribution", clubs: "Club distribution", name: "Recipient", league: "League placing", distance: "Distance award", total: "Total allocated",
  search: "Search recipients", empty: "No published allocations yet", emptyHelp: "Approved rounds and totals will appear here after publication. Unpublished amounts are not zero.",
  noMatches: "No recipients match this search.", publicPrivacy: "Allocation transparency does not disclose private wallet, identity-review or consent information.",
  viewRules: "Distribution rules", why: "How is this calculated?", publicEvidence: "Publication and contract evidence",
  pendingValue: "Not published", filtered: "Filtered total", rowDetails: "Allocation breakdown", viewCalculator: "Explore a planning scenario",
  totalsTitle: "Your rewards at a glance", earned: "Total allocated", paidKnown: "Verified paid", waiting: "Awaiting payment", claimability: "Claim availability",
  checkPerAward: "Checked per award", incomplete: "Load all award pages to see a complete total. Claim attempts never count as additional earnings.",
  allLoaded: "Totals count each recorded award once. Allocated rewards are not your wallet balance.",
  nextAthlete: "Your next step", nextWallet: "Set or review your receiving wallet, then open an award to review its claim.",
  nextAwards: "Open an award to see its preparation, consent and payment status.", awardsLink: "View my awards", walletLink: "Wallet settings",
  walletSummary: "Receiving wallet", walletSettings: "Manage receiving wallet", allProgrammes: "All programmes",
  selectedProgramme: "Programme", programmeId: "Programme identifier", noName: "Saved programme", scopeAll: "All returned programmes",
  awaitingPreparation: "Awaiting organizer preparation", privacyBoundary: "Public view · No wallet connection required",
  previewOnly: "Planning example · Not an approved allocation", backOverview: "Back to overview",
  legacyRecipients: "Existing recipient workspaces", legacyHelp: "Select the registered reward programme explicitly. A shared season alone does not prove it is the selected planning draft.",
} as const;
const hr: Record<keyof typeof en, string> = {
  public: "Javni program", organizer: "Organizator", tools: "Demo alati", calculator: "Kalkulator plana",
  trial: "Probni ugovori", private: "Privatni radni prostor", overview: "Pregled", rules: "Pravila i postavke",
  results: "Rezultati i raspodjela", recipients: "Primatelji", funding: "Financiranje i ugovor", activity: "Aktivnosti",
  programme: "Program nagrada", planned: "Planirani fond", funded: "Uplate u program", allocated: "Dodijeljeno na lancu",
  paid: "Potvrđeno isplaćeno", unknown: "Nije provjereno", refresh: "Osvježi pregled", pots: "Pet kola i liga",
  pot: "Fond", budget: "Proračun", state: "Stanje ugovora", next: "Sljedeći korak", inspect: "Pregledaj fond",
  attention: "Potrebna radnja", fundingNext: "Provjerite financiranje programa i registraciju ugovora.",
  resultsNext: "Provjerite odabrane izvore i točnu raspodjelu svakog fonda.",
  observation: "Provjereno u bloku", scope: "Spremljena pravila i opaženo stanje ugovora prikazani su zasebno.",
  mapping: "Povezivanje utrka i kategorija", viewPublic: "Javni plan demo programa", technical: "Identifikatori programa",
  activityHelp: "Spremljena revizija i opažanja ugovora. Povijest odobrenja i isplata ostaje uz odgovarajuću raspodjelu ili primatelja.",
  updated: "Pravila zadnji put spremljena", revision: "Spremljena revizija", noRuntime: "Dostupnost izvršavanja provjerava se pri pregledu točne radnje.",
  allocationHelp: "Dodijeljeni iznosi na lancu nisu zbroj nacrta raspodjele. Neisplaćeni iznosi ostaju rezervirani.",
  sourceUnknown: "Potrebna provjera izvora", unpublished: "Nije objavljeno", publicTitle: "Pratite svaku nagradu",
  publicIntro: "Istražite pravila programa, raspodjelu svakog kola i nagrade sportaša i klubova.",
  publicationPending: "Čeka se objava programa", publicationHelp: "U nastavku su ciljni proračun i predložena raspodjela. Organizator ovdje još nije objavio odobrenu raspodjelu za sportaše.",
  athletes: "Raspodjela sportašima", clubs: "Raspodjela klubovima", name: "Primatelj", league: "Plasman u ligi", distance: "Nagrada za udaljenost", total: "Ukupno dodijeljeno",
  search: "Pretraži primatelje", empty: "Još nema objavljenih nagrada", emptyHelp: "Odobrena kola i ukupni iznosi pojavit će se nakon objave. Neobjavljeni iznosi nisu nula.",
  noMatches: "Nema primatelja koji odgovaraju pretrazi.", publicPrivacy: "Javna raspodjela ne otkriva privatne podatke o novčaniku, provjeri identiteta ili pristanku.",
  viewRules: "Pravila raspodjele", why: "Kako se izračunava?", publicEvidence: "Dokazi objave i ugovora",
  pendingValue: "Nije objavljeno", filtered: "Filtrirani zbroj", rowDetails: "Objašnjenje raspodjele", viewCalculator: "Istraži scenarij raspodjele",
  totalsTitle: "Vaše nagrade ukratko", earned: "Ukupno dodijeljeno", paidKnown: "Potvrđeno isplaćeno", waiting: "Čeka isplatu", claimability: "Dostupnost preuzimanja",
  checkPerAward: "Provjera uz svaku nagradu", incomplete: "Učitajte sve stranice nagrada za potpuni zbroj. Pokušaji preuzimanja nisu dodatne nagrade.",
  allLoaded: "Svaka spremljena nagrada broji se jednom. Dodijeljene nagrade nisu stanje vašeg novčanika.",
  nextAthlete: "Vaš sljedeći korak", nextWallet: "Postavite ili provjerite novčanik primatelja, zatim otvorite nagradu i pregledajte preuzimanje.",
  nextAwards: "Otvorite nagradu za pregled pripreme, pristanka i stanja isplate.", awardsLink: "Pregledaj moje nagrade", walletLink: "Postavke novčanika",
  walletSummary: "Novčanik primatelja", walletSettings: "Upravljaj novčanikom primatelja", allProgrammes: "Svi programi",
  selectedProgramme: "Program", programmeId: "Identifikator programa", noName: "Spremljeni program", scopeAll: "Svi dohvaćeni programi",
  awaitingPreparation: "Čeka pripremu organizatora", privacyBoundary: "Javni pregled · Povezivanje novčanika nije potrebno",
  previewOnly: "Primjer plana · Raspodjela nije odobrena", backOverview: "Natrag na pregled",
  legacyRecipients: "Postojeći prostori primatelja", legacyHelp: "Izričito odaberite registrirani program nagrada. Ista sezona sama po sebi ne potvrđuje povezanost s odabranim nacrtom.",
};
export const workspaceCopy = (locale: string): Record<keyof typeof en, string> => locale === "hr" ? hr : en;
