import {act,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {beforeEach,expect,it,vi} from 'vitest';
import HostedAwardReview from './HostedAwardReview';
const mocks=vi.hoisted(()=>({review:vi.fn(),upload:vi.fn(),handoff:vi.fn(),publish:vi.fn(),authorize:vi.fn()}));
vi.mock('../data/hostedAwardReview',()=>({readHostedAwardReview:mocks.review}));
vi.mock('../data/hostedAwardUpload',()=>({readHostedAwardUpload:mocks.upload,readHostedAwardHandoff:mocks.handoff}));
vi.mock('../data/reviewPublication',()=>({readReviewPublication:mocks.publish}));
vi.mock('../components/RewardEmbeddedWalletContext',()=>({useRewardEmbeddedWallet:()=>({status:'ready',wallet:null,reviewerConnected:true,authorizePublication:mocks.authorize})}));
vi.mock('@/lib/auth',()=>({useAuth:()=>({session:null})}));
vi.mock('../model/useRewardSessionEpoch',()=>({useRewardSessionEpoch:()=> 'same-session'}));
const contextHash='c'.repeat(64),documentHash='d'.repeat(64);
const review={contextHash,documentHash,historicalAcknowledgement:false,approval:null,recorded:null,proposedWei:'880000000000000000',retainedWei:'120000000000000000',reasons:[],recipientCounts:{athletes:17,clubs:0}};
const approved={...review,approval:{id:'approval',decision:'approved',current:true,documentHash}};
const upload={current:true,protocolVersion:5,prepared:null,contextHash,documentHash};
const prepared={...upload,prepared:{id:'package',packageHash:'e'.repeat(64)}};
const handoff={current:true,publication:null,publicationHash:'f'.repeat(64)};
const publication={ownership:'owned',state:1,claimsOpen:false,next:'upload',pending:null};
beforeEach(()=>vi.clearAllMocks());
it('one reviewer decision carries the exact allocation through all three chain receipts to open claims',async()=>{
 const order:string[]=[];let allocation=review,packageReady=false,handedOff=false,step=0;
 const actions=['upload','stage','activate'];
 mocks.review.mockImplementation(async(_id,_slot,command)=>{if(command){order.push('approve');allocation=approved;}return allocation;});
 mocks.upload.mockImplementation(async(_scope,command)=>{if(command){order.push('prepare');packageReady=true;}return packageReady?prepared:upload;});
 mocks.handoff.mockImplementation(async(_scope,command)=>{if(command){order.push('handoff');handedOff=true;}return {...handoff,publication:handedOff?{id:'publication'}:null};});
 mocks.publish.mockImplementation(async(_scope,digest,advance,signature)=>{
  expect(digest).toBe(documentHash);expect(handedOff).toBe(true);
  if(!advance)return publication;
  if(!signature)return {...publication,next:actions[step],authorization:{transactionId:actions[step]},pending:{action:actions[step],confirmed:false,hash:null}};
  expect(signature.transactionId).toBe(actions[step]);order.push(actions[step]);step++;
  return {...publication,state:step===3?3:step===2?2:1,claimsOpen:step===3,next:actions[step]??null,pending:{action:actions[step-1],confirmed:true,hash:`0x${step}`}};
 });
 mocks.authorize.mockImplementation(async v=>({transactionId:v.authorization.transactionId,authorizationSignature:'fictional',requestExpiry:999}));
 render(<HostedAwardReview id="setup" slot={4} hr={false}/>);
 await screen.findByRole('checkbox');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Approve and open claims'}));
 expect(await screen.findByText('Claims are open.')).toBeVisible();
 expect(order).toEqual(['approve','prepare','handoff','upload','stage','activate']);expect(mocks.authorize).toHaveBeenCalledTimes(3);
 expect(screen.queryByRole('button',{name:'Resume approved publication'})).not.toBeInTheDocument();
 expect(screen.queryByText(/recipient requests|athlete verification|club treasury verification/i)).not.toBeInTheDocument();
 expect(mocks.review.mock.calls.filter(c=>c[2])).toHaveLength(1);
});
it('an already approved and prepared campaign resumes publication without reviewing results again',async()=>{
 mocks.review.mockResolvedValue(approved);mocks.upload.mockResolvedValue(prepared);mocks.handoff.mockResolvedValue({...handoff,publication:{id:'publication'}});
 mocks.publish.mockResolvedValueOnce(publication).mockResolvedValue({...publication,state:3,claimsOpen:true,next:null});
 render(<HostedAwardReview id="setup" slot={4} hr={false}/>);
 const resume=await screen.findByRole('button',{name:'Resume approved publication'});
 expect(mocks.publish).toHaveBeenCalledOnce();expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();
 fireEvent.click(resume);await screen.findByText('Claims are open.');
 expect(mocks.review.mock.calls).toEqual([['setup',4]]);expect(mocks.upload).toHaveBeenCalledOnce();expect(mocks.handoff).toHaveBeenCalledOnce();
});
it('a rejected publication stays stopped after one approval and exposes resume',async()=>{
 mocks.review.mockResolvedValueOnce(review).mockResolvedValue(approved);mocks.upload.mockResolvedValue(prepared);mocks.handoff.mockResolvedValue({...handoff,publication:{id:'publication'}});
 mocks.publish.mockResolvedValueOnce(publication).mockRejectedValue(Error('controller_balance_required'));
 render(<HostedAwardReview id="setup" slot={4} hr={false}/>);
 await screen.findByRole('checkbox');fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Approve and open claims'}));
 expect(await screen.findByRole('alert')).toHaveTextContent('reviewer wallet needs test MON');
 await act(async()=>{});expect(mocks.publish).toHaveBeenCalledTimes(2);expect(mocks.review).toHaveBeenCalledTimes(2);
 expect(screen.queryByText('Claims are open.')).not.toBeInTheDocument();
 expect(screen.getByRole('button',{name:'Resume approved publication'})).toBeEnabled();
 await waitFor(()=>expect(screen.getByText(/Allocation approved/)).toBeVisible());
});
