import {useEffect,useState} from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import {ArrowLeft,BadgeCheck,Clock3} from 'lucide-react';
import {formatUnits} from 'viem';
import {readHostedReviewWorkspace,hostedRecipientTotals,type HostedReviewWorkspaceData,type HostedReviewGroup} from '../data/hostedReviewWorkspace';
import {officialFinishTime} from '../model/officialFinishTime';
import {setupAmount} from '../model/setupAmount';
import HostedAwardReview from './HostedAwardReview';
import p from '../components/Podium.module.css';
import s from './HostedReviewWorkspace.module.css';
type Campaign={id:string;name:string;revision:number};
const reviewFundingLabel=(state:string,hr:boolean)=>({funded:hr?'Financirano':'Funded',awaiting_contract:hr?'Čeka ugovor':'Awaiting contract',awaiting_funding:hr?'Čeka uplatu':'Awaiting funding',cancelled:hr?'Otkazano':'Cancelled',unverified:hr?'Uplata nije potvrđena':'Funding not verified'}[state]??(hr?'Provjera uplate':'Check funding'));
function Money({value,hr}:{value:string|bigint;hr:boolean}){return <span title={`${formatUnits(BigInt(value),18)} test MON`}>{setupAmount(BigInt(value),hr)} <small>test MON</small></span>;}
function AwardTable({group,hr}:{group:HostedReviewGroup;hr:boolean}){
 const [page,setPage]=useState(0),t=(en:string,local:string)=>hr?local:en;
 const results=group.results,rows=results??group.awards.map(a=>({key:a.beneficiaryId,beneficiaryId:a.beneficiaryId,name:a.name,club:null,rankOverall:null,rankCategory:a.place,finishTimeMs:null,status:'standing',points:null}));
 const pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages-1),race=Boolean(results&&group.slot),league=Boolean(results&&!group.slot);
 return <section className={s.categoryTable}><h3>{group.classification?.categoryName??group.name}</h3>
  {group.hold?<p className={s.notice}>{t('Awards are held pending a review of the official results.','Nagrade čekaju pregled službenih rezultata.')}</p>:null}
  {rows.length?<><p className={s.tableNote}>{race?t('Official overall rank and category rank use the copied results. Times retain every recorded millisecond.','Službeni ukupni i kategorijski poredak koriste kopirane rezultate. Vremena čuvaju svaku zabilježenu milisekundu.'):league?t('League category standings use the saved scoring policy. No single finish time applies.','Poredak kategorija lige koristi spremljena pravila bodovanja. Nema jedinstvenog vremena utrke.'):t('Award ordering and sporting basis.','Poredak nagrada i sportska osnova.')}</p>
  <p className={s.scrollHint}>{t('Scroll sideways to compare times and rewards.','Pomaknite tablicu vodoravno za usporedbu vremena i nagrada.')}</p><div className={s.tableScroll} tabIndex={0} role="region" aria-label={`${group.name} ${t('results','rezultati')}`}><table><caption className={s.srOnly}>{group.name}</caption><thead><tr>
   {race?<th scope="col">{t('Overall rank','Ukupni poredak')}</th>:null}<th scope="col">{results?t('Category rank','Poredak kategorije'):t('Award place','Mjesto nagrade')}</th><th scope="col">{group.beneficiaryKind==='club'?t('Club','Klub'):t('Athlete','Sportaš')}</th>
   <th scope="col">{t('Category','Kategorija')}</th>{race?<><th scope="col">{t('Club','Klub')}</th><th scope="col">{t('Exact finish time','Točno vrijeme')}</th></>:<th scope="col">{group.type==='athlete_finishes'?t('Finishes','Završene utrke'):group.type.endsWith('metres')?t('Metres','Metri'):t('Points','Bodovi')}</th>}<th scope="col">{t('Award','Nagrada')}</th>
  </tr></thead><tbody>{rows.slice(current*10,current*10+10).map(r=>{const award=group.awards.find(a=>a.beneficiaryId===r.beneficiaryId);return <tr key={r.key}>
   {race?<td className={s.numeric}>{r.rankOverall??'—'}</td>:null}<td className={s.numeric}>{r.rankCategory??'—'}</td><th scope="row">{r.name}</th><td>{group.classification?.categoryName??group.name}</td>
   {race?<><td>{r.club??'—'}</td><td className={s.exactTime}>{officialFinishTime(r.finishTimeMs,r.status)}</td></>:<td className={s.numeric}>{r.points??award?.value??'—'}</td>}
   <td>{award?<Money value={award.amountWei} hr={hr}/>:group.hold?t('Held','Zadržano'):<Money value="0" hr={hr}/>}</td>
  </tr>;})}</tbody></table></div>{pages>1?<nav className={s.pagination} aria-label={`${group.name} ${t('pages','stranice')}`}><button disabled={!current} onClick={()=>setPage(current-1)}>{t('Previous','Prethodno')}</button><span>{current+1} / {pages} · {rows.length} {t('results','rezultata')}</span><button disabled={current===pages-1} onClick={()=>setPage(current+1)}>{t('Next','Sljedeće')}</button></nav>:null}</>:<p className={s.notice}>{t('No results are available in this category.','Nema dostupnih rezultata u ovoj kategoriji.')}</p>}
 </section>;
}
function Standings({groups,hr}:{groups:HostedReviewGroup[];hr:boolean}){
 const tracks=new Map<string,{name:string;groups:HostedReviewGroup[]}>();
 for(const group of groups){const id=group.classification?.trackId??group.nodeId,track=tracks.get(id)??{name:group.classification?.trackName??group.name,groups:[]};track.groups.push(group);tracks.set(id,track);}
 return <div className={s.groups}>{[...tracks].map(([id,track])=><details className={s.category} key={id} open><summary>{track.name}<span><Money value={track.groups.reduce((sum,g)=>sum+BigInt(g.budgetWei),0n)} hr={hr}/></span></summary>{track.groups.map(group=><AwardTable key={group.nodeId} group={group} hr={hr}/>)}</details>)}</div>;
}
function ReviewContent({data,requestedSlot,hr,campaign}:{data:HostedReviewWorkspaceData;requestedSlot:number|null;hr:boolean;campaign:Campaign}){
 const [selected,setSelected]=useState(()=>data.pools.some(p=>p.slot===requestedSlot)?requestedSlot!:data.pools[0]!.slot),[tab,setTab]=useState('standings'),[query,setQuery]=useState(''),[page,setPage]=useState(0);
 const t=(en:string,local:string)=>hr?local:en,pool=data.pools.find(p=>p.slot===selected)!,groups=data.groups.filter(g=>g.slot===selected),totals=hostedRecipientTotals(groups);
 const filtered=totals.filter(r=>r.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages-1);
 const proposed=groups.reduce((sum,g)=>sum+BigInt(g.proposedWei),0n),retained=BigInt(pool.budgetWei)-proposed,held=groups.filter(g=>BigInt(g.budgetWei)>BigInt(g.proposedWei)),funding=data.funding,observed=funding.pools.find(p=>p.slot===selected);
 return <>
  <header className={p.heading}><div><span className={p.eyebrow}>{t('Review','Pregled')}</span><h1>{campaign.name}</h1><p>{data.pools.length===1?pool.name:t('Select a sponsored prize pool','Odaberite sponzorirani nagradni fond')}</p></div><span className={p.badge} data-state={funding.state}>{reviewFundingLabel(funding.state,hr)}</span></header>
  {requestedSlot!==null&&!data.pools.some(p=>p.slot===requestedSlot)?<p className={s.notice} role="status">{t('The requested prize pool is not sponsored by this campaign. Showing its sponsored pool.','Traženi fond nije sponzoriran ovom kampanjom. Prikazan je sponzorirani fond.')}</p>:null}
  {data.pools.length>1?<label className={s.pool}>{t('Sponsored event','Sponzorirani događaj')}<select value={selected} onChange={e=>{setSelected(Number(e.target.value));setQuery('');setPage(0);}}>{data.pools.map(p=><option key={p.slot} value={p.slot}>{p.name}</option>)}</select></label>:null}
  <div className={s.layout}><div className={s.evidence}>
   <div className={s.source}><BadgeCheck size={20}/><span><strong>{t('Official results','Službeni rezultati')}</strong> {t('published by RacesOn','objavljuje RacesOn')}<small>{t('Demo names are aliases; ranks and times retain the copied sporting evidence.','Demo imena su pseudonimi; poredak i vremena čuvaju kopirane sportske podatke.')}</small></span></div>
   <Tabs.Root value={tab} onValueChange={setTab}><Tabs.List className={s.tabs} aria-label={t('Review views','Prikazi pregleda')}><Tabs.Trigger value="standings">{t('Standings & awards','Poredak i nagrade')}</Tabs.Trigger><Tabs.Trigger value="totals">{t('Recipient totals','Ukupno po primatelju')}</Tabs.Trigger><Tabs.Trigger value="held">{t('Reserved','Zadržano')} ({held.length})</Tabs.Trigger><Tabs.Trigger value="funding">{t('Funding','Financiranje')}</Tabs.Trigger></Tabs.List>
    <Tabs.Content value="standings"><Standings groups={groups} hr={hr}/></Tabs.Content>
    <Tabs.Content value="totals"><section className={s.card}><div className={s.cardHeading}><h2>{t('Recipient totals','Ukupno po primatelju')}</h2><strong><Money value={proposed} hr={hr}/></strong></div><label className={s.search}>{t('Find a recipient','Pronađi primatelja')}<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder={t('Athlete or club name','Ime sportaša ili kluba')}/></label><div className={s.tableScroll}><table><thead><tr><th>{t('Recipient','Primatelj')}</th><th>{t('Categories','Kategorije')}</th><th>{t('Total','Ukupno')}</th></tr></thead><tbody>{filtered.slice(current*12,current*12+12).map(r=><tr key={r.id}><th scope="row">{r.name}<small>{r.kind==='club'?t('Club','Klub'):t('Athlete','Sportaš')}</small></th><td>{r.categories}</td><td><Money value={r.amountWei} hr={hr}/></td></tr>)}</tbody></table></div>{!filtered.length?<p role="status">{t('No matching recipients.','Nema odgovarajućih primatelja.')}</p>:null}<nav className={s.pagination} aria-label={t('Recipient pages','Stranice primatelja')}><button disabled={!current} onClick={()=>setPage(n=>n-1)}>{t('Previous','Prethodno')}</button><span>{current+1} / {pages} · {filtered.length}</span><button disabled={current===pages-1} onClick={()=>setPage(n=>n+1)}>{t('Next','Sljedeće')}</button></nav></section></Tabs.Content>
    <Tabs.Content value="held"><section className={s.card}><h2>{t('Reserved funds','Zadržana sredstva')}</h2><p className={s.large}><Money value={retained} hr={hr}/></p>{retained===0n?<p>{t('The full prize pool is allocated to recipients.','Cijeli fond raspoređen je primateljima.')}</p>:<><p>{t('These funds remain under the campaign’s saved return terms.','Ova sredstva ostaju pod spremljenim uvjetima povrata kampanje.')}</p>{groups.filter(g=>BigInt(g.budgetWei)>BigInt(g.proposedWei)).map(g=><div className={s.balanceRow} key={g.nodeId}><span>{g.name}<small>{g.hold?t('Results need review','Rezultati zahtijevaju pregled'):t('Unused or unallocated prizes','Neiskorištene ili neraspoređene nagrade')}</small></span><Money value={BigInt(g.budgetWei)-BigInt(g.proposedWei)} hr={hr}/></div>)}</>}</section></Tabs.Content>
    <Tabs.Content value="funding"><section className={s.card}><div className={s.cardHeading}><h2>{t('Prize funding','Financiranje nagrada')}</h2><span className={p.badge}>{reviewFundingLabel(funding.state,hr)}</span></div><dl className={s.balances}><div><dt>{pool.name}</dt><dd><Money value={pool.budgetWei} hr={hr}/></dd></div>{observed?[['Remaining',t('Remaining','Preostalo'),observed.remainingWei],['Paid',t('Paid to recipients','Isplaćeno primateljima'),observed.paidWei],['Returned',t('Returned','Vraćeno'),observed.returnedWei]].map(([key,label,value])=><div key={key}><dt>{label}</dt><dd><Money value={value!} hr={hr}/></dd></div>):null}</dl>{funding.state==='unverified'?<p role="status">{t('Funding could not be verified. Reload to check again.','Uplata nije potvrđena. Ponovno učitajte za provjeru.')}</p>:null}{funding.programmeAddress?<a className={s.explorer} href={`https://testnet.monadexplorer.com/address/${funding.programmeAddress}`} target="_blank" rel="noreferrer">{t('View reward contract ↗','Pogledaj ugovor nagrada ↗')}</a>:null}{funding.blockNumber?<p className={s.muted}>{t('Verified at block','Provjereno u bloku')} {funding.blockNumber}</p>:null}</section></Tabs.Content>
   </Tabs.Root>
  </div><aside className={s.workflow}><h2><Clock3 size={20}/>{t('Workflow','Tijek rada')}</h2><HostedAwardReview key={`${campaign.id}:${selected}`} id={campaign.id} slot={selected} hr={hr} expected={{budgetWei:pool.budgetWei,proposedWei:proposed.toString()}}/></aside></div>
 </>;
}
export default function HostedReviewWorkspace({campaign,requestedSlot,hr,onBack}:{campaign:Campaign;requestedSlot:number|null;hr:boolean;onBack:()=>void}){
 const [data,setData]=useState<HostedReviewWorkspaceData|null>(null),[error,setError]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError(false);void readHostedReviewWorkspace(campaign.id,campaign.revision).then(v=>{if(active)setData(v);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[campaign.id,campaign.revision,reload]);
 return <><div className={s.topbar}><button onClick={onBack}><ArrowLeft size={16}/>{hr?'Red za pregled':'Review queue'}</button><button onClick={()=>setReload(n=>n+1)}>{hr?'Osvježi pregled':'Refresh review'}</button></div>{error?<section className={p.empty}><p role="alert">{hr?'Pregled nije dostupan. Ponovno učitajte važeće rezultate i uplatu.':'The review could not be verified. Refresh to load the current results and funding.'}</p></section>:data?<ReviewContent key={`${campaign.id}:${reload}`} campaign={campaign} data={data} requestedSlot={requestedSlot} hr={hr}/>:<p role="status">{hr?'Učitavanje rezultata i uplate…':'Loading results and funding…'}</p>}</>;
}
