import {lazy,Suspense,useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import * as Dialog from "@radix-ui/react-dialog";
import {Link,useSearchParams,useNavigate} from "react-router-dom";
import {Plus,LockKeyhole,Unlock,Trash2,Copy,Undo2,Save,FolderOpen,Download} from "lucide-react";
import {useAuth} from "@/lib/auth";
import {ApiError} from "@/lib/api";
import {useI18n} from "@/shared/i18n/I18nContext";
import {useRewardSessionEpoch} from "../model/useRewardSessionEpoch";
import {createRewardSetup,defaultRewardSetupPolicy,decodeRewardSetup,finishRewardSetup,setupReadiness,previewRewardSetup,setupNodes,setupPath,updateSetupNode,balanceSetupChildren,presetSetupShares,setupId,SETUP_LIMITS,type RewardDistributionSetup,type RewardSetupContext,type RewardSetupNode,type SavedRewardSetup,type SetupPreviewRow} from "@raceson/domain/rewards/distribution-setup";
import {readRewardSetup,saveRewardSetup,listRewardSetups} from "../data/distributionSetups";
import {rewardSetupCopy} from "../model/rewardSetupCopy";
import {setupAmount} from "../model/setupAmount";
import {type SetupEventSelection} from "../components/RewardSetupEvent";
import RewardSetupEventSource from "../components/RewardSetupEventSource";
import RewardSetupChart from "../components/RewardSetupChart";

import {sponsorIntent,demoSponsorRounds,sponsorDemoEditions} from "../model/sponsorOpportunities";
import GuidedRewardSetup from "../components/GuidedRewardSetup";
import {sponsorConfigurationSourcesReady} from "@raceson/domain/rewards/sponsor-launch";
import {sponsorSetupComplete} from "../model/sponsorSetupComplete";
import {createGuidedSetup} from "@raceson/domain/rewards/guided-setup-editor";
import RewardSetupJourney from "../components/RewardSetupJourney";
import RewardSetupDirectSource from "../components/RewardSetupDirectSource";
import RewardSetupEventResults from "../components/RewardSetupEventResults";
import type {RewardSetupEventContext,RewardEventChoice} from "@raceson/domain/rewards/setup-event";
import RewardSetupPolicy from "../components/RewardSetupPolicy";
import s from "../components/RewardSetup.module.css";
const RewardSetupSource=lazy(()=>import("../components/RewardSetupSource"));
const RewardSetupConversion=lazy(()=>import("../components/RewardSetupConversion"));
const GUEST_DRAFT_KEY="raceson.reward-setup.sign-in-draft.v1";
const legacySetup=(hr:boolean):RewardDistributionSetup=>({...createRewardSetup(crypto.randomUUID(),hr),version:4,programmeKind:"event",event:null,context:null,stage:"draft",policy:defaultRewardSetupPolicy()});
const freshSetup=(hr:boolean):RewardDistributionSetup=>createGuidedSetup(()=>crypto.randomUUID(),hr);
function readGuestSetup(storageKey:string){try{const raw=sessionStorage.getItem(storageKey);return raw?decodeRewardSetup(JSON.parse(raw)):null;}catch{return null;}}
function initialSetup(hr:boolean,restoreGuest:boolean,legacy=false,storageKey=GUEST_DRAFT_KEY){
 if(restoreGuest){const restored=readGuestSetup(storageKey);if(restored)return restored;}
 return legacy?legacySetup(hr):freshSetup(hr);
}
const newNode=(name:string,shareBps=0):RewardSetupNode=>({id:crypto.randomUUID(),name,shareBps,locked:false,children:[],rule:null});
const copyNode=(node:RewardSetupNode):RewardSetupNode=>({...node,id:crypto.randomUUID(),children:node.children.map(copyNode)});

function Percentage({label,value,disabled,onChange}:{label:string;value:number;disabled?:boolean;onChange:(v:number)=>void}){
 return <div className={s.row}><input aria-label={`${label} slider`} type="range" min="0" max="10000" step="25" value={value} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/><input aria-label={label} type="number" min="0" max="100" step="0.01" value={value/100} disabled={disabled} onChange={e=>{if(e.target.value!==""&&e.target.validity.valid)onChange(Math.round(Number(e.target.value)*100));}}/><span>%</span></div>;
}
function Inspector({building=false,node,parent,row,hr,disabled,onNode,onSelect,onRemove,onDuplicate,depth,context,directEvent,onDirectConnect,eventSelection,reviewMode,selectedRank,openRequest}:{building?:boolean;selectedRank:number|null;openRequest:number;directEvent:RewardSetupEventContext|null;onDirectConnect:(choice:RewardEventChoice,basis:"race_position"|"club_points")=>void;context:RewardSetupContext|null;eventSelection:SetupEventSelection|null;reviewMode:boolean;node:RewardSetupNode;parent:RewardSetupNode|null;row:SetupPreviewRow|undefined;hr:boolean;disabled:boolean;onNode:(update:(n:RewardSetupNode)=>RewardSetupNode)=>void;onSelect:(id:string)=>void;onRemove:()=>void;onDuplicate:()=>void;depth:number}){
 const c=rewardSetupCopy(hr),[addCount,setAddCount]=useState("2"),[rewardCount,setRewardCount]=useState(String(node.rule?.sharesBps.length??10)),[tab,setTab]=useState(reviewMode?"source":"settings"),[error,setError]=useState("");
 const [editRequest,setEditRequest]=useState(0);
 const heading=useRef<HTMLHeadingElement>(null),rewardInputs=useRef(new Map<number,HTMLInputElement>());
 useEffect(()=>{if(!openRequest)return;heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView?.({block:"start"});},[openRequest]);
 useEffect(()=>{if(!editRequest||selectedRank===null)return;const input=rewardInputs.current.get(selectedRank);input?.focus({preventScroll:true});input?.scrollIntoView?.({block:"nearest"});},[editRequest,selectedRank]);
 function safely(action:()=>void){try{action();setError("");}catch{setError(c.limit);}}
 function add(){safely(()=>{const count=Number(addCount);if(!Number.isInteger(count)||count<1||count+node.children.length>SETUP_LIMITS.children||depth>=SETUP_LIMITS.depth)throw new Error();
   onNode(n=>{const children=[...n.children,...Array.from({length:count},(_,i)=>newNode(`${c.branch} ${n.children.length+i+1}`))];return {...n,rule:null,children:n.children.length?children:balanceSetupChildren(children,"equal")};});onSelect(node.id);
 });}
 function setRewards(){safely(()=>onNode(n=>({...n,rule:{basis:n.rule?.basis??"race_position",source:n.rule?.source??null,sharesBps:presetSetupShares(Number(rewardCount))}})));}
 return <section id="reward-setup-inspector" className={s.card} aria-label={c.selected}><header className={s.cardHeader}><div><p className={s.eyebrow}>{c.selected}</p><h2 ref={heading} tabIndex={-1} className={s.selectedHeading}>{node.name||c.branch}{selectedRank!==null?` · ${c.rank} ${selectedRank}`:""}</h2></div>{openRequest>0?<button className={s.button} onClick={()=>{const chart=document.getElementById("reward-setup-chart");chart?.focus({preventScroll:true});chart?.scrollIntoView?.({block:"start"});}}>{hr?"Natrag na grafikon":"Back to chart"}</button>:null}</header>
 <div className={s.inspector}><fieldset disabled={disabled}>
  {selectedRank!==null&&node.rule?<div className={s.selectedPlace} role="region" aria-label={`${c.rank} ${selectedRank} ${hr?"detalji":"details"}`}><span className={s.eyebrow}>{c.rank} {selectedRank} · {node.name}</span><strong>{setupAmount(row?.slots[selectedRank-1]??null,hr)} test MON</strong><p>{node.rule.sharesBps[selectedRank-1]/100}% {c.parent}</p><button className={s.button} onClick={()=>{setTab("settings");setEditRequest(n=>n+1);}}>{hr?"Uredi udio ovog mjesta":"Edit this place’s share"}</button></div>:null}
  <label className={s.field}>{c.branchName}<input maxLength={100} value={node.name} onChange={e=>onNode(n=>({...n,name:e.target.value}))}/></label>
  <div className={s.hero}><span className={s.eyebrow}>{hr?"Planirana vrijednost":"Planned allocation"}</span><strong title={row?.amountWei!==null&&row?.amountWei!==undefined?`${row.amountWei} wei`:undefined}>{setupAmount(row?.amountWei??null,hr)} <span style={{fontSize:13,fontWeight:500}}>test MON</span></strong><small>{node.shareBps/100}% {c.parent} · {new Intl.NumberFormat(hr?"hr":"en",{maximumFractionDigits:4}).format((row?.pathShare??1)*100)}% {c.total}</small></div>
  {parent?<><div className={s.row}><span>{c.share}</span><button className={s.icon} aria-label={node.locked?c.unlock:c.lock} aria-pressed={node.locked} onClick={()=>onNode(n=>({...n,locked:!n.locked}))}>{node.locked?<LockKeyhole size={14}/>:<Unlock size={14}/>}</button></div><Percentage label={c.share} value={node.shareBps} disabled={node.locked} onChange={shareBps=>onNode(n=>({...n,shareBps}))}/></>:null}
  {parent?<div className={s.tabs} role="tablist" aria-label={hr?"Vrsta grane":"Branch type"}><button role="tab" aria-selected={!node.rule} onClick={()=>onNode(n=>({...n,rule:null}))}>{c.group}</button><button role="tab" aria-selected={Boolean(node.rule)} disabled={node.children.length>0} onClick={()=>onNode(n=>({...n,rule:n.rule??{basis:"race_position",sharesBps:presetSetupShares(10),source:null}}))}>{c.winners}</button></div>:null}
  {node.rule?<>{!building?<div className={s.tabs} role="tablist" aria-label={c.setup}><button role="tab" aria-selected={tab==="settings"} onClick={()=>setTab("settings")}>{c.setup}</button><button role="tab" aria-selected={tab==="source"} onClick={()=>setTab("source")}>{c.source}</button></div>:null}
   {(tab==="settings"||building)?<><div className={s.row}><label className={s.field}>{c.rewardCount}<input type="number" min="1" max={SETUP_LIMITS.winners} value={rewardCount} onChange={e=>setRewardCount(e.target.value)}/></label><button className={s.button} onClick={setRewards}>{c.applyCount}</button></div><div className={s.actions}><button className={s.button} onClick={()=>onNode(n=>({...n,rule:{...n.rule!,sharesBps:presetSetupShares(n.rule!.sharesBps.length)}}))}>{c.equal}</button><button className={s.button} onClick={()=>onNode(n=>({...n,rule:{...n.rule!,sharesBps:presetSetupShares(n.rule!.sharesBps.length,"descending")}}))}>{c.descending}</button></div>
   <div className={`${s.tableWrap} ${s.section}`}><table className={s.table} aria-label={c.rewards}><thead><tr><th>{c.rank}</th><th>{c.percent}</th><th>{c.amount}</th></tr></thead><tbody>{node.rule.sharesBps.map((share,i)=><tr key={i} data-selected-place={selectedRank===i+1}><td>{i+1}</td><td><input ref={element=>{if(element)rewardInputs.current.set(i+1,element);else rewardInputs.current.delete(i+1);}} aria-label={`${c.rank} ${i+1} %`} type="number" min="0" max="100" step="0.01" value={share/100} onChange={e=>{if(e.target.value!==""&&e.target.validity.valid)onNode(n=>({...n,rule:{...n.rule!,sharesBps:n.rule!.sharesBps.map((v,j)=>i===j?Math.round(Number(e.target.value)*100):v)}}));}}/> %</td><td title={row?.slots[i]!==undefined?`${row.slots[i]} wei`:undefined}>{setupAmount(row?.slots[i]??null,hr)}</td></tr>)}</tbody></table></div></>:null}{(tab==="source"||building)?<><label className={s.field}>{c.resultBasis}<select disabled={Boolean(directEvent)} value={node.rule.basis} onChange={e=>onNode(n=>({...n,rule:{...n.rule!,basis:e.target.value as NonNullable<RewardSetupNode["rule"]>["basis"],source:null}}))}>{Object.entries(c.basis).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{!["race_position","club_points","league_position"].includes(node.rule.basis)?<p className={s.notice}>{c.sourceReview}</p>:null}<div className={s.section}><Suspense fallback={<p>{c.loading}</p>}>{directEvent?<RewardSetupDirectSource key={`${directEvent.editionId}:${directEvent.catalogueHash}`} event={directEvent} node={node} slots={row?.slots??[]} hr={hr} disabled={disabled} onConnect={onDirectConnect}/>:context?<RewardSetupEventSource key={`${node.id}:${node.rule.basis}:${context.draftId}:${context.roundId}:${context.catalogueHash}`} context={context} selection={eventSelection} node={node} slots={row?.slots??[]} hr={hr} disabled={disabled} onChange={source=>onNode(n=>({...n,rule:{...n.rule!,source}}))}/>:<RewardSetupSource key={`${node.id}:${node.rule.basis}`} node={node} slots={row?.slots??[]} hr={hr} disabled={disabled} onChange={source=>onNode(n=>({...n,rule:{...n.rule!,source}}))}/>}</Suspense></div></>:null}
  </>:<><section className={s.section}><div className={s.row}><h3>{c.branches} <span className={s.badge}>{node.children.length}</span></h3><span className={s.small}>{row?.totalShareBps===undefined?0:row.totalShareBps/100}%</span></div>
   {node.children.length?<div className={s.actions}><button className={s.button} onClick={()=>safely(()=>onNode(n=>({...n,children:balanceSetupChildren(n.children,"equal")})))}>{c.equal}</button><button className={s.button} onClick={()=>safely(()=>onNode(n=>({...n,children:balanceSetupChildren(n.children,"proportional")})))}>{c.balance}</button></div>:null}
   {node.children.map((child,i)=><div key={child.id} className={s.branchRow}><div className={s.row}><button className={s.branchName} onClick={()=>onSelect(child.id)}><span className={s.dot}/> {child.name} ↗</button><div className={s.actions}><button className={s.icon} aria-label={`${child.locked?c.unlock:c.lock}: ${child.name}`} onClick={()=>onNode(n=>({...n,children:n.children.map(v=>v.id===child.id?{...v,locked:!v.locked}:v)}))}>{child.locked?<LockKeyhole size={12}/>:<Unlock size={12}/>}</button><button className={s.icon} aria-label={`${c.up}: ${child.name}`} disabled={i===0} onClick={()=>onNode(n=>{const children=[...n.children];[children[i-1],children[i]]=[children[i],children[i-1]];return {...n,children};})}>↑</button></div></div><Percentage label={`${child.name} %`} value={child.shareBps} disabled={child.locked} onChange={shareBps=>onNode(n=>({...n,children:n.children.map(v=>v.id===child.id?{...v,shareBps}:v)}))}/><div className={s.bar}><span style={{width:`${child.shareBps/100}%`}}/></div></div>)}
   <div className={`${s.row} ${s.section}`}><label className={s.field}>{c.count}<input type="number" min="1" max={SETUP_LIMITS.children-node.children.length} value={addCount} onChange={e=>setAddCount(e.target.value)}/></label><button className={s.primary} disabled={depth>=SETUP_LIMITS.depth||node.children.length>=SETUP_LIMITS.children} onClick={add}><Plus size={16}/>{c.add}</button></div>
  </section></>}
  {row?.issue?<p role="status" className={s.notice}>{row.issue==="overallocated"?c.invalid:row.issue==="empty"?c.empty:`${c.remaining}: ${(10000-row.totalShareBps)/100}% · ${setupAmount(row.retainedWei,hr)} test MON`}</p>:<p className={`${s.success} ${s.section}`}>{c.complete}</p>}
  {error?<p role="alert" className={s.notice}>{error}</p>:null}
  {parent?<div className={`${s.actions} ${s.section}`}><button className={s.button} onClick={onDuplicate}><Copy size={14}/>{c.duplicate}</button><button className={`${s.button} ${s.danger}`} onClick={onRemove}><Trash2 size={14}/>{c.remove}</button></div>:null}
 </fieldset></div></section>;
}

function SetupEditor({id,signedIn,campaign=false}:{id:string|null;signedIn:boolean;campaign?:boolean}){
 const {locale}=useI18n(),hr=locale==="hr",c=rewardSetupCopy(hr),[search,setSearch]=useSearchParams(),navigate=useNavigate();
 const sourceScope=[search.get("sourceLeagueId"),search.get("sourceSeasonId"),search.get("eventEditionId"),search.get("raceId")].filter(Boolean).join(":");
 const guestKey=campaign?`${GUEST_DRAFT_KEY}.sponsor.${sponsorIntent(search.get("opportunity"))?.id??"league"}${sourceScope?`.${sourceScope}`:""}`:GUEST_DRAFT_KEY;
 const [configuration,setConfiguration]=useState(()=>{const restored=!id?readGuestSetup(guestKey):null,initial=restored??initialSetup(hr,false,search.get("legacy")==="1");if(campaign&&!id&&!restored){initial.budgetMon="";initial.policy={...defaultRewardSetupPolicy(),fewerFinishers:"selected_return"};initial.root={...initial.root,children:initial.root.children.map((pot,i)=>({...pot,name:i?demoSponsorRounds[i-1]:pot.name}))};const intent=sponsorIntent(search.get("opportunity"),hr);const raceSlot=intent?.round||sponsorDemoEditions.indexOf(search.get("eventEditionId") as typeof sponsorDemoEditions[number])+1;if(raceSlot)initial.root.children=initial.root.children.map((pot,i)=>({...pot,shareBps:i===raceSlot?10000:0}));initial.name=hr?"Moja sponzorska kampanja":"My sponsor campaign";}return search.get("programme")&&initial.version!==5?{...initial,version:4 as const,programmeKind:"league" as const,event:null}:initial;}),[saved,setSaved]=useState<SavedRewardSetup|null>(null),[loading,setLoading]=useState(Boolean(id&&signedIn)),[loadError,setLoadError]=useState(false),[reload,setReload]=useState(0);
 const [step,setStep]=useState(()=>{const requested=Number(search.get("step"));return requested>=1&&requested<=6?requested:search.get("view")==="results"?6:id?5:1;});
 function goToSetupStep(next:number,round?:number){setStep(next);setSearch(previous=>{const nextSearch=new URLSearchParams(previous);nextSearch.set("step",String(next));if(next===4)nextSearch.delete("round");else if(round!==undefined)nextSearch.set("round",String(round));nextSearch.delete("view");return nextSearch;},{replace:true});}
 useEffect(()=>{document.getElementById("setup-workflow")?.scrollIntoView?.({block:"start"});},[step]);
 const [selected,setSelected]=useState(configuration.root.id),[history,setHistory]=useState<RewardDistributionSetup[]>([]),[notice,setNotice]=useState<ReactNode>(null);
 useEffect(()=>{if(!signedIn&&!id){try{sessionStorage.setItem(guestKey,JSON.stringify(configuration));}catch{/* Saving remains an explicit account action when browser storage is unavailable. */}}},[configuration,signedIn,id,guestKey]);
 const [pointSelection,setPointSelection]=useState<{id:string;rank:number|null;request:number}|null>(null);
 const [eventSelection,setEventSelection]=useState<SetupEventSelection|null>(null),[reviewing,setReviewing]=useState<string|null>(null);
 const [busy,setBusy]=useState(false),[outcome,setOutcome]=useState<"unknown"|"conflict"|"failed"|null>(null),[showLibrary,setShowLibrary]=useState(false),[library,setLibrary]=useState<SavedRewardSetup[]|null>(null),[libraryError,setLibraryError]=useState(false);
 const [converting,setConverting]=useState(false),[copyBusy,setCopyBusy]=useState(false),[copyOutcome,setCopyOutcome]=useState<"unknown"|"failed"|null>(null);
 const conversionRequest=useRef<{id:string;requestId:string;expectedRevision:number;configuration:RewardDistributionSetup}|null>(null);
 const [newId]=useState(()=>crypto.randomUUID()),request=useRef<{requestId:string;expectedRevision:number;configuration:RewardDistributionSetup}|null>(null),active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 useEffect(()=>{if(signedIn&&!id){try{sessionStorage.removeItem(guestKey);}catch{/* Storage may be unavailable in private browsing. */}}},[signedIn,id,guestKey]);
 useEffect(()=>{if(!id||!signedIn)return;let current=true;setLoading(true);setLoadError(false);void readRewardSetup(id).then(record=>{if(current){setSaved(record);setConfiguration(record.configuration);setSelected(record.configuration.root.id);setHistory([]);request.current=null;setOutcome(null);}}).catch(()=>{if(current)setLoadError(true);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[id,reload,signedIn]);
 useEffect(()=>{if(!loading&&configuration.stage==="ready"&&search.get("view")==="results")document.getElementById(configuration.event?"setup-results":"setup-step-6")?.scrollIntoView?.({block:"start"});},[loading,configuration.stage,configuration.event,search]);
 const dirty=JSON.stringify(saved?.configuration)!==JSON.stringify(configuration);
 useEffect(()=>{if(!dirty&&!copyBusy&&copyOutcome!=="unknown")return;if(!signedIn&&!id){try{if(sessionStorage.getItem(guestKey)===JSON.stringify(configuration))return;}catch{/* Unsaved storage failures retain the leave warning. */}}const leave=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave);},[dirty,signedIn,id,configuration,copyBusy,copyOutcome,guestKey]);
 const preview=useMemo(()=>{try{return previewRewardSetup(configuration);}catch{return null;}},[configuration]);
 const path=setupPath(configuration.root,selected),node=path.at(-1)??configuration.root,parent=path.at(-2)??null,all=setupNodes(configuration.root),groups=all.filter(n=>n.rule),row=preview?.rows.find(r=>r.id===node.id);
 const selectedRank=pointSelection?.id===node.id&&pointSelection.rank!==null&&node.rule?.sharesBps[(pointSelection?.rank??0)-1]!==undefined?pointSelection!.rank:null;
 function openChartPoint(id:string,rank:number|null=null){setSelected(id);setReviewing(null);setPointSelection(old=>({id,rank,request:(old?.request??0)+1}));}
 const ready=configuration.stage==="ready",readiness=setupReadiness(configuration);
 const locked=busy||outcome==="unknown"||outcome==="conflict";
 function change(next:RewardDistributionSetup){if(locked)return;if(setupNodes(next.root).length>SETUP_LIMITS.nodes)throw new Error("limit");setHistory(h=>[...h.slice(-19),configuration]);setConfiguration({...next,version:next.version===5?5:next.version===4?4:3,context:next.context??null,stage:"draft",policy:next.policy??defaultRewardSetupPolicy()});setNotice(null);setOutcome(null);}
 function update(fn:(n:RewardSetupNode)=>RewardSetupNode){try{change({...configuration,root:updateSetupNode(configuration.root,node.id,fn)});}catch{setNotice(c.limit);}}
 async function save(finish=false,continueToLaunch=false){if(busy||!preview||!signedIn)return;const fixed=request.current??{requestId:crypto.randomUUID(),expectedRevision:saved?.revision??0,configuration:finish?finishRewardSetup(configuration):decodeRewardSetup(configuration)};request.current=fixed;setBusy(true);setOutcome(null);
  try{const record=await saveRewardSetup(id??newId,fixed);if(!active.current)return;setSaved(record);setConfiguration(record.configuration);request.current=null;if(continueToLaunch&&sponsorConfigurationSourcesReady(record.configuration)){navigate(`/rewards/campaigns/${record.id}`);return;}if(finish){setStep(record.configuration.version===5?5:6);setSearch({setup:record.id,view:"results"},{replace:true});}else if(!id)setSearch(previous=>{const next=new URLSearchParams(previous);next.set("setup",record.id);next.set("step",String(step));return next;},{replace:true});}
  catch(e){if(!active.current)return;if(e instanceof ApiError&&e.status===409){setOutcome(e.code==="reward_setup_limit"?"failed":"conflict");if(e.code==="reward_setup_limit")request.current=null;}else if(e instanceof ApiError&&[400,401,403,404].includes(e.status)){request.current=null;setOutcome("failed");}else setOutcome("unknown");}
  finally{if(active.current)setBusy(false);}
 }
 async function openLibrary(){setShowLibrary(true);setLibrary(null);setLibraryError(false);try{const records=await listRewardSetups();if(active.current)setLibrary(records);}catch{if(active.current)setLibraryError(true);}}
 async function createGuidedCopy(next:RewardDistributionSetup){
  if(copyBusy||!signedIn||!saved||dirty||locked)return;
  const fixed=conversionRequest.current??{id:crypto.randomUUID(),requestId:crypto.randomUUID(),expectedRevision:0,configuration:decodeRewardSetup(next)};
  conversionRequest.current=fixed;setCopyBusy(true);setCopyOutcome(null);
  try{const {id:copyId,...body}=fixed;const record=await saveRewardSetup(copyId,body);if(!active.current)return;conversionRequest.current=null;setSearch({setup:record.id,step:"1"},{replace:true});}
  catch(e){if(!active.current)return;if(e instanceof ApiError&&[400,401,403,404,409].includes(e.status)){conversionRequest.current=null;setCopyOutcome("failed");}else setCopyOutcome("unknown");}
  finally{if(active.current)setCopyBusy(false);}
 }
 function exportDraft(){try{const contents=JSON.stringify(decodeRewardSetup(configuration),null,2),url=URL.createObjectURL(new Blob([contents],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="reward-setup.json";a.click();URL.revokeObjectURL(url);}catch{setNotice(c.badFile);}}
 async function importDraft(file:File|undefined){if(!file||locked)return;try{if(file.size>262144)throw new Error();const next=decodeRewardSetup(JSON.parse(await file.text()));if(!active.current)return;if(dirty&&!window.confirm(c.replace))return;change(next);setSelected(next.root.id);}catch{if(active.current)setNotice(c.badFile);}}
 function switchDraft(nextId:string|null){if(dirty&&!window.confirm(c.leave))return;setShowLibrary(false);if(nextId)setSearch({setup:nextId});else {setSearch({});const next=freshSetup(hr);setSaved(null);setConfiguration(next);setSelected(next.root.id);setHistory([]);setStep(1);}}
 if(loading)return <div className={s.page} role="status">{c.loading}</div>;
 if(loadError)return <div className={s.page}><h1>{c.title}</h1><p role="alert">{c.failed}</p><button className={s.button} onClick={()=>setReload(n=>n+1)}>{c.retry}</button></div>;
 if(converting&&saved&&!dirty)return <Suspense fallback={<p role="status" className={s.page}>{c.loading}</p>}><RewardSetupConversion source={saved.configuration} revision={saved.revision} hr={hr} busy={copyBusy} uncertain={copyOutcome==="unknown"}
 error={copyOutcome==="unknown"?(hr?"Stvaranje nije potvrđeno. Ponovite isti zahtjev; izvornik nije izmijenjen.":"Creation is not confirmed. Retry the same request; the original has not been changed."):copyOutcome==="failed"?(hr?"Kopija nije stvorena. Izvornik nije izmijenjen.":"The copy could not be created. The original has not been changed."):null}
 onCancel={()=>{if(!copyBusy&&copyOutcome!=="unknown"){setConverting(false);setCopyOutcome(null);}}} onCreate={next=>void createGuidedCopy(next)}/></Suspense>;
 if(configuration.version===5)return <GuidedRewardSetup setupId={saved?.id} sourceLocked={Boolean(saved?.lifecycle&&saved.lifecycle.state!=="draft")} launchHref={campaign&&saved&&!dirty?`/rewards/campaigns/${saved.id}`:undefined} campaign={campaign} key={configuration.stage??"draft"} configuration={configuration} onChange={change} step={step} onStep={goToSetupStep} disabled={locked} hr={hr} selection={eventSelection} onLoaded={setEventSelection} initialProgramme={search.get("programme")} revision={saved?.revision??null} busy={busy} canSave={signedIn} isSaved={Boolean(saved&&!dirty)} onFinish={()=>{if(campaign){if(sponsorSetupComplete(configuration)){if(saved&&!dirty&&sponsorConfigurationSourcesReady(configuration))navigate(`/rewards/campaigns/${saved.id}`);else void save(false,true);}}else void save(true);}}
 saveStatus={saved&&!dirty?`${c.saved} · ${saved.revision}`:c.unsaved}
 error={outcome?<p className={s.notice} role="alert">{outcome==="unknown"?c.unknown:outcome==="conflict"?c.conflict:c.draftError}{outcome==="conflict"?<button className={s.button} onClick={()=>setReload(n=>n+1)}>{c.reload}</button>:null}</p>:null}
 saveAction={signedIn?<button className={s.primary} disabled={busy||outcome==="conflict"||!preview||!dirty} onClick={()=>void save(false,campaign&&step===5)}><Save size={16}/>{busy?c.saving:outcome==="unknown"?c.retry:c.save}</button>:<Link className={s.primary} onClick={e=>{try{sessionStorage.setItem(guestKey,JSON.stringify(decodeRewardSetup(configuration)));}catch{e.preventDefault();setNotice(c.badFile);}}} to={`/auth?next=${encodeURIComponent(campaign?`/rewards/create?${search.toString()}`:`/rewards/setup${id?`?setup=${id}`:""}`)}`}>{c.signin}</Link>}/>;
 return <article className={s.page}><header className={s.heading}><div><span className={s.eyebrow}>RacesOn · {ready?(hr?"Spremno za rezultate":"Ready for results"):c.draft}</span><h1>{c.title}</h1><p>{c.intro}</p></div><div className={s.actions}>
  <button className={s.button} onClick={()=>{if(signedIn)void openLibrary();else switchDraft(null);}} disabled={locked}><FolderOpen size={16}/>{signedIn?c.library:c.fresh}</button>
  <details className={s.tools}><summary>{hr?"Alati":"Tools"}</summary><button className={s.button} onClick={exportDraft} disabled={!preview}><Download size={17}/>{c.export}</button></details>
  {signedIn?<button className={s.primary} disabled={busy||outcome==="conflict"||!preview||!dirty} onClick={()=>void save()}><Save size={16}/>{busy?c.saving:outcome==="unknown"?c.retry:c.save}</button>:<Link className={s.primary} onClick={e=>{try{sessionStorage.setItem(guestKey,JSON.stringify(decodeRewardSetup(configuration)));}catch{e.preventDefault();setNotice(c.badFile);}}} to={`/auth?next=${encodeURIComponent(campaign?`/rewards/create?${search.toString()}`:`/rewards/setup${id?`?setup=${id}`:""}`)}`}>{c.signin}</Link>}
 </div></header>
 <Link className={s.small} to="/rewards/manage">← {hr?"Moji programi":"My programmes"}</Link>
 {configuration.programmeKind!=="event"&&!configuration.event&&(!configuration.context||configuration.context.roundId===null)?<section className={`${s.card} ${s.journeySection}`}><h2>{hr?"Nastavite uz jednostavnije postavljanje":"Continue with simpler setup"}</h2><p>{hr?"Stvorite vođenu kopiju uz usporedbu fondova i pravila. Izvorna raspodjela ostaje spremljena.":"Create a guided copy with a comparison of pots and rules. Your original distribution stays saved."}</p><button className={s.button} disabled={locked||!saved||dirty} onClick={()=>setConverting(true)}>{hr?"Pregledaj vođenu kopiju":"Review guided copy"}</button>{!saved||dirty?<p className={s.small}>{hr?"Najprije spremite ovaj nacrt kako bi izvornik ostao dostupan.":"Save this draft first so the original remains available."}</p>:null}</section>:null}
 {outcome?<p className={s.notice} role="alert">{outcome==="unknown"?c.unknown:outcome==="conflict"?c.conflict:c.draftError}{outcome==="conflict"?<button className={s.button} onClick={()=>setReload(n=>n+1)}>{c.reload}</button>:null}</p>:null}
 {notice?<p className={s.notice} role="status">{notice}</p>:null}
 {!preview?<p className={s.notice} role="alert">{hr?"Provjerite nazive i pozitivan iznos do 1.000.000 test MON (najviše 18 decimala).":"Check names and enter a positive amount up to 1,000,000 test MON (up to 18 decimals)."}</p>:null}
 <div className={`${s.row} ${s.status}`}><span className={saved&&!dirty?s.success:s.small}>{saved&&!dirty?`${c.saved} · ${saved.revision}`:c.unsaved}</span><div hidden={step!==4&&step!==5} className={s.actions}><label className={`${s.small} ${s.importLabel}`}>{c.import}<input type="file" accept="application/json,.json" disabled={locked} onChange={e=>{void importDraft(e.target.files?.[0]);e.target.value="";}}/></label><button className={s.button} disabled={!history.length||locked} onClick={()=>{const previous=history.at(-1)!;setConfiguration(previous);setHistory(h=>h.slice(0,-1));setSelected(previous.root.id);setNotice(null);}}><Undo2 size={14}/>{c.undo}</button></div></div>
 <ol id="setup-workflow" className={s.workflow} aria-label={hr?"Koraci postavljanja":"Setup progress"}>{[hr?"Novi program":"Create programme",hr?"Odaberi događaj":"Choose event",hr?"Pregled strukture":"Review structure",hr?"Odaberi nagrade":"Choose rewards",hr?"Raspodjela fonda":"Pot & distribution",hr?"Dovrši i pregledaj":"Finish & review"].map((label,i)=><li key={label} data-complete={i===0?Boolean(configuration.name):i===1?Boolean(configuration.context||configuration.event):i<4?groups.length>0&&!readiness.includes("sources"):i===4?preview?.complete:ready}><button aria-current={step===i+1?"step":undefined} onClick={()=>goToSetupStep(i+1)}><span>{i+1}</span>{label}</button></li>)}</ol>
 <div className={s.workspaceContext}><div><strong>{configuration.name}</strong><p>{configuration.event?`${configuration.event.name} · ${configuration.event.date}`:configuration.context?.eventName??(hr?"Izvor rezultata još nije povezan":"Results source not connected yet")}</p></div><span className={s.badge}>{hr?"Korak":"Step"} {step} / 6</span></div>
 <RewardSetupJourney step={step} onStep={goToSetupStep} configuration={configuration} disabled={locked} hr={hr} initialProgramme={search.get("programme")} onChange={change} onLoaded={setEventSelection} selection={eventSelection} onContext={context=>{const same=configuration.context?.draftId===context.draftId&&configuration.context?.roundId===context.roundId&&configuration.context?.catalogueHash===context.catalogueHash;
 if(!same&&groups.some(n=>n.rule!.source)&&!window.confirm(hr?"Promijeniti izvor rezultata?":"Change the results source?"))return;
 const clear=(n:RewardSetupNode):RewardSetupNode=>({...n,children:n.children.map(clear),rule:n.rule?{...n.rule,source:null}:null});
 change({...configuration,version:4,programmeKind:"league",event:null,context,stage:"draft",root:same?configuration.root:clear(configuration.root)});setStep(3);}
}/>
 <div hidden={step!==4&&step!==5}>
 <div id={step===4?"setup-step-4":"setup-step-5"} className={s.stepHeading}><div><span className={s.eyebrow}>{step} · {step===4?(hr?"Odaberi nagrade":"Choose what to reward"):(hr?"Fond i raspodjela":"Pot & distribution")}</span><h2>{step===4?(hr?"Izgradite nagrade na grafikonu":"Build your rewards on the chart"):(hr?"Uredite cijelu raspodjelu":"Edit the complete distribution")}</h2><p className={s.small}>{step===4?(hr?"Odaberite krug i dodajte podfondove znakom +. Svaka grana može imati vlastite kategorije i broj dobitnika.":"Select a circle and use + to add subpots. Give each branch its own categories and winner count."):(hr?"Isti grafikon, iste grane. Uredite ukupan fond, udjele i iznose dobitnika.":"The same chart and branches. Adjust the total pot, percentages and winner amounts.")}</p></div><button className={s.button} onClick={()=>goToSetupStep(step===4?5:6)}>{step===4?(hr?"Nastavi na raspodjelu":"Continue to distribution"):(hr?"Nastavi na završetak":"Continue to finish setup")}</button></div>
 <div className={s.toolbar}><div className={s.fields}><label className={`${s.field} ${s.budget}`}>{c.budget}<input inputMode="decimal" value={configuration.budgetMon} disabled={locked} onChange={e=>change({...configuration,budgetMon:e.target.value})}/></label></div><div className={s.summary}><span><strong>{configuration.root.children.length}</strong>{c.branches}</span><span><strong>{groups.length}</strong>{c.groups}</span><span><strong>{groups.reduce((sum,n)=>sum+n.rule!.sharesBps.length,0)}</strong>{c.slots}</span></div></div>
 <div className={s.layout} id="reward-setup-editor"><RewardSetupChart root={configuration.root} selected={node.id} selectedRank={selectedRank} rows={preview?.rows??[]} onSelect={openChartPoint} hr={hr} canAddChild={id=>{const target=setupPath(configuration.root,id).at(-1);return !locked&&Boolean(target&&!target.rule&&target.children.length<SETUP_LIMITS.children)&&setupPath(configuration.root,id).length-1<SETUP_LIMITS.depth&&all.length<SETUP_LIMITS.nodes;}} onAddChild={id=>{if(locked)return;const target=setupPath(configuration.root,id).at(-1);if(!target||target.rule||target.children.length>=SETUP_LIMITS.children||setupPath(configuration.root,id).length-1>=SETUP_LIMITS.depth||all.length>=SETUP_LIMITS.nodes)return;const child=newNode(`${c.branch} ${target.children.length+1}`,target.children.length?0:10000);change({...configuration,root:updateSetupNode(configuration.root,id,n=>({...n,children:[...n.children,child]}))});openChartPoint(child.id);}}/>
 <Inspector building={step===4} key={`inspector:${node.id}:${reviewing===node.id}:${selectedRank}`} selectedRank={selectedRank} openRequest={pointSelection?.id===node.id?pointSelection.request:0} onDirectConnect={(choice,basis)=>{if(configuration.event)change({...configuration,event:{...configuration.event,choices:[...configuration.event.choices.filter(c=>c.nodeId!==node.id),choice]},root:updateSetupNode(configuration.root,node.id,n=>({...n,rule:{...n.rule!,basis,source:null}}))});}} directEvent={configuration.event??null} context={configuration.context??null} eventSelection={eventSelection} reviewMode={reviewing===node.id} node={node} parent={parent} row={row} hr={hr} disabled={locked} depth={path.length-1} onNode={update} onSelect={setSelected}
  onRemove={()=>{if(!parent)return;change({...configuration,root:updateSetupNode(configuration.root,parent.id,n=>({...n,children:n.children.filter(child=>child.id!==node.id)}))});setSelected(parent.id);setNotice(c.deleteNote);}}
  onDuplicate={()=>{if(!parent)return;try{if(parent.children.length>=SETUP_LIMITS.children||path.length+Math.max(...setupNodes(node).map(n=>setupPath(node,n.id).length))>SETUP_LIMITS.depth+2)throw new Error();const copy={...copyNode(node),name:`${node.name.slice(0,90)} (2)`,shareBps:0,locked:false};change({...configuration,root:updateSetupNode(configuration.root,parent.id,n=>({...n,children:[...n.children,copy]}))});setSelected(copy.id);}catch{setNotice(c.limit);}}}/></div>
 </div>
 <div hidden={step!==6}>
 <section className={`${s.card} ${s.review}`}><header className={s.cardHeader}><div><h2>{c.review}</h2><p>{c.reviewHint}</p></div><span className={s.badge}>{preview?.complete?c.complete:c.needsWork}</span></header>
 <div className={s.tableWrap}><table className={s.table} aria-label={c.review}><thead><tr><th>{c.branch}</th><th>{c.rewards}</th><th>{c.source}</th><th>{c.amount}</th></tr></thead><tbody>{groups.map(n=><tr key={n.id}><td><button onClick={()=>{setSelected(n.id);setStep(5);}}>{setupPath(configuration.root,n.id).map(p=>p.name).join(" / ")}</button></td><td>{n.rule!.sharesBps.length}</td><td><button onClick={()=>{setSelected(n.id);setReviewing(n.id);setStep(5);}}>{(n.rule!.source||configuration.event?.choices.some(c=>c.nodeId===n.id))?(hr?"Pregledaj rezultate":"Review results"):c.source}</button></td><td>{setupAmount(preview?.rows.find(r=>r.id===n.id)?.amountWei??null,hr)}</td></tr>)}{!groups.length?<tr><td colSpan={4}>{c.empty}</td></tr>:null}</tbody></table></div><div className={s.chartFooter}><span className={s.small}>{c.remaining}</span><strong>{setupAmount(preview?.retainedWei??null,hr)} test MON</strong></div></section>
 <RewardSetupPolicy policy={configuration.policy} hr={hr} disabled={locked} onChange={policy=>change({...configuration,policy})}/>
 <section id="setup-step-6" className={`${s.card} ${s.finishCard}`} aria-label={hr?"Dovrši postavljanje":"Finish setup"}><div><span className={s.eyebrow}>6 · {hr?"Dovrši postavljanje":"Finish setup"}</span><h2>{ready?(hr?"Spremno za rezultate":"Ready for results"):(hr?"Provjerite i dovršite postavke":"Check and finish your setup")}</h2><p className={s.small}>{ready?(hr?"Postavke su dovršene. Pregledajte rezultate svake grupe kad budu dostupni. Svaka izmjena vraća postavke u nacrt.":"Setup is complete. Review each group’s results when available. Any edit returns this setup to draft."):(hr?"Spremi nacrt čuva rad u tijeku. Dovrši postavljanje sprema potpune postavke spremne za pregled rezultata.":"Save draft keeps work in progress. Finish setup saves complete settings ready for result review.")}</p>
 {!ready?<ul className={s.checklist}>{(["event","distribution","sources"] as const).map(key=><li key={key}>{readiness.includes(key)?"○":"✓"} {key==="event"?(hr?"Događaj ili liga povezani":"Event or league connected"):key==="distribution"?(hr?"Svaka raspodjela iznosi 100%":"Every allocation totals 100%"):hr?"Sve grupe povezane s odabranim događajem":"Every reward group connected to the chosen event"}</li>)}</ul>:null}
 <p className={s.small}>{hr?"Odobrenje, službena objava i isplata slijede nakon pregleda rezultata. Dovršavanje ne pokreće te korake.":"Approval, official publication and payment follow result review. Finishing setup does not perform those steps."}</p></div>
 <div className={s.actions}>{signedIn&&!ready?<button className={s.button} disabled={locked||!preview||!dirty} onClick={()=>void save()}>{hr?"Spremi kao nacrt":"Save as draft"}</button>:null}{ready?<button className={s.button} onClick={()=>change({...configuration,stage:"draft"})}>{hr?"Uredi postavke":"Edit setup"}</button>:null}{ready?<button className={s.primary} disabled={!groups.length} onClick={()=>{if(configuration.event){document.getElementById("setup-results")?.scrollIntoView({block:"start"});return;}setSelected(groups[0].id);setReviewing(groups[0].id);setStep(5);document.getElementById("reward-setup-editor")?.scrollIntoView({block:"start"});}}>{hr?"Pregledaj rezultate":"Review results"}</button>:<button className={s.primary} disabled={!signedIn||locked||!preview||readiness.length>0} onClick={()=>void save(true)}>{busy?c.saving:(hr?"Dovrši postavljanje":"Finish setup")}</button>}</div></section>
 {ready&&configuration.event?<section id="setup-results" className={`${s.card} ${s.journeySection}`}><span className={s.eyebrow}>{hr?"Sljedeće · Pregled rezultata":"Next · Review results"}</span><h2>{configuration.name}</h2><p>{hr?"Spremljena verzija":"Saved version"} {saved?.revision} · {configuration.event.name} · {configuration.event.date}</p>{groups.map(n=><RewardSetupEventResults key={`${n.id}:${configuration.event!.catalogueHash}`} event={configuration.event!} node={n} slots={preview?.rows.find(r=>r.id===n.id)?.slots??[]} hr={hr}/>)}</section>:null}
 </div>
 <div className={s.stepNavigation}>{step>1?<button className={s.button} onClick={()=>setStep(step-1)}>{hr?"Natrag":"Back"}</button>:null}{step===4?<button className={s.primary} onClick={()=>setStep(5)}>{hr?"Nastavi na raspodjelu":"Continue to distribution"}</button>:null}{step===5?<button className={s.primary} onClick={()=>setStep(6)}>{hr?"Pregled i dovršetak":"Review & finish"}</button>:null}</div>
 <Dialog.Root open={showLibrary} onOpenChange={setShowLibrary}>{showLibrary?<div className={s.modal}><Dialog.Content className={s.dialog} aria-describedby={undefined}><div className={s.heading}><Dialog.Title asChild><h2>{c.library}</h2></Dialog.Title><button className={s.button} onClick={()=>setShowLibrary(false)}>{c.close}</button></div><button className={s.primary} onClick={()=>switchDraft(null)}>{c.fresh}</button>{libraryError?<p role="alert">{c.failed} <button className={s.button} onClick={()=>void openLibrary()}>{c.retry}</button></p>:library===null?<p role="status">{c.loading}</p>:library.length?library.map(record=><button className={s.libraryItem} key={record.id} onClick={()=>switchDraft(record.id)}><strong>{record.configuration.name}</strong><span className={s.badge}>{record.configuration.stage==="ready"?(hr?"Spremno za rezultate":"Ready for results"):c.draft}</span><p>{record.configuration.event?.name??record.configuration.context?.eventName}</p><p>{record.configuration.budgetMon} test MON · {record.configuration.root.children.length} {c.branches.toLowerCase()}</p></button>):<p className={s.section}>{c.noDrafts}</p>}</Dialog.Content></div>:null}</Dialog.Root>
 </article>;
}
export default function RewardSetup({campaign=false}:{campaign?:boolean}){
 const auth=useAuth(),epoch=useRewardSessionEpoch(auth.session),[search]=useSearchParams(),{locale}=useI18n(),c=rewardSetupCopy(locale==="hr"),id=search.get("setup");
 if(auth.isLoading)return <p role="status" className={s.page}>{c.loading}</p>;
 if(id&&!setupId(id))return <p className={s.page} role="alert">{c.failed}</p>;
 if(id&&!(auth.user&&auth.session&&auth.account?.userId===auth.user.id))return <article className={s.page}><section className={`${s.card} ${s.journeySection}`}><span className={s.eyebrow}>{locale==="hr"?"Spremljeni program":"Saved programme"}</span><h1>{locale==="hr"?"Prijavite se za otvaranje postavki":"Sign in to open your saved setup"}</h1><p>{locale==="hr"?"Ova poveznica otvara privatnu raspodjelu. Prijavite se računom kojim je spremljena.":"This link opens a private distribution. Sign in with the account that saved it."}</p><Link className={s.primary} to={`/auth?next=${encodeURIComponent(`${campaign?"/rewards/create":"/rewards/setup"}?${search.toString()}`)}`}>{locale==="hr"?"Prijavi se i otvori program":"Sign in & open programme"}</Link></section></article>;
 return <SetupEditor campaign={campaign} key={`${auth.user?.id??"guest"}:${epoch}:${id??"new"}`} id={id} signedIn={Boolean(auth.user&&auth.session&&auth.account?.userId===auth.user.id)}/>;
}
