import RewardSupportSettings from '../components/RewardSupportSettings';
import * as Tabs from "@radix-ui/react-tabs";
import roleStyle from "../components/RewardRoleWorkspace.module.css";
import {useI18n} from "@/shared/i18n/I18nContext";
import {walletAdminText} from "../model/walletAdministrationCopy";
import {useCallback,useContext,useEffect,useState,type ComponentType} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '@/lib/auth';
import {publicEnv} from '@/lib/public-env';
import {readWalletAdministration,reviewWalletReplacement,activateWalletReplacement,prepareWalletCreation,type WalletCreationPreparation,type WalletAdministration as Snapshot,type WalletReview,type WalletRole} from '../data/walletAdministration';
import {OperationalWalletRuntimeContext,type OperationalWalletProps} from '../components/OperationalWalletRuntime';
import p from '../components/Podium.module.css';
import s from './RewardsControl.module.css';
import a from './WalletAdministration.module.css';
const roleName=(role:WalletRole,hr=false)=>role==='deployment'?(hr?'novčanik za stvaranje kampanja':'deployment wallet'):(hr?'kontrolora raspodjele':'distribution controller');
export default function WalletAdministration(){
 const {locale}=useI18n(),tr=(text:string)=>walletAdminText(locale,text);
 const auth=useAuth();
 if(auth.isLoading)return <p role="status">{tr("Loading account…")}</p>;
 if(!auth.user)return <article className={`${p.page} ${p.workspace}`}><header className={p.heading}><div><h1>{tr("Wallet administration")}</h1><p>{tr("Sign in with your RacesOn master-admin account.")}</p></div></header><Link className={s.primary} to="/auth?next=%2Frewards%2Fadmin%2Fwallets">{tr("Sign in")}</Link></article>;
 if(auth.account?.platformRole!=='super_admin')return <article className={`${p.page} ${p.workspace}`}><header className={p.heading}><div><h1>{tr("Master-admin access required")}</h1><p>{tr("Only an active master administrator can change Podium’s operational wallets.")}</p></div></header><Link translate="no" className={s.secondary} to="/rewards">{tr("Back to Podium")}</Link></article>;
 return <WalletSettings key={auth.user.id}/>;
}
export function WalletSettings(){
 const {locale}=useI18n(),hr=locale==='hr',tr=(text:string)=>walletAdminText(locale,text);
 const loader=useContext(OperationalWalletRuntimeContext);
 const [creation,setCreation]=useState<{preparation:WalletCreationPreparation;Runtime:ComponentType<OperationalWalletProps>}|null>(null);
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[role,setRole]=useState<WalletRole|null>(null),[walletId,setWalletId]=useState(''),[review,setReview]=useState<WalletReview|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0),[sort,setSort]=useState<'date'|'actor'|'reason'>('date'),[descending,setDescending]=useState(true);
 useEffect(()=>{let current=true;setSnapshot(null);setError('');void readWalletAdministration().then(v=>{if(current)setSnapshot(v);}).catch(()=>{if(current)setError('Wallet settings could not be loaded. Your current master-admin session is required.');});return()=>{current=false;};},[reload]);
 const [pane,setPane]=useState('deployment');
 const current=snapshot?.settings;
 const selectCreated=useCallback((id:string)=>{setWalletId(id);setReview(null);setConfirmed(false);},[]);
 function start(next:WalletRole){setPane(next);setCreation(null);setRole(next);setWalletId('');setReview(null);setReason('');setConfirmed(false);setError('');setNotice('');}
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await action();}catch{setReview(null);setConfirmed(false);setError('The wallet could not be verified or settings changed. Reload settings and check the wallet’s ownership and restricted deployment access. No change was confirmed.');}finally{setBusy(false);}}
 function sorted(column:typeof sort){setDescending(sort===column?!descending:false);setSort(column);}
 const history=[...(snapshot?.history??[])].sort((x,y)=>{const order=sort==='date'?x.revision-y.revision:sort==='actor'?x.changed_by.localeCompare(y.changed_by):x.reason.localeCompare(y.reason);return descending?-order:order;});
 return <article className={s.page}>
 <div className={a.header}><header className={s.header}><span className={s.eyebrow}>{tr("Master administration · Monad testnet")}</span><h1>{hr?"Postavke platforme":"Platform settings"}</h1><p>{hr?"Ograničen pristup. Svaka promjena se pregledava i bilježi.":"Restricted. Every change is reviewed and logged."}</p></header><button className={s.secondary} disabled={busy} onClick={()=>{setCreation(null);setRole(null);setReview(null);setNotice('');setReload(v=>v+1);}}>{tr("Reload settings")}</button></div>
 {busy?<p role="status">{tr("Verifying your current access and wallet settings…")}</p>:null}
 {error?<p role="alert">{tr(error)}</p>:null}{notice?<p role="status" className={s.verified}>{hr?`Postavke novčanika spremljene · revizija ${notice}. Sredstva nisu prenesena.`:`Wallet settings saved · revision ${notice}. No funds were moved.`}</p>:null}
 {!snapshot&&!error?<p role="status">{tr("Loading wallet settings…")}</p>:null}
 {publicEnv.hostedOperations&&current&&snapshot?.revision===0?<p role="status" className={s.notice}>{hr?'Za ovu stranicu izradite i potvrdite poseban novčanik za plin i novčanik kontrolora. Postojeći lokalni novčanici ostaju dostupni svom vlasniku.':'Create and verify a dedicated creation wallet and controller wallet for this site. Existing local wallets remain with their owner.'}</p>:null}
 {snapshot&&!current?<p className={s.notice}>{tr("The initial provider configuration is not ready. Configure the existing controller and restricted deployment service before choosing replacements.")}</p>:null}
 <Tabs.Root value={pane} onValueChange={value=>{if(!busy){setPane(value);setRole(null);setReview(null);setCreation(null);setConfirmed(false);}}}><Tabs.List className={roleStyle.tabs} aria-label={hr?"Područja administracije":"Administration areas"}>{[["deployment",hr?"Plin za stvaranje":"Creation gas"],["controller",hr?"Ovlast kontrolora":"Controller authority"],["support",hr?"Podrška isplatama primatelja":"Recipient payment support"]].map(([value,label])=><Tabs.Trigger key={value} value={value} disabled={busy}>{label}</Tabs.Trigger>)}</Tabs.List><Tabs.Content value={pane}>
 {pane!=='support'&&current?<>{current.deployment.address===current.controller.wallet?<p className={s.notice}>{tr("Both roles currently use the same wallet. Replace the deployment wallet to give campaign creation its own transaction queue.")}</p>:null}
 <div className={a.cards}>{(['deployment','controller'] as const).filter(value=>pane===value).map(value=><section key={value} className={s.card}><span className={s.eyebrow}>{value==='deployment'?tr("Automatic creation"):tr("Explicit review & signing")}</span><h2>{tr(value==='deployment'?'Deployment wallet':'Distribution controller')}</h2><p>{value==='deployment'?tr("Pays creation gas. Its service access is restricted to the verified factory on Monad testnet."):tr("Signs approved allocations and opens claims. Sponsor funds remain in campaign contracts.")}</p><p className={a.address}>{value==='deployment'?current.deployment.address:current.controller.wallet}</p><button className={s.secondary} disabled={busy} onClick={()=>start(value)}>{hr?'Zamijeni':'Replace'} {roleName(value,hr)}</button></section>)}</div>
 {pane==='deployment'?<RewardSupportSettings key={`gas:${reload}`} area="gas" hr={hr}/>:null}
 <details className={a.scope}><summary>{hr?"Opseg promjene novčanika":"What a wallet change affects"}</summary><p>{tr("Changes apply to new work. Existing campaigns keep their original controller; pending transactions keep their original signer and nonce. Changing these settings does not transfer funds or cancel transactions.")}</p></details>
 {role?<section className={s.card} aria-label={`${hr?'Zamijeni':'Replace'} ${roleName(role,hr)}`}><h2>{hr?'Zamijeni':'Replace'} {roleName(role,hr)}</h2><p>{role==='deployment'?tr("Create a new wallet in Privy, or enter an existing wallet ID. The wallet owner approves restricted campaign-creation access before Podium verifies the replacement."):tr("Choose an existing native Privy wallet owned by a user. Podium verifies its address and owner with Privy.")}</p>
 {<div className={a.create}><h3>{tr("Create with Privy")}</h3><p>{role==='deployment'?tr("Sign in as the current deployment policy’s owner. Creating a wallet does not activate it or move funds."):hr?'Prijavite se Privy računom trenutačnog kontrolora. Izrada novčanika ne dodjeljuje mu ovlast kontrolora.':'Sign in as the current controller’s Privy owner. Creating a wallet does not grant controller authority.'}</p>{creation?<creation.Runtime preparation={creation.preparation} onSelected={selectCreated} onBusy={setBusy}/>:<button type="button" className={s.secondary} disabled={busy||!loader} onClick={()=>void run(async()=>{const preparation=await prepareWalletCreation(snapshot!,role);const module=await loader!();selectCreated('');setCreation({preparation,Runtime:module.default});})}>{tr("Create new wallet with Privy")}</button>}{!loader?<p role="status">{tr("Privy creation is unavailable in this environment. You can still enter an existing wallet ID.")}</p>:null}</div>}
 <form onSubmit={event=>{event.preventDefault();void run(async()=>{const result=await reviewWalletReplacement(snapshot!,role,walletId.trim());setReview(result);setConfirmed(false);});}}><label className={s.field}>{tr("New Privy wallet ID")}<input value={walletId} onChange={event=>{setWalletId(event.target.value);setReview(null);setConfirmed(false);}} disabled={busy} required autoComplete="off" maxLength={100}/></label><p>{tr("This is the wallet’s public provider ID, not a private key or recovery phrase.")}</p><button className={s.primary} disabled={busy||!walletId.trim()}>{tr("Verify replacement")}</button></form>
 {review?<div className={s.notice}><h3>{tr("Review wallet change")}</h3><dl className={a.review}><dt>{tr("Current")}</dt><dd>{role==='deployment'?current.deployment.address:current.controller.wallet}</dd><dt>{tr("Replacement")}</dt><dd>{role==='deployment'?review.candidate.deployment.address:review.candidate.controller.wallet}</dd><dt>{tr("Network")}</dt><dd>{tr("Monad testnet · 10143")}</dd></dl><label className={s.field}>{tr("Reason for change")}<textarea value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} minLength={8} maxLength={500} rows={3}/></label><label className={a.confirm}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>{tr("I reviewed the address and understand that existing campaigns and pending transactions keep their original authority.")}</label><button className={s.primary} disabled={busy||!confirmed||reason.trim().length<8} onClick={()=>void run(async()=>{const next=await activateWalletReplacement(snapshot!,role,walletId.trim(),review,reason.trim());setSnapshot(next);setRole(null);setReview(null);setNotice(String(next.revision));})}>{tr("Activate replacement")}</button></div>:null}
 <button className={s.secondary} disabled={busy} onClick={()=>{setRole(null);setReview(null);}}>{tr("Cancel edit")}</button></section>:null}
 {<section className={s.card}><h2>{tr("Change history")}</h2><p>{hr?`Posljednjih 50 promjena · revizija ${snapshot?.revision}`:`Latest 50 changes · revision ${snapshot?.revision}`}</p>{history.length?<div className={a.table} role="region" aria-label={tr("Wallet change history")} tabIndex={0}><p className={a.scrollHint}>{tr("Scroll horizontally for reasons and wallet addresses.")}</p><table><thead><tr>{([['date','Date'],['actor','Changed by'],['reason','Reason']] as const).map(([key,label])=><th key={key} aria-sort={sort===key?descending?'descending':'ascending':'none'}><button onClick={()=>sorted(key)}>{tr(label)}{sort===key?descending?' ↓':' ↑':''}</button></th>)}<th>{tr("Wallets")}</th></tr></thead><tbody>{history.map(h=><tr key={h.revision}><td><time dateTime={h.changed_at}>{new Date(h.changed_at).toLocaleString(hr?"hr-HR":"en-GB",{timeZone:"Europe/Zagreb"})}</time><small>{hr?'Revizija':'Revision'} {h.revision}</small></td><td>{h.changed_by}</td><td>{h.reason}</td><td><details><summary>{tr("View addresses")}</summary><p>{hr?'Stvaranje kampanja':'Deployment'}: {h.settings.deployment.address}</p><p>{hr?'Kontrolor':'Controller'}: {h.settings.controller.wallet}</p><a href={`/rewards/control?wallet=${encodeURIComponent(h.settings.controller.wallet)}`}>{tr("Open this controller")}</a></details></td></tr>)}</tbody></table></div>:<p>{tr("No wallet changes have been recorded. Current settings come from the initial server configuration.")}</p>}</section>}
 </>:null}
 {pane==='support'||pane==='deployment'&&!current?<RewardSupportSettings key={`${pane}:${reload}`} area={pane==='deployment'?'gas':'support'} hr={hr}/>:null}
 </Tabs.Content></Tabs.Root>
 </article>;
}
