import { parseAbi } from "viem";

/** This intentional protocol subset is checked against the compiled Solidity ABI.
 *  No arbitrary function selector/calldata is accepted from an application user. */
export const rewardCampaignAbi = parseAbi([
  "constructor(address operator_, address treasury_, bytes32 programmeId_, bytes32 campaignId_, bytes32 programmeManifestHash_, uint8 enabledPot_)",
  "function fund() payable",
  "function closeFunding()",
  "function completeFunding(uint256 expectedAccountedFunding, uint256 expectedBudget) payable",
  "function uploadAwards((bytes32 entitlementId, bytes32 beneficiaryId, uint8 pot, uint256 amount, bytes32 explanationHash, uint8 beneficiaryKind)[] awards)",
  "function stageAllocation(bytes32 snapshotDigest_, bytes32 expectedUploadDigest, uint256 expectedCount, uint64 latestPublicationAt)",
  "function activate(bytes32 expectedAllocationDigest, bytes32 revalidatedSnapshotDigest)",
  "function claim(bytes32 entitlementId, address recipient, uint256 nonce, uint64 issuedAt, uint64 expiresAt, bytes operatorSignature, bytes recipientSignature)",
  "function claimDigests(bytes32 entitlementId, address recipient, uint256 nonce, uint64 issuedAt, uint64 expiresAt) view returns (bytes32 approvalHash, bytes32 receiptHash)",
  "function entitlements(bytes32) view returns (bytes32 beneficiaryId, uint256 amount, bytes32 explanationHash, uint256 authorizationNonce, address recipient, uint8 pot, bool paid, uint8 beneficiaryKind)",
  "function uploadDigest() view returns (bytes32)",
  "function allocationDigest() view returns (bytes32)",
  "function activationNotBefore() view returns (uint256)",
  "function claimDeadline() view returns (uint256)",
  "function state() view returns (uint8)",
  "function paused() view returns (bool)",
  "function budgets(uint256) view returns (uint256)",
  "function allocated(uint256) view returns (uint256)",
  "function paid(uint256) view returns (uint256)",
  "function accountedFunding() view returns (uint256)",
  "function treasuryReturned() view returns (uint256)",
  "function entitlementCount() view returns (uint256)",
  "function snapshotDigest() view returns (bytes32)",
  "function pausedAt() view returns (uint256)",
  "function pause()",
  "function resume()",
  "function revokeAuthorization(bytes32 entitlementId)",
  "function close()",
  "function cancel()",
  "function returnToTreasury()",
  "function returnSurplus()",
  "event RewardPaid(bytes32 indexed entitlementId, address indexed recipient, uint8 indexed pot, uint256 amount, uint256 nonce)",
  "event Funded(address indexed funder, uint256 amount, uint256 total)",
  "event FundingClosed(uint8 indexed pot, uint256 budget)",
  "event AwardUploaded(bytes32 indexed entitlementId, bytes32 indexed beneficiaryId, uint8 indexed pot, uint256 amount, bytes32 explanationHash, uint8 beneficiaryKind)",
  "event AllocationStaged(bytes32 indexed allocationDigest, bytes32 indexed snapshotDigest, uint256 count, uint256 activationNotBefore)",
  "event Activated(bytes32 indexed allocationDigest, uint256 claimDeadline)",
]);
