export type IsoDate = `${number}-${number}-${number}`;

export type RecreationalScheduleOverride = {
  sourceDate: string;
  action: "skip" | "cancel" | "reschedule";
  replacementDate?: string | null;
  replacementLocalStartTime?: string | null;
  reason?: string | null;
};

export type RecreationalScheduleOccurrence = {
  sourceDate: string;
  scheduledDate: string;
  localStartTime: string;
  state: "planned" | "cancelled" | "skipped";
  reason: string | null;
};

export type RecreationalScheduleDefinition = {
  validFrom: string;
  validUntil: string;
  weekdays: number[];
  localStartTime: string;
  overrides?: RecreationalScheduleOverride[];
};

const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const LOCAL_TIME_PATTERN = /^([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/;

function parseIsoDate(value: string) {
  if (!ISO_DATE_PATTERN.test(value)) return null;
  const [year, month, day] = value.split("-").map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  if (
    date.getUTCFullYear() !== year
    || date.getUTCMonth() !== month - 1
    || date.getUTCDate() !== day
  ) return null;
  return date;
}

function formatIsoDate(date: Date) {
  return date.toISOString().slice(0, 10);
}

function isoWeekday(date: Date) {
  const weekday = date.getUTCDay();
  return weekday === 0 ? 7 : weekday;
}

export function validateRecreationalScheduleDefinition(
  definition: RecreationalScheduleDefinition,
) {
  const validFrom = parseIsoDate(definition.validFrom);
  const validUntil = parseIsoDate(definition.validUntil);
  if (!validFrom || !validUntil) return "Use valid start and end dates.";
  if (validUntil < validFrom) return "Schedule end date must be on or after its start date.";
  if (!LOCAL_TIME_PATTERN.test(definition.localStartTime)) return "Use a valid local start time.";
  const uniqueWeekdays = new Set(definition.weekdays);
  if (
    !uniqueWeekdays.size
    || [...uniqueWeekdays].some((weekday) => !Number.isInteger(weekday) || weekday < 1 || weekday > 7)
  ) {
    return "Select at least one weekday.";
  }

  const overrideSourceDates = new Set<string>();
  for (const override of definition.overrides ?? []) {
    const sourceDate = parseIsoDate(override.sourceDate);
    if (!sourceDate) return "Every schedule exception needs a valid source date.";
    if (sourceDate < validFrom || sourceDate > validUntil || !uniqueWeekdays.has(isoWeekday(sourceDate))) {
      return "Every schedule exception must target a date generated by this rule.";
    }
    if (overrideSourceDates.has(override.sourceDate)) {
      return "Each generated date can have only one schedule exception.";
    }
    overrideSourceDates.add(override.sourceDate);
    if (override.action === "reschedule" && !parseIsoDate(override.replacementDate ?? "")) {
      return "Every rescheduled race needs a replacement date.";
    }
    if (
      override.replacementLocalStartTime
      && !LOCAL_TIME_PATTERN.test(override.replacementLocalStartTime)
    ) return "Use a valid replacement start time.";
  }

  const overrideBySourceDate = new Map(
    (definition.overrides ?? []).map((override) => [override.sourceDate, override]),
  );
  const plannedSlots = new Set<string>();
  for (
    let cursor = new Date(validFrom);
    cursor <= validUntil;
    cursor.setUTCDate(cursor.getUTCDate() + 1)
  ) {
    if (!uniqueWeekdays.has(isoWeekday(cursor))) continue;
    const sourceDate = formatIsoDate(cursor);
    const override = overrideBySourceDate.get(sourceDate);
    if (override?.action === "skip" || override?.action === "cancel") continue;
    const scheduledDate = override?.replacementDate ?? sourceDate;
    const localStartTime = override?.replacementLocalStartTime ?? definition.localStartTime;
    const slot = `${scheduledDate}|${localStartTime}`;
    if (plannedSlots.has(slot)) {
      return "Two generated races cannot use the same local date and start time.";
    }
    plannedSlots.add(slot);
  }

  return null;
}

export function expandRecreationalSchedule(
  definition: RecreationalScheduleDefinition,
): RecreationalScheduleOccurrence[] {
  const validationError = validateRecreationalScheduleDefinition(definition);
  if (validationError) throw new Error(validationError);

  const validFrom = parseIsoDate(definition.validFrom)!;
  const validUntil = parseIsoDate(definition.validUntil)!;
  const weekdays = new Set(definition.weekdays);
  const overrides = new Map(
    (definition.overrides ?? []).map((override) => [override.sourceDate, override]),
  );
  const occurrences: RecreationalScheduleOccurrence[] = [];

  for (
    let cursor = new Date(validFrom);
    cursor <= validUntil;
    cursor.setUTCDate(cursor.getUTCDate() + 1)
  ) {
    if (!weekdays.has(isoWeekday(cursor))) continue;
    const sourceDate = formatIsoDate(cursor);
    const override = overrides.get(sourceDate);
    if (override?.action === "skip" || override?.action === "cancel") {
      occurrences.push({
        sourceDate,
        scheduledDate: sourceDate,
        localStartTime: definition.localStartTime,
        state: override.action === "skip" ? "skipped" : "cancelled",
        reason: override.reason?.trim() || null,
      });
      continue;
    }

    occurrences.push({
      sourceDate,
      scheduledDate: override?.replacementDate ?? sourceDate,
      localStartTime: override?.replacementLocalStartTime ?? definition.localStartTime,
      state: "planned",
      reason: override?.reason?.trim() || null,
    });
  }

  return occurrences.sort((left, right) => (
    left.scheduledDate.localeCompare(right.scheduledDate)
    || left.localStartTime.localeCompare(right.localStartTime)
    || left.sourceDate.localeCompare(right.sourceDate)
  ));
}
