import {deriveLeagueParticipationMetrics,type LeagueParticipationMetrics} from "./league-participation-metrics.js";
import {previewParticipationReward,type ParticipationReview} from "./participation-awards.js";
import {decodeSavedRewardPlanningDraft} from "./programme-draft-v2.js";
import {decodeRewardMappingWorkspaceV2} from "./source-mapping-v2.js";
import {decodeStoredRewardSnapshot} from "./published-preview-v2.js";
import {requireHistoricalCatalogueV3} from "./historical-catalogue-v3.js";

export type ParticipationReviewChange={requestId:string;expectedReviewId:string|null;review:ParticipationReview;reason:string};
export type ParticipationReviewRecord={id:string;previousReviewId:string|null;revision:number;review:ParticipationReview;
  reason:string;reviewedAt:string;reviewedByUserId:string;current:boolean};
function check(v:unknown):asserts v {if(!v)throw Error("invalid_reward_participation_review");}
const object=(v:unknown,keys:string[])=>{check(v&&typeof v==="object"&&!Array.isArray(v));const r=v as Record<string,unknown>;
  check(Object.keys(r).sort().join()===keys.sort().join());return r;};
const uuid=(v:unknown):string=>{check(typeof v==="string"&&/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/.test(v)&&v!=="00000000-0000-0000-0000-000000000000");return v;};
const hash=(v:unknown):string=>{check(typeof v==="string"&&/^[0-9a-f]{64}$/.test(v));return v;};
const reason=(v:unknown):string=>{check(typeof v==="string"&&v.trim().length>0&&v.length<=500&&!/[\u0000-\u001f\u007f]/.test(v));return v;};
const ids=(v:unknown):string[]=>{check(Array.isArray(v)&&v.length<=20000);const result=v.map(uuid);check(new Set(result).size===result.length);return result.sort();};
export const canonicalParticipationValue=(v:unknown):string=>JSON.stringify(v,(_key,value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a<b?-1:a>b?1:0)):value);

export function decodeParticipationReview(value:unknown):ParticipationReview {
  const r=object(value,["version","sourceHash","duplicates","confirmedUnaffiliatedResultIds"]);
  check(r.version===1&&Array.isArray(r.duplicates)&&r.duplicates.length<=20000);
  const duplicates=r.duplicates.map(value=>{
    const d=object(value,["round","athleteId","resultIds","keepResultId","reason"]);
    check(Number.isInteger(d.round)&&Number(d.round)>=1&&Number(d.round)<=5);
    const resultIds=ids(d.resultIds),keepResultId=d.keepResultId===null?null:uuid(d.keepResultId);
    check(resultIds.length>=2&&(keepResultId===null||resultIds.includes(keepResultId)));
    return {round:Number(d.round),athleteId:uuid(d.athleteId),resultIds,keepResultId,reason:reason(d.reason)};
  }).sort((a,b)=>a.round-b.round||(a.athleteId<b.athleteId?-1:a.athleteId>b.athleteId?1:0));
  check(new Set(duplicates.map(d=>`${d.round}:${d.athleteId}`)).size===duplicates.length);
  const result={version:1 as const,sourceHash:hash(r.sourceHash),duplicates,confirmedUnaffiliatedResultIds:ids(r.confirmedUnaffiliatedResultIds)};
  check(JSON.stringify(result).length<=262144);return result;
}
export function decodeParticipationReviewChange(value:unknown):ParticipationReviewChange {
  const r=object(value,["requestId","expectedReviewId","review","reason"]);
  const result={requestId:uuid(r.requestId),expectedReviewId:r.expectedReviewId===null?null:uuid(r.expectedReviewId),review:decodeParticipationReview(r.review),reason:reason(r.reason)};
  check(result.requestId!==result.expectedReviewId);return result;
}
/** Reuses the reviewed-contribution checks in the existing pure estimator.
 * No sporting decision, entitlement or payment is generated by validation. */
export function validateParticipationReviewEvidence(metrics:LeagueParticipationMetrics,input:unknown) {
  const review=decodeParticipationReview(input);
  previewParticipationReward(metrics,review,{metric:"athlete_finishes",method:"proportional",minimumFinishes:1,prizeSharesBps:[]},0n);
  return review;
}
function decodeRecord(value:unknown,sourceHash:string|null,latestId:string|null):ParticipationReviewRecord {
  const r=object(value,["id","previousReviewId","revision","review","reason","reviewedAt","reviewedByUserId","current"]);
  const id=uuid(r.id),previousReviewId=r.previousReviewId===null?null:uuid(r.previousReviewId),review=decodeParticipationReview(r.review);
  check(Number.isInteger(r.revision)&&Number(r.revision)>=1&&Number(r.revision)<=2147483645);
  check(previousReviewId!==id&&(Number(r.revision)===1)===(previousReviewId===null));
  check(typeof r.reviewedAt==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|\+00:00)$/.test(r.reviewedAt)&&Number.isFinite(Date.parse(r.reviewedAt)));
  check(r.current===(id===latestId&&review.sourceHash===sourceHash));
  return {id,previousReviewId,revision:Number(r.revision),review,reason:reason(r.reason),reviewedAt:new Date(r.reviewedAt).toISOString(),reviewedByUserId:uuid(r.reviewedByUserId),current:r.current as boolean};
}
/** Both server and browser validate the same source envelope. SQL supplies no
 * metric totals; the server derives them, and the browser verifies them. */
export function decodeParticipationReviewWorkspace(value:unknown,includesMetrics=false) {
  const r=object(value,["record","workspace","snapshot","sourceHash","review","history","recordedReview",...(includesMetrics?["metrics"]:[])]);
  const record=decodeSavedRewardPlanningDraft(r.record),workspace=decodeRewardMappingWorkspaceV2(r.workspace);
  check(workspace.draftId===record.draftId&&workspace.rulesRevision===record.revision);
  const snapshot=r.snapshot===null?null:decodeStoredRewardSnapshot(r.snapshot),sourceHash=r.sourceHash===null?null:hash(r.sourceHash);
  check((snapshot===null)===(sourceHash===null));if(snapshot)requireHistoricalCatalogueV3(snapshot,workspace.catalogue);
  const metrics=snapshot?deriveLeagueParticipationMetrics(snapshot,sourceHash!):null;
  if(includesMetrics)check(canonicalParticipationValue(metrics)===canonicalParticipationValue(r.metrics));
  const latestId=r.review&&typeof r.review==="object"&&"id" in r.review?uuid(r.review.id):null;
  const review=r.review===null?null:decodeRecord(r.review,sourceHash,latestId);
  check(Array.isArray(r.history)&&r.history.length<=10);
  const history=r.history.map(row=>decodeRecord(row,sourceHash,latestId));
  check(review?history.length>0&&canonicalParticipationValue(history[0])===canonicalParticipationValue(review):history.length===0);
  for(let i=1;i<history.length;i++)check(history[i-1]!.previousReviewId===history[i]!.id&&history[i-1]!.revision===history[i]!.revision+1);
  const recordedReview=r.recordedReview===null?null:decodeRecord(r.recordedReview,sourceHash,latestId);
  if(review?.current&&metrics)validateParticipationReviewEvidence(metrics,review.review);
  return {record,workspace,snapshot,sourceHash,metrics,review,history,recordedReview};
}
export type ParticipationReviewWorkspace=ReturnType<typeof decodeParticipationReviewWorkspace>;
