import test from 'node:test';
import assert from 'node:assert/strict';
import {createRewardSetup,defaultRewardSetupPolicy,decodeRewardSetup,finishRewardSetup,setupReadiness,previewRewardSetup} from '../../../packages/domain/dist/rewards/distribution-setup.js';
import {generateEventTree,previewEventGroup} from '../../../packages/domain/dist/rewards/setup-event.js';
import {eventCatalogue,rewardSetupEvents} from '../../../packages/db/dist/rewards/setup-events.js';
import {dispatchSetupEvents} from '../dist/routes/rewards/setup-events.js';
const id=n=>`77000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const rawEvent=()=>({id:id(1),name:'Synthetic standalone 2026',date:'2026-10-03',organizationName:'Synthetic organizer',catalogueHash:'a'.repeat(64),races:[{id:id(2),name:'Long route',distanceKm:25,minimumAge:18,maximumAge:null,genders:['F','M'],resultsMode:'standard',ranking:{overall:{enabled:true},age:{enabled:true,buckets:[{key:'18-39',label:'Age 18–39',minAge:18,maxAge:39}]},team:{enabled:true,mode:'club',label:'Club standings',scoringMethod:'best_three_by_place',scoringCount:3}}},{id:id(3),name:'Short route',distanceKm:null,minimumAge:null,maximumAge:null,genders:[],resultsMode:'standard',ranking:{overall:{enabled:true}}}]});
const event=()=>eventCatalogue(rawEvent());
function config(){let seq=100;return {...createRewardSetup(id(90)),version:4,programmeKind:'event',context:null,stage:'draft',policy:defaultRewardSetupPolicy(),...generateEventTree(createRewardSetup(id(90)).root,event(),[{raceId:id(2),groupKey:'overall',winners:2,approved:true},{raceId:id(2),groupKey:'age:18-39',winners:7,approved:true},{raceId:id(3),groupKey:'overall',winners:1,approved:true}],()=>id(seq++))};}
test('standalone event generates only selected groups, independent winner counts, and finishes without any league',()=>{const c=config();assert.equal(c.context,null);assert.deepEqual(c.root.children.map(r=>r.children.map(n=>n.rule.sharesBps.length)),[[2,7],[1]]);assert.equal(previewRewardSetup(c).complete,true);assert.equal(finishRewardSetup(c).stage,'ready');assert.deepEqual(decodeRewardSetup(c),c);});
test('event setup refuses mixed scopes, incomplete eligibility and mismatched club basis',()=>{const c=config();c.event.choices[0].approved=false;assert.deepEqual(setupReadiness(c),['sources']);assert.throws(()=>finishRewardSetup(c));c.event.choices[0].approved=true;c.root.children[0].children[0].rule.basis='club_points';assert.throws(()=>finishRewardSetup(c));assert.throws(()=>decodeRewardSetup({...config(),programmeKind:'league'}));assert.throws(()=>decodeRewardSetup({...config(),event:{...config().event,choices:[...config().event.choices,config().event.choices[0]]}}));});
test('missing structure is explicit and clubs require a configured ranking method',()=>{const e=event();assert.equal(e.races[0].groups.find(g=>g.kind==='club').key,'club');assert.deepEqual(e.races[1].groups.map(g=>g.key),['overall']);assert.ok(e.races[1].missing.includes('Distance is missing'));assert.ok(e.races[1].missing.includes('Club ranking is not configured'));const raw=rawEvent();delete raw.races[0].ranking;assert.equal(eventCatalogue(raw).races[0].groups.length,0);});
test('preview shares tied occupied prizes, preserves unused places, and rejects stale/unpublished sources',()=>{const c=config(),node=c.root.children[0].children[0],choice=c.event.choices[0];const results={catalogueHash:c.event.catalogueHash,publicationId:id(8),publicationState:'official',publishedAt:'2026-10-03T12:00:00Z',groups:[{raceId:choice.raceId,groupKey:choice.groupKey,issue:null,candidates:[{beneficiaryId:id(11),name:'Synthetic A',order:1,evidenceIds:[id(21)],evidenceValue:1000},{beneficiaryId:id(12),name:'Synthetic B',order:1,evidenceIds:[id(22)],evidenceValue:1000}]}]};assert.equal(previewEventGroup(c.event,node,[],results).issue,'distribution_incomplete');assert.deepEqual(previewEventGroup(c.event,node,[150n,100n],results).awards.map(a=>a.amountWei),[125n,125n]);results.groups[0].candidates.pop();assert.equal(previewEventGroup(c.event,node,[150n,100n],results).unusedWei,100n);assert.equal(previewEventGroup(c.event,node,[150n,100n],{...results,catalogueHash:'b'.repeat(64)}).issue,'source_changed');assert.equal(previewEventGroup(c.event,node,[150n,100n],{...results,publicationState:'provisional'}).issue,'awaiting_publication');});
test('read adapter binds account scope, normalizes eligibility, and never exposes age or sex to the browser',async()=>{let args;const raw={catalogue:rawEvent(),publication:{id:id(8),state:'official',publishedAt:'2026-10-03T12:00:00Z',runStatus:'succeeded',runRaceId:id(2),completed:true},expectedCount:2,rows:[{id:id(21),athleteId:id(11),name:'Synthetic A',gender:'female',age:25,clubId:null,clubName:null,status:'official',participation:'finished',finishTimeMs:1000,rank:1,valid:true},{id:id(22),athleteId:id(12),name:'Synthetic B',gender:'male',age:42,clubId:null,clubName:null,status:'official',participation:'finished',finishTimeMs:1000,rank:1,valid:true}]};const rpc=async(name,a)=>{assert.equal(name,'service_reward_setup_events');args=a;return{data:raw,error:null};};const result=await rewardSetupEvents({userId:id(30),sessionId:id(31)},id(1),id(2),rpc);assert.equal(args.p_actor_user_id,id(30));assert.equal(result.groups.find(g=>g.groupKey==='overall').candidates.length,2);assert.equal(result.groups.find(g=>g.groupKey==='age:18-39').candidates.length,1);assert.ok(!JSON.stringify(result).includes('"age"'));assert.ok(!JSON.stringify(result).includes('"gender"'));raw.rows[0].valid=false;assert.equal((await rewardSetupEvents({userId:id(30),sessionId:id(31)},id(1),id(2),rpc)).groups[0].issue,'ambiguous_results');});
test('private event endpoint rejects identity overrides and invalid scopes before the repository',async()=>{let calls=0,response;const deps={config:()=>({chainId:31337}),requireIdentity:async()=>({userId:id(30),sessionId:id(31)}),rpc:async()=>{calls++;return{data:[],error:null};},applyPrivateSessionHeaders(){},sendSuccess:(_r,data)=>response={status:200,data},sendError:(_r,status)=>response={status}};const res={setHeader(){}};await dispatchSetupEvents({method:'GET'},res,new URL('http://local/api/v1/rewards/setup-events'),deps);assert.equal(response.status,200);await dispatchSetupEvents({method:'GET'},res,new URL('http://local/api/v1/rewards/setup-events?owner=other'),deps);assert.equal(response.status,400);assert.equal(calls,1);await dispatchSetupEvents({method:'GET'},res,new URL('http://local/api/v1/rewards/setup-events'),{...deps,requireIdentity:async()=>{throw Error('Unauthorized');}});assert.equal(response.status,401);assert.equal(calls,1);});
test('league review uses authoritative eligible ranks and the edited slot amounts, and holds stale sources',async()=>{
 const {previewSetupLeagueSource}=await import('../../../packages/domain/dist/rewards/distribution-setup-results.js');
 const workspace={draftId:id(1),catalogueHash:'a'.repeat(64)},node={...config().root.children[0].children[0],rule:{basis:'league_position',sharesBps:[6000,4000],source:{draftId:id(1),roundId:null,categoryId:id(2),catalogueHash:'a'.repeat(64)}}};
 const view={draftId:id(1),labels:{athletes:[{id:id(11),name:'Synthetic A'},{id:id(12),name:'Synthetic B'}],clubs:[]},proposal:{state:'unapproved_proposal',athleteTables:[{categoryId:id(2),rows:[{beneficiaryId:id(11),rank:1,eligible:true,points:50,rounds:[{sourceRowId:id(21)}]},{beneficiaryId:id(12),rank:1,eligible:true,points:50,rounds:[{sourceRowId:id(22)}]},{beneficiaryId:id(13),rank:null,eligible:false,points:10,rounds:[]}]}],clubTables:[]}};
 const p=previewSetupLeagueSource(node,[150n,100n],workspace,view);assert.deepEqual(p.awards.map(a=>a.amountWei),[125n,125n]);assert.equal(p.reason,null);assert.equal(previewSetupLeagueSource(node,[150n,100n],workspace,{...view,proposal:{state:'held'}}).reason,'awaiting_results');assert.equal(previewSetupLeagueSource(node,[150n,100n],{...workspace,catalogueHash:'b'.repeat(64)},view).reason,'source_changed');
});
