import {useI18n} from "@/shared/i18n/I18nContext";
import {walletAdminText} from "../model/walletAdministrationCopy";
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {controllerJobSchema,controllerNonceStatusSchema,confirmControllerJob,recoverControllerJob,type ControllerJob} from '../data/controllerTransactions';
import type {ControllerConnection} from '../screens/RewardsControl';
import type {ControllerSession} from '../data/controller';
import {setupAmount} from '../model/setupAmount';
import s from '../screens/RewardsControl.module.css';
const status=z.object({pending:controllerJobSchema.nullable(),factory:controllerJobSchema.nullable(),nonceStatus:controllerNonceStatusSchema.nullable().optional()}).strict();
export default function ControllerCreationSetup({connection,session,onRefresh}:{connection:ControllerConnection;session:ControllerSession;onRefresh:()=>Promise<void>}){
 const {locale}=useI18n(),hr=locale==='hr',tr=(text:string)=>walletAdminText(locale,text);
 const [nonceStatus,setNonceStatus]=useState<z.infer<typeof controllerNonceStatusSchema>|null>(null);
 const [pending,setPending]=useState<ControllerJob|null>(null),[factory,setFactory]=useState<ControllerJob|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),live=useRef(true),flight=useRef(false);
 async function load(){const v=status.parse(await connection.request('/transactions'));if(live.current&&connection.isCurrent()){setPending(v.pending);setFactory(v.factory);setNonceStatus(v.nonceStatus??null);}}
 useEffect(()=>{live.current=true;void load().catch(()=>{if(live.current)setError('Setup status could not be checked. Refresh to retry.');});return()=>{live.current=false;};},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function run(action:()=>Promise<void>){if(flight.current)return;flight.current=true;setBusy(true);setError(null);try{await action();await load();}catch(e){if(live.current)setError(e instanceof Error&&e.message.startsWith('controller_wallet_changed:')?`The wallet changed the prepared ${e.message.split(':')[1]}. Nothing was sent.`:e instanceof Error&&e.message==='controller_local_signature_missing'?'No signature is saved in this browser. Check setup status for a transaction saved by the server. Otherwise, use the browser where you confirmed or return to campaign review. The request remains reserved.':e instanceof Error&&e.message==='controller_session_changed'?'Your controller session changed. Sign in with the assigned controller account before recovering this request.':e instanceof Error&&e.message==='controller_transaction_pending'?'Another controller transaction is pending. Complete it before continuing.':'The step is not confirmed. Refresh or retry the saved transaction.');}finally{flight.current=false;if(live.current)setBusy(false);}}
 const setup=session.creation?.setup,ready=session.creation?.configured,separate=Boolean(session.creation?.address&&session.creation.address!==session.wallet),blocksCreation=Boolean(pending&&!separate);
 return <section className={s.card}><span className={s.eyebrow}>{tr("Sponsor self-service")}</span><h2>{tr("Automatic campaign creation")}</h2>
 {ready?<p className={blocksCreation?s.notice:s.verified}>{blocksCreation?tr('Campaign creation is waiting for this controller request.'):separate?tr('Provider access verified · separate deployment wallet'):tr('Ready · deployment-only controller access verified')}</p>:separate?<p className={s.notice}>{tr("The separate deployment wallet needs verified provider access. A master administrator can review it in Wallet administration.")}</p>:<><p>{tr("One-time setup lets sponsors create campaigns automatically using your controller’s gas. Every distribution still requires your review and Privy confirmation.")}</p>
 {!factory&&!pending?<button className={s.primary} disabled={busy||!connection.signTransaction} onClick={()=>void run(async()=>{const j=controllerJobSchema.parse(await connection.request('/transactions',{action:'prepare',kind:'factory'}));setFactory(j);setPending(j);})}>{tr("Review one-time setup")}</button>:null}
 {factory?.confirmed?<><p className={s.verified}>{tr("Deployment contract verified on Monad testnet.")}</p>{setup&&factory.factory===setup.factory?<button className={s.primary} disabled={busy||!connection.addSigner} onClick={()=>void run(async()=>{await connection.addSigner!(session.wallet,setup.signerId,setup.policyId);await onRefresh();})}>{tr("Enable automatic campaign creation")} · Privy</button>:<p>{tr("Deployment-only Privy access is being configured for this contract.")}</p>}</>:null}</>}
 {pending?<div className={s.notice}><strong>{pending.context.kind==='factory'?tr('One-time deployment setup'):pending.context.kind==='clubClaim'?'Club claim payment':pending.context.kind==='claim'?'Claim payment':tr('Distribution transaction')} · {pending.hash?tr('receipt verification needed'):tr('no signature recorded by the server')}</strong>
 <p>{nonceStatus?.state==='unused'?tr('The reserved nonce has not been used on the checked chain. A signature may still be saved in another browser.'):nonceStatus?.state==='pending'?tr('The network reports a pending transaction at this nonce. Recover the saved transaction to verify its outcome.'):nonceStatus?.state==='consumed'?tr('The reserved nonce has been used on-chain. This does not confirm this distribution. Verify its saved receipt before continuing.'):separate?tr('Chain status is unavailable. The distribution request remains reserved; check setup status to retry.'):tr('Chain status is unavailable. The saved request still holds campaign creation; check setup status to retry.')}</p>
 <details className={s.recoveryDetails}><summary>{tr("Request and network details")}</summary><dl>
 <div><dt>{tr("Request")}</dt><dd>{pending.id}</dd></div>
 {pending.context.kind==='claim'||pending.context.kind==='clubClaim'?<><div><dt>Campaign</dt><dd>{pending.context.setupId}</dd></div><div><dt>Claim request</dt><dd>{pending.context.claimId}</dd></div></>:null}
 {pending.context.kind==='distribution'?<><div><dt>{tr("Campaign")}</dt><dd>{pending.context.setupId}</dd></div><div><dt>{tr("Action")}</dt><dd>{pending.context.action==='upload'?tr('Upload approved awards'):pending.context.action==='stage'?tr('Stage approved distribution'):tr('Open claims')}</dd></div></>:null}
 <div><dt>{tr("Network")}</dt><dd>{tr("Monad testnet · 10143")}</dd></div>
 <div><dt>{tr("Controller")}</dt><dd>{session.wallet}</dd></div>
 <div><dt>{tr("Destination")}</dt><dd>{pending.transaction.to??pending.factory??tr('Contract creation')}</dd></div>
 <div><dt>{tr("Reserved nonce")}</dt><dd>{pending.transaction.nonce}</dd></div>
 {nonceStatus?.observedAt?<><div><dt>{tr("Finalized / pending nonce")}</dt><dd>{nonceStatus.finalizedNonce} / {nonceStatus.pendingNonce}</dd></div><div><dt>{tr("Checked at (UTC)")}</dt><dd>{nonceStatus.observedAt.replace('T',' ').replace('Z','')}</dd></div></>:null}
 </dl><p>{tr("This check cannot cancel a request or prove a reward payment. The reservation stays in place until its outcome is verified.")}</p></details>
 <p>{tr("Maximum fee:")} {setupAmount(BigInt(pending.transaction.gas)*BigInt(pending.transaction.gasPrice),hr)} {tr("test MON. Reward deposit: 0.")}</p>
 {pending.factory?<p className={s.address}>{tr("Deployment contract:")} {pending.factory}</p>:null}
 {pending.hash?<p className={s.address}>{pending.hash}</p>:null}
 {pending.context.kind==='distribution'&&!pending.hash?<><p>{tr("Open the saved campaign to review its awards before wallet confirmation.")}</p></>:null}
 <div className={s.recoveryActions}>{(pending.context.kind==='claim'||pending.context.kind==='clubClaim')&&!pending.hash?<a className={s.primary} href={`/rewards/control?campaign=${encodeURIComponent(pending.context.setupId)}&approval=${encodeURIComponent(pending.context.approvalId)}&claim=${encodeURIComponent(pending.context.claimId)}&wallet=${encodeURIComponent(session.wallet)}${pending.context.kind==='clubClaim'?'&claimKind=club':''}`}>{pending.context.kind==='clubClaim'?'Review pending club claim payment':'Review pending claim payment'}</a>:null}{pending.context.kind==='distribution'&&!pending.hash?<a className={s.primary} href={`/rewards/control?campaign=${encodeURIComponent(pending.context.setupId)}&wallet=${encodeURIComponent(session.wallet)}`}>{tr("Review pending distribution")}</a>:null}
 <button className={pending.context.kind==='distribution'&&!pending.hash?s.secondary:s.primary} disabled={busy} onClick={()=>void run(async()=>{if(pending.hash)await recoverControllerJob(connection,pending);else if(pending.context.kind==='factory')await confirmControllerJob(connection,session.wallet,pending);else await recoverControllerJob(connection,pending);})}>{pending.hash?tr('Verify saved transaction'):pending.context.kind==='factory'?tr('Confirm setup with Privy'):tr('Recover a saved signature')}</button></div>
 {pending.context.kind==='distribution'&&!pending.hash?<p>{tr("Already confirmed in this browser? Recover the saved signature without signing again. If no signature was saved, return to campaign review.")}</p>:null}</div>:null}
 <details className={s.walletExplanation}><summary>{hr?"Novčanici i mrežne naknade":"Wallets & network fees"}</summary>{separate?<p>{tr("Distribution requests use your controller wallet. Campaign creation uses")} {session.creation?.address} {tr("and has its own transaction queue.")}</p>:null}<p>{tr("RacesOn pays creation and distribution gas. Sponsors deposit their own reward funds into campaign contracts.")}</p></details>
 <button className={s.secondary} disabled={busy} onClick={()=>void run(async()=>{await onRefresh();})}>{tr("Check setup status")}</button>
 {error?<p role="alert">{tr(error)}</p>:null}</section>;
}
