import {lazy, Suspense, useState, type ReactNode} from "react";
import {Link,useSearchParams} from "react-router-dom";
import {previewRewardSetup, setupReadiness, setupNodes, updateSetupNode, presetSetupShares, type RewardDistributionSetup, type RewardSetupNode} from "@raceson/domain/rewards/distribution-setup";
import {GUIDED_REWARD_TYPES, isParticipationType, type GuidedRewardType, type GuidedRewardGroup} from "@raceson/domain/rewards/guided-setup";
import {addGuidedGroup, bindGuidedSeason, changeGuidedMethod, connectGuidedGroup, copyGuidedRound, guidedCategories, removeGuidedGroup} from "@raceson/domain/rewards/guided-setup-editor";
import SponsorTargets from "./SponsorTargets";
import SponsorCampaignStudio from "./SponsorCampaignStudio";
import SponsorPrizeEditor from "./SponsorPrizeEditor";
import {sponsorIntent} from "../model/sponsorOpportunities";
import RewardSetupEvent, {type SetupEventSelection} from "./RewardSetupEvent";
import RewardSetupChart from "./RewardSetupChart";
import RewardSetupPolicy from "./RewardSetupPolicy";
import {setupAmount} from "../model/setupAmount";
import s from "./RewardSetup.module.css";
import g from "./GuidedRewardSetup.module.css";
const Metrics = lazy(()=>import("./RewardLeagueMetrics"));
const SeasonPicker = lazy(()=>import("../screens/CreateRewardProgramme"));

export type GuidedRewardSetupProps = {
 copySource?:{name:string;slot:number;categoryKeys?:import("../model/copyExistingRoundRules").ExistingCategoryKeys;visibleGroups?:Set<string>;tracks?:import("../model/sponsorTrackAllocation").SponsorTrack[]};
  setupId?:string; sourceLocked?:boolean;
  campaign?:boolean; configuration:RewardDistributionSetup; onChange:(value:RewardDistributionSetup)=>void;
  step:number; onStep:(step:number,round?:number)=>void; disabled:boolean; hr:boolean;
  selection:SetupEventSelection|null; onLoaded:(selection:SetupEventSelection|null)=>void;
  initialProgramme:string|null; saveAction:ReactNode; saveStatus:ReactNode; error:ReactNode;
  launchHref?:string; onFinish:()=>void; isSaved?:boolean; canSave:boolean; busy:boolean; revision:number|null;
};
export default function GuidedRewardSetup(props:GuidedRewardSetupProps) {
  return props.campaign?<SponsorCampaignStudio {...props}/>:<ClassicGuidedRewardSetup {...props}/>;
}
function ClassicGuidedRewardSetup(props:GuidedRewardSetupProps) {
  const {configuration:c,onChange,disabled:baseDisabled,hr,selection,onLoaded}=props,meta=c.guided!;
  const [dataReviewUnsaved,setDataReviewUnsaved]=useState(false),[leagueReviewUnsaved,setLeagueReviewUnsaved]=useState(false);
  const reviewUnsaved=dataReviewUnsaved||leagueReviewUnsaved,disabled=baseDisabled||reviewUnsaved;
  const t=(en:string,local:string)=>hr?local:en,step=Math.min(5,props.step);
  const [search]=useSearchParams(),intent=sponsorIntent(search.get("opportunity"),hr);
  const stepOrder=props.campaign?[1,4,2,5]:[1,2,3,4,5],stepIndex=stepOrder.indexOf(props.campaign&&step===3?4:step);
  const [activeRound,setActiveRound]=useState(intent?.round||1),[selected,setSelected]=useState(c.root.id),[rank,setRank]=useState<number|null>(null);
  const [categoryId,setCategoryId]=useState(""),[addType,setAddType]=useState<GuidedRewardType>("athlete_standings");
  const [copyTargets,setCopyTargets]=useState<string[]>([]),[copyPreview,setCopyPreview]=useState(false),[localError,setLocalError]=useState("");
  const [showSeasons,setShowSeasons]=useState(false),[addedProgramme,setAddedProgramme]=useState<string|null>(null);
  const [workspaceView,setWorkspaceView]=useState<"setup"|"review">(c.stage==="ready"?"review":"setup");
  const [chartVisible,setChartVisible]=useState(false);
  let preview:ReturnType<typeof previewRewardSetup>|null=null;
  try {preview=previewRewardSetup(c);}catch {/* Form input can be temporarily incomplete. */}
  const readiness=setupReadiness(c),catalogue=selection&&selection.record.draftId===c.context?.draftId&&selection.workspace.catalogueHash===c.context.catalogueHash?selection.workspace.catalogue:null;
  const pot=meta.pots.find(p=>p.slot===(step===3?activeRound:0))!,potNode=c.root.children.find(n=>n.id===pot.nodeId)!;
  const options=catalogue?guidedCategories(catalogue,pot.roundId,addType):[];
  const group=meta.groups.find(v=>v.nodeId===selected),selectedNode=setupNodes(c.root).find(n=>n.id===selected)??c.root;
  const selectedPot=meta.pots.find(p=>p.nodeId===selected||c.root.children.find(n=>n.id===p.nodeId)?.children.some(n=>n.id===selected));
  const labels:Record<GuidedRewardType,string>={athlete_standings:t("Athlete standings","Poredak sportaša"),club_standings:t("Club standings","Klupski poredak"),athlete_finishes:t("Athlete finishes","Broj završetaka"),athlete_metres:t("Athlete kilometres","Kilometri sportaša"),club_metres:t("Club kilometres","Kilometri klubova")};
  const steps=props.campaign?[t("League","Liga"),t("Budget","Fond"),t("Rewards","Nagrade"),t("Rewards","Nagrade"),t("Review","Pregled")]:[t("League and data","Liga i podaci"),t("Reward pots","Fondovi nagrada"),t("Round rewards","Nagrade kola"),t("League rewards","Nagrade lige"),t("Review and finish","Pregled i dovršetak")];
  function safely(action:()=>RewardDistributionSetup) {try {onChange(action());setLocalError("");}catch {setLocalError(t("Check the programme name, budget and category. These settings could not be applied.","Provjerite naziv, fond i kategoriju. Postavke nisu primijenjene."));}}
  function editNode(id:string,update:(n:RewardSetupNode)=>RewardSetupNode) {onChange({...c,root:updateSetupNode(c.root,id,update)});}
  function editGroup(id:string,change:Partial<GuidedRewardGroup>) {onChange({...c,guided:{...meta,groups:meta.groups.map(v=>v.nodeId===id?{...v,...change}:v)}});}
  function go(next:number){if(reviewUnsaved)return;props.onStep(next);setCopyPreview(false);setCopyTargets([]);setCategoryId("");setAddType("athlete_standings");}
  const amount=(id:string)=>setupAmount(preview?.rows.find(r=>r.id===id)?.amountWei??null,hr);
  const sum=(node:RewardSetupNode)=>node.children.reduce((n,c)=>n+c.shareBps,0)/100;
  function percent(label:string,value:number,change:(value:number)=>void) {return <label className={s.field}>{label}<span className={g.inputUnit}><input aria-label={label} type="number" min="0" max="100" step="0.01" value={value/100} disabled={disabled} onChange={e=>{if(e.target.value!==""&&e.target.validity.valid)change(Math.round(Number(e.target.value)*100));}}/><span>%</span></span></label>;}

  return <article className={`${s.page} ${g.page} ${props.campaign?g.campaign:""}`}>
    <Link className={s.small} to="/rewards/manage" aria-disabled={reviewUnsaved} onClick={e=>{if(reviewUnsaved)e.preventDefault();}}>← {t("My campaigns","Moje kampanje")}</Link>
    <header className={s.heading}><div><h1>{props.campaign?t("Sponsor campaign","Sponzorska kampanja"):c.name}</h1>{c.context?<p>{c.context.eventName}</p>:null}</div><fieldset className={s.actions} disabled={reviewUnsaved} style={{border:0,margin:0,padding:0}}>{props.saveAction}</fieldset></header>
    {!props.campaign?<div className={g.workspace}><button aria-current={workspaceView==="setup"?"page":undefined} disabled={reviewUnsaved} onClick={()=>setWorkspaceView("setup")}>{t("Set up","Postavi")}</button><button disabled={c.stage!=="ready"||reviewUnsaved} aria-current={workspaceView==="review"?"page":undefined} onClick={()=>setWorkspaceView("review")}>{t("Review awards","Pregledaj nagrade")}</button><span>{t("Release rewards","Objavi nagrade")}</span><span>{t("Track claims","Prati preuzimanja")}</span></div>:null}
    {!props.campaign?<div className={g.status}>{props.saveStatus}<span>{c.budgetMon} test MON</span></div>:null}
    {reviewUnsaved?<p role="status" className={s.notice}>{t("Save or discard the contribution review before leaving this step.","Spremite ili odbacite provjeru doprinosa prije napuštanja ovog koraka.")}</p>:null}
    {props.error}{localError?<p role="alert" className={s.notice}>{localError}</p>:null}
    {!preview?<p role="alert" className={s.notice}>{t("Enter a programme name and a valid positive budget before saving.","Unesite naziv programa i valjan pozitivan fond prije spremanja.")}</p>:null}
    {workspaceView==="review"?<section className={`${s.card} ${g.body}`}><h2>{t("Ready for results","Spremno za rezultate")}</h2><p>{t("Rules version","Verzija pravila")} {props.revision}. {t("Review each pot when its official results are available. League awards use the approved campaign period and result snapshot.","Pregledajte svaki fond kad službeni rezultati budu dostupni. Nagrade lige čekaju konačne rezultate sezone.")}</p><div className={g.potGrid}>{meta.pots.map(p=>{const n=c.root.children.find(n=>n.id===p.nodeId)!;return <div key={p.nodeId} className={g.pot}><h3>{n.name}</h3><strong>{amount(n.id)} test MON</strong><p>{t("Award review integration pending","Povezivanje pregleda nagrada u tijeku")}</p></div>;})}</div><p className={s.notice}>{t("This saved setup is not yet connected to final award approval. It does not release funds.","Ove spremljene postavke još nisu povezane s konačnim odobrenjem nagrada. Ne pokreću isplatu.")}</p></section>:<>
    <ol id="setup-workflow" className={`${s.workflow} ${g.steps} ${props.campaign?g.fourSteps:""}`} aria-label={t("Setup progress","Koraci postavljanja")}>{stepOrder.map((stage,i)=><li key={stage}><button disabled={reviewUnsaved} aria-current={stepOrder[stepIndex]===stage?"step":undefined} onClick={()=>go(stage)}><span>{i+1}</span>{steps[stage-1]}</button></li>)}</ol>
    <section className={`${s.card} ${g.body}`} aria-label={steps[step-1]}><div className={g.sectionHeading}><div><h2>{steps[step-1]}</h2></div>{step>1?<button className={s.button} onClick={()=>setChartVisible(v=>!v)}>{chartVisible?t("Hide overview","Sakrij pregled"):t("Distribution overview","Pregled raspodjele")}</button>:null}</div>
      <div hidden={step!==1}>

        <label className={s.field}>{props.campaign?t("Campaign name","Naziv kampanje"):t("Programme name","Naziv programa")}<input value={c.name} disabled={disabled} maxLength={100} onChange={e=>onChange({...c,name:e.target.value})}/></label>
        <RewardSetupEvent compact={props.campaign} leagueOnly preferSibenik={props.campaign&&Boolean(intent)} context={c.context??null} initialProgramme={addedProgramme??props.initialProgramme} key={addedProgramme??"current"} hr={hr} disabled={disabled} onLoaded={onLoaded} onChange={context=>{if(selection)safely(()=>bindGuidedSeason(c,context,selection.workspace.catalogue));}}/>
        <button className={s.button} disabled={disabled} onClick={()=>setShowSeasons(v=>!v)}>{t("Find a league","Pronađi ligu")}</button>
        {showSeasons?<Suspense fallback={<p>{t("Loading…","Učitavanje…")}</p>}><SeasonPicker initialBudgetMon={c.budgetMon} onSelected={id=>{setAddedProgramme(id);setShowSeasons(false);}}/></Suspense>:null}
        {c.context?<details className={g.details}><summary>{t("Included rounds","Uključena kola")}</summary><div className={g.roundList}>{meta.pots.filter(p=>p.slot>0).map(p=>{const round=catalogue?.rounds.find(r=>r.id===p.roundId);return <div className={g.round} key={p.nodeId}><strong>{p.slot}. {c.root.children.find(n=>n.id===p.nodeId)!.name}</strong><span>{round?.date??t("Edition not connected","Izdanje nije povezano")}</span><span>{round?.races.map(r=>`${r.name} · ${r.distanceMetres===null?"?":Number(r.distanceMetres)/1000} km`).join(" / ")}</span></div>;})}</div></details>:null}
        {catalogue&&selection?<details className={g.details}><summary>{t("Organizer data review","Organizatorska provjera podataka")}</summary><Suspense fallback={<p>{t("Loading…","Učitavanje…")}</p>}><Metrics selection={selection} hr={hr} onReviewUnsavedChange={setDataReviewUnsaved}/></Suspense></details>:null}
        <p className={s.small}>{t("Demo scope: rounds 1–5 of 7.","Demo obuhvat: kola 1–5 od 7.")}</p>
      </div>
      {step===2?<><label className={s.field}>{t("Total budget · test MON","Ukupni fond · test MON")}<input inputMode="decimal" disabled={disabled} value={c.budgetMon} onChange={e=>onChange({...c,budgetMon:e.target.value})}/></label><div className={g.potGrid}>{meta.pots.map(p=>{const n=c.root.children.find(n=>n.id===p.nodeId)!;return <div key={p.nodeId} className={g.pot}><h3>{n.name}</h3><strong>{amount(n.id)} test MON</strong>{percent(`${n.name} %`,n.shareBps,v=>editNode(n.id,n=>({...n,shareBps:v})))}</div>;})}</div><p className={sum(c.root)===100?s.success:s.notice}>{sum(c.root)}% {t("allocated","raspoređeno")} · {t("Target 100%","Cilj 100%")}</p></>:null}
      {step===3||step===4?<>
        {props.campaign?<label className={s.field}>{t("Reward pot","Fond nagrada")}<select disabled={reviewUnsaved} value={step===4?0:activeRound} onChange={e=>{const slot=Number(e.target.value);setActiveRound(slot||1);go(slot===0?4:3);}}>{meta.pots.map(p=><option key={p.nodeId} value={p.slot}>{c.root.children.find(n=>n.id===p.nodeId)!.name}</option>)}</select></label>:step===3?<><p>{t("Configure one round, then copy its groups to the rounds you select. Each round keeps its own settings.","Postavite jedno kolo pa kopirajte grupe u odabrana kola. Svako kolo ima vlastite postavke.")}</p><div className={g.roundTabs} role="group" aria-label={t("Choose round","Odaberi kolo")}>{meta.pots.filter(p=>p.slot>0).map(p=><button className={s.button} key={p.nodeId} aria-pressed={activeRound===p.slot} onClick={()=>{setActiveRound(p.slot);setCopyTargets([]);setCopyPreview(false);setCategoryId("");}}>{c.root.children.find(n=>n.id===p.nodeId)!.name}</button>)}</div></>:<p>{t("Choose which season achievements receive part of the league pot. Participation can share by contribution or reward the highest totals.","Odaberite sezonska postignuća za nagrade lige. Nagrade za sudjelovanje dijele se prema doprinosu ili najvećim ukupnim rezultatima.")}</p>}
        <div className={g.sectionHeading}><h3>{potNode.name}</h3><strong>{amount(potNode.id)} test MON · {sum(potNode)}%</strong></div>
        {props.campaign?<details key={pot.nodeId} className={g.details} open={potNode.children.length===0?true:undefined}><summary>{t("Add rewards","Dodaj nagrade")}</summary><SponsorTargets configuration={c} potId={pot.nodeId} catalogue={catalogue} hr={hr} disabled={disabled} onChange={onChange}/></details>:null}
        {potNode.children.length>1?<button className={s.button} disabled={disabled} onClick={()=>editNode(pot.nodeId,n=>({...n,children:n.children.map((child,i)=>({...child,shareBps:presetSetupShares(n.children.length)[i]}))}))}>{t("Split equally","Podijeli jednako")}</button>:null}
        {potNode.children.map(n=>{const rule=meta.groups.find(v=>v.nodeId===n.id)!;const category=catalogue?.categories.find(cat=>cat.id===n.rule?.source?.categoryId);return <section className={g.reward} key={n.id} aria-label={n.name} id={`guided-group-${n.id}`} tabIndex={-1}>
          <div className={g.sectionHeading}><div><h3>{n.name}</h3></div><button className={s.button} disabled={disabled} onClick={()=>safely(()=>removeGuidedGroup(c,n.id))}>{t("Remove","Ukloni")}</button></div>
          {!isParticipationType(rule.type)&&(!props.campaign||!n.rule?.source)?<label className={s.field}>{t("Official category","Službena kategorija")} · {n.name}<select disabled={disabled||!catalogue||!c.context||pot.slot>0&&!pot.roundId} value={n.rule?.source?.categoryId??""} onChange={e=>{if(catalogue)safely(()=>connectGuidedGroup(c,n.id,e.target.value||null,catalogue));}}><option value="">{t("Choose a category…","Odaberite kategoriju…")}</option>{catalogue?guidedCategories(catalogue,pot.roundId,rule.type).map(cat=><option key={cat.id} value={cat.id}>{cat.competitionName} · {cat.name}</option>):null}</select></label>:null}
          <div className={g.controls}>{percent(`${n.name} ${t("budget","fond")} %`,n.shareBps,v=>editNode(n.id,n=>({...n,shareBps:v})))}<strong>{amount(n.id)} test MON</strong>
          {isParticipationType(rule.type)?<><label className={s.field}>{t("Distribution","Raspodjela")}<select disabled={disabled} value={rule.method} onChange={e=>safely(()=>changeGuidedMethod(c,n.id,e.target.value as GuidedRewardGroup["method"]))}><option value="proportional">{t("Share by contribution","Podijeli prema doprinosu")}</option><option value="ranked">{t("Reward highest totals","Nagradi najveće rezultate")}</option></select></label><label className={s.field}>{t("Minimum completed rounds","Najmanje završenih kola")}<select disabled={disabled} value={rule.minimumFinishes} onChange={e=>editGroup(n.id,{minimumFinishes:Number(e.target.value),eligibilityApproved:false})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label></>:null}
          {rule.method==="ranked"?<SponsorPrizeEditor name={n.name} shares={n.rule!.sharesBps} slots={preview?.rows.find(r=>r.id===n.id)?.slots??[]} disabled={disabled} hr={hr} onChange={sharesBps=>editNode(n.id,n=>({...n,rule:{...n.rule!,sharesBps}}))}/>:null}</div>
          <details className={g.details}><summary>{t("Rules & prize breakdown","Pravila i iznosi nagrada")}</summary><p>{isParticipationType(rule.type)?t("One approved finish per athlete per round. Completed course distance counts; club distance follows the represented club in each race. All eligible members contribute.","Jedan odobren završetak po sportašu u kolu. Broji se završena udaljenost staze; klupski kilometri pripadaju klubu zastupanom u toj utrci. Doprinose svi prihvatljivi članovi."):category?`${category.competitionName} · ${category.name}`:t("Connect this group's official category before finishing setup.","Povežite službenu kategoriju ove grupe prije dovršetka.")}</p>
          {rule.method==="ranked"?<><p className={s.small}>{t("Ties share the combined prizes for occupied places. A tie can create more recipients than prize positions.","Izjednačeni dijele zbroj nagrada zauzetih mjesta. Broj primatelja može biti veći od broja nagrađenih mjesta.")}</p><div className={s.tableWrap}><table className={s.table}><thead><tr><th>{t("Place","Mjesto")}</th><th>%</th><th>test MON</th></tr></thead><tbody>{n.rule!.sharesBps.map((v,i)=><tr key={i}><td>{i+1}</td><td>{percent(`${n.name} #${i+1} %`,v,v=>editNode(n.id,n=>({...n,rule:{...n.rule!,sharesBps:n.rule!.sharesBps.map((old,j)=>j===i?v:old)}})))}</td><td>{setupAmount(preview?.rows.find(r=>r.id===n.id)?.slots[i]??null,hr)}</td></tr>)}</tbody></table></div></>:<p>{t("Each eligible recipient receives the pool × their verified contribution ÷ all eligible contributions. There is no winner limit.","Svaki prihvatljivi primatelj dobiva fond × svoj potvrđeni doprinos ÷ sve prihvatljive doprinose. Broj dobitnika nije ograničen.")}</p>}
          <label className={g.check}><input type="checkbox" disabled={disabled||!c.context||!isParticipationType(rule.type)&&!n.rule?.source} checked={rule.eligibilityApproved} onChange={e=>editGroup(n.id,{eligibilityApproved:e.target.checked})}/>{t("I reviewed this group's eligibility and counting rules","Pregledao/la sam uvjete i pravila brojanja ove grupe")}</label></details>
        </section>;})}
        {!potNode.children.length&&catalogue?<p className={s.small}>{t("No rewards selected.","Nema odabranih nagrada.")}</p>:null}
        {!props.campaign?<div className={g.addGroup}><label className={s.field}>{t("Reward type","Vrsta nagrade")}<select value={addType} disabled={disabled} onChange={e=>{setAddType(e.target.value as GuidedRewardType);setCategoryId("");}}>{GUIDED_REWARD_TYPES.filter(type=>step===4||!isParticipationType(type)).map(type=><option key={type} value={type}>{labels[type]}</option>)}</select></label>{!isParticipationType(addType)?<label className={s.field}>{t("Official category","Službena kategorija")}<select value={categoryId} disabled={disabled||!catalogue} onChange={e=>setCategoryId(e.target.value)}><option value="">{t("Choose a category…","Odaberite kategoriju…")}</option>{options.map(cat=><option key={cat.id} value={cat.id}>{cat.competitionName} · {cat.name}</option>)}</select></label>:null}<button className={s.primary} disabled={disabled||step===3&&!pot.roundId||!isParticipationType(addType)&&!options.some(cat=>cat.id===categoryId)||isParticipationType(addType)&&meta.groups.some(v=>v.type===addType)} onClick={()=>safely(()=>addGuidedGroup(c,pot.nodeId,addType,()=>crypto.randomUUID(),options.find(cat=>cat.id===categoryId)??null,hr))}>{t("Add reward group","Dodaj grupu nagrada")}</button></div>:null}
        {potNode.children.length>0&&sum(potNode)!==100?<p className={s.notice}>{`${sum(potNode)}% ${t("allocated · needs 100%","raspoređeno · potrebno 100%")}`}</p>:null}
        {step===3&&potNode.children.length>0?<details className={g.details}><summary>{t("Copy these settings to other rounds","Kopiraj postavke u druga kola")}</summary><p>{t("Only selected rounds change. Pot amounts stay the same. Existing groups in those rounds will be replaced.","Mijenjaju se samo odabrana kola. Iznosi fondova ostaju isti. Postojeće grupe u tim kolima bit će zamijenjene.")}</p>{meta.pots.filter(p=>p.slot>0&&p.slot!==activeRound).map(p=><label key={p.nodeId} className={g.check}><input type="checkbox" disabled={disabled} checked={copyTargets.includes(p.nodeId)} onChange={e=>{setCopyPreview(false);setCopyTargets(ids=>e.target.checked?[...ids,p.nodeId]:ids.filter(id=>id!==p.nodeId));}}/>{c.root.children.find(n=>n.id===p.nodeId)!.name} · {c.root.children.find(n=>n.id===p.nodeId)!.children.length} → {potNode.children.length} {t("groups","grupa")}</label>)}{copyPreview?<div className={s.notice}><p>{t("Confirm replacement in the selected rounds. Review their eligibility again after copying.","Potvrdite zamjenu u odabranim kolima. Nakon kopiranja ponovno pregledajte uvjete.")}</p><button className={s.primary} disabled={disabled||!catalogue} onClick={()=>{if(catalogue)safely(()=>copyGuidedRound(c,pot.nodeId,copyTargets,catalogue,()=>crypto.randomUUID()));setCopyPreview(false);}}>{t("Apply to selected rounds","Primijeni na odabrana kola")}</button></div>:<button className={s.button} disabled={disabled||!copyTargets.length} onClick={()=>setCopyPreview(true)}>{t("Preview copy","Pregledaj kopiranje")}</button>}</details>:null}
        {step===4&&selection&&catalogue?<details className={g.details}><summary>{t("Organizer data review","Organizatorska provjera podataka")}</summary><Suspense fallback={<p>{t("Loading…","Učitavanje…")}</p>}><Metrics selection={selection} hr={hr} onReviewUnsavedChange={setLeagueReviewUnsaved}/></Suspense></details>:null}
      </>:null}
      {step===5?<><p className={s.small}>{t("Save your choices. Funding comes later.","Spremite odabir. Financiranje slijedi kasnije.")}</p><div className={g.potGrid}>{c.root.children.map(n=><div className={g.pot} key={n.id}><h3>{n.name}</h3><strong>{amount(n.id)} test MON</strong><p>{n.children.length} {t("reward groups","grupa nagrada")} · {sum(n)}%</p><ul>{n.children.map(child=><li key={child.id}>{child.name} · {amount(child.id)} test MON · {meta.groups.find(v=>v.nodeId===child.id)?.method==="proportional"?t("By contribution","Prema doprinosu"):`Top ${child.rule!.sharesBps.length}`}</li>)}</ul></div>)}</div><details className={g.details}><summary>{t("Reward rules & claim deadline","Pravila i rok preuzimanja")}</summary><RewardSetupPolicy hr={hr} policy={c.policy} disabled={disabled} onChange={policy=>onChange({...c,policy})}/></details><ul className={g.checklist}>{(["event","distribution","sources"] as const).map(key=><li key={key}>{readiness.includes(key)?"○":"✓"} {key==="event"?t("League and all five rounds connected","Liga i svih pet kola povezani"):key==="distribution"?t("All pots and prize distributions total 100%","Svi fondovi i raspodjele iznose 100%"):t("Reward categories and eligibility reviewed","Pregledane kategorije i uvjeti nagrada")}</li>)}</ul><button className={s.primary} disabled={!props.canSave||disabled||!preview||readiness.length>0} onClick={props.onFinish}>{props.busy?t("Saving…","Spremanje…"):t("Finish setup → Review awards","Dovrši → Pregledaj nagrade")}</button></>:null}
    </section>
    {(chartVisible||!props.campaign&&step===5)&&step>1?<div className={g.overview}><RewardSetupChart initialShowPrizes={false} root={c.root} selected={selectedNode.id} selectedRank={rank} rows={preview?.rows??[]} onSelect={(id,place)=>{setSelected(id);setRank(place??null);}} hr={hr}/><section className={`${s.card} ${g.body}`} id="reward-setup-inspector"><span className={s.eyebrow}>{t("Selected allocation","Odabrana raspodjela")}</span><h3>{selectedNode.name}{rank!==null?` · #${rank}`:""}</h3><strong>{rank===null?amount(selectedNode.id):setupAmount(preview?.rows.find(r=>r.id===selectedNode.id)?.slots[rank-1]??null,hr)} test MON</strong>{group?<p>{labels[group.type]} · {group.method==="proportional"?t("Share by contribution","Podijeli prema doprinosu"):`Top ${selectedNode.rule!.sharesBps.length}`}</p>:null}<p className={s.small}>{t("The chart follows your form settings. Open the corresponding step to change this allocation.","Grafikon prati postavke obrasca. Otvorite odgovarajući korak za izmjenu.")}</p><button className={s.button} onClick={()=>{if(group&&selectedPot){setActiveRound(selectedPot.slot||1);go(selectedPot.slot===0?4:3);}else go(2);requestAnimationFrame(()=>{const target=document.getElementById(group?`guided-group-${selected}`:"setup-workflow");target?.focus({preventScroll:true});target?.scrollIntoView?.({block:"start"});});}}>{t("Open settings","Otvori postavke")}</button></section></div>:null}
    <footer className={g.footer}><button className={s.button} disabled={stepIndex===0||reviewUnsaved} onClick={()=>go(stepOrder[stepIndex-1])}>{t("Back","Natrag")}</button><span>{props.saveStatus}</span>{stepIndex<stepOrder.length-1?<button className={s.primary} disabled={reviewUnsaved||props.campaign&&step===1&&!c.context} onClick={()=>go(stepOrder[stepIndex+1])}>{t("Continue","Nastavi")} →</button>:null}</footer>
    </>}
  </article>;
}
