import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpDown,Clock3} from 'lucide-react';
import {PUBLIC_REWARD_PAGE_SIZE,type PublicRewardPage} from '@raceson/domain/rewards/public-campaign';
import {readPublicRewards} from '../data/publicCampaign';
import {setupAmount} from '../model/setupAmount';
import s from './Podium.module.css';
import styles from './PublicRewardTable.module.css';
export default function PublicRewardTable({id,slot,hr,refresh,title,subtitle}:{id:string;slot:number;hr:boolean;refresh:number;title?:string;subtitle?:string}) {
 const t=(en:string,local:string)=>hr?local:en;
 const [page,setPage]=useState<PublicRewardPage|null>(null),[busy,setBusy]=useState(true),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all');
 const [offset,setOffset]=useState(0),[sort,setSort]=useState<'reward'|'amount'>('reward'),[direction,setDirection]=useState<'asc'|'desc'>('asc');
 useEffect(()=>{const abort=new AbortController();setBusy(true);setFailed(false);setPage(null);
  void readPublicRewards(id,slot,offset,sort,direction,abort.signal).then(p=>{if(!abort.signal.aborted)setPage(p);}).catch(()=>{if(!abort.signal.aborted)setFailed(true);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});
  return()=>abort.abort();
 },[id,slot,offset,sort,direction,refresh,retry]);
 const changeSort=(key:'reward'|'amount')=>{setOffset(0);setSort(key);setDirection(key===sort?(direction==='asc'?'desc':'asc'):key==='amount'?'desc':'asc');};
 const label=page?.availability==='open'?t('Claims are open. Each recipient must claim their reward from My rewards.','Preuzimanje je otvoreno. Svaki primatelj preuzima svoju nagradu na stranici Moje nagrade.'):
 page?.availability==='paused'?t('Claims are paused. Confirmed payments remain visible below.','Preuzimanje je pauzirano. Potvrđene isplate vidljive su u nastavku.'):
 page?.availability==='closed'?t('The claim window is closed. Unclaimed rewards are not payments.','Rok za preuzimanje je zatvoren. Nepreuzete nagrade nisu isplate.'):
 t('Awards are prepared. Claims open after the remaining review and controller steps.','Nagrade su pripremljene. Preuzimanje se otvara nakon pregleda i preostalih koraka kontrolera.');
 const filtered=page?.rows.filter(row=>(status==='all'||row.status===status)&&`${row.id} ${row.number} ${row.kind}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))??[];
 return <section aria-label={t('Individual rewards','Pojedinačne nagrade')} aria-busy={busy}>
  <div className={styles.heading}><div><h2>{title??t('Rewards','Nagrade')}{page?<span className={styles.count} aria-label={`${page.total} ${t('rewards','nagrade')}`}> {page.total}</span>:null}</h2>{subtitle?<p className={styles.subtitle}>{subtitle}</p>:null}</div>{!title?<Link to="/athlete/rewards" className={s.back}>{t('Claim my rewards →','Preuzmi moje nagrade →')}</Link>:null}</div>
  {busy?<p className={styles.loading} role="status">{t('Checking reward status…','Provjera stanja nagrada…')}</p>:failed?<div className={s.notice} role="alert"><p>{t('Reward status could not be verified. No payment status is assumed.','Stanje nagrada nije moguće provjeriti. Stanje isplate nije pretpostavljeno.')}</p><button className={s.secondary} onClick={()=>setRetry(n=>n+1)}>{t('Retry reward status','Ponovi provjeru nagrada')}</button></div>:page?.total===0?<div className={styles.empty}><Clock3 size={22} aria-hidden="true"/><div><strong>{t('No individual rewards yet','Pojedinačne nagrade još nisu dostupne')}</strong><p>{t('Awaiting approved results and reward allocation. Saved category budgets are below.','Čeka odobrene rezultate i raspodjelu nagrada. Spremljeni fondovi kategorija su u nastavku.')}</p></div></div>:page?<>
  <details className={styles.guidance}><summary>{page.availability==='open'?t('Claims open','Preuzimanje otvoreno'):page.availability==='paused'?t('Claims paused','Preuzimanje pauzirano'):page.availability==='closed'?t('Claims closed','Preuzimanje zatvoreno'):t('Awaiting review','Čeka pregled')}</summary><p>{label}</p></details>
  <div className={styles.filters} role="search" aria-label={t('Reward ledger filters','Filtri nagrada')}><label><span className="sr-only">{t('Search this page','Pretraži ovu stranicu')}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search reference or number (this page)','Pretraži oznaku ili broj (ovu stranicu)')}/></label><label><span className="sr-only">{t('Status on this page','Stanje na ovoj stranici')}</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('All statuses','Sva stanja')}</option><option value="planned">{t('Planned','Planirano')}</option><option value="unclaimed">{t('Not claimed','Nije preuzeto')}</option><option value="claimed">{t('Claimed','Preuzeto')}</option></select></label><label><span className="sr-only">{t('Sort ledger','Poredaj nagrade')}</span><select value={`${sort}-${direction}`} onChange={e=>{const [key,order]=e.target.value.split('-');setOffset(0);setSort(key as 'reward'|'amount');setDirection(order as 'asc'|'desc');}}><option value="reward-asc">{t('Sort: reference','Poredak: oznaka')}</option><option value="reward-desc">{t('Sort: reference descending','Poredak: oznaka silazno')}</option><option value="amount-desc">{t('Sort: amount high–low','Poredak: iznos silazno')}</option><option value="amount-asc">{t('Sort: amount low–high','Poredak: iznos uzlazno')}</option></select></label>{query||status!=='all'?<button className={s.secondary} onClick={()=>{setQuery('');setStatus('all');}}>{t('Clear filters','Očisti filtre')}</button>:null}</div>
  {query||status!=='all'?<p role="status" className={s.muted}>{t(`${filtered.length} matching rewards on this page of ${page.rows.length}. Filters do not search other pages.`,`${filtered.length} odgovarajućih nagrada od ${page.rows.length} na ovoj stranici. Filtri ne pretražuju druge stranice.`)}</p>:null}
  <div className={`${s.scroll} ${styles.scroll}`}><table className={`${s.table} ${styles.table}`}><caption className="sr-only">{t('Awards and claim status','Nagrade i stanje preuzimanja')}</caption><thead><tr>
  <th scope="col" aria-sort={sort==='reward'?(direction==='asc'?'ascending':'descending'):'none'}><button disabled={busy} onClick={()=>changeSort('reward')}>{t('Reference','Oznaka')}<ArrowUpDown size={14}/></button></th>
  <th scope="col">{t('Reward','Nagrada')}</th>
  <th scope="col" aria-sort={sort==='amount'?(direction==='asc'?'ascending':'descending'):'none'}><button disabled={busy} onClick={()=>changeSort('amount')}>{t('Amount','Iznos')}<ArrowUpDown size={14}/></button></th>
  <th scope="col">{t('Status','Stanje')}</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><th scope="row"><span className={styles.reference} title={row.id}>{row.id.slice(0,10)}…{row.id.slice(-6)}</span></th><td>{row.kind==='athlete'?t('Athlete reward','Nagrada sportaša'):t('Club reward','Nagrada kluba')} {row.number}</td><td>{setupAmount(BigInt(row.amountWei),hr)} <small>test MON</small></td><td><span className={row.status==='claimed'?styles.claimed:styles.pending}>{row.status==='claimed'?t('Claimed','Preuzeto'):row.status==='planned'?t('Planned','Planirano'):t('Not claimed','Nije preuzeto')}</span></td></tr>)}</tbody></table></div>
  <div className={styles.footer}><span>{t('Showing','Prikaz')} {Math.min(offset+1,page.total)}–{Math.min(offset+page.rows.length,page.total)} {t('of','od')} {page.total}</span>{page.total>PUBLIC_REWARD_PAGE_SIZE?<div><button className={s.secondary} disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-PUBLIC_REWARD_PAGE_SIZE))}>{t('Previous','Prethodno')}</button><button className={s.secondary} disabled={offset+PUBLIC_REWARD_PAGE_SIZE>=page.total} onClick={()=>setOffset(n=>n+PUBLIC_REWARD_PAGE_SIZE)}>{t('Next','Sljedeće')}</button></div>:null}</div>
  <details className={styles.note}><summary>{t('Verification details','Detalji provjere')}</summary><p>{t('Public reward references protect recipient account details. “Claimed” means the contract confirms payment.','Javne oznake nagrada štite podatke računa primatelja. „Preuzeto” znači da ugovor potvrđuje isplatu.')}<br/>{t('Verified','Provjereno')} {new Date(Number(page.blockTimestamp)*1000).toLocaleString(hr?'hr-HR':'en-GB')} · {t('Finalized block','Finalizirani blok')} {page.blockNumber}</p></details>
  </>:null}
 </section>;
}
