import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import type { PublicRewardProgramme } from "@raceson/domain/rewards/public-report";
import { useI18n } from "@/shared/i18n/I18nContext";
import { publicAllocationRows, sortAllocationRows, type AllocationSort } from "../model/publicAllocationTable";
import { ReportAmount } from "./PublicReportSummary";
import { rewardPoolLabel } from "../model/prizeDisplay";
import styles from "./RewardWorkspace.module.css";
import ui from "../screens/RewardCatalogue.module.css";

export default function PublicAllocationTable({programme,poolKey,title}:{programme:PublicRewardProgramme;poolKey?:string;title?:string}) {
  const {locale}=useI18n(),hr=locale==="hr";
  const [search,setSearch]=useState(""),[kind,setKind]=useState("all"),[payment,setPayment]=useState("all"),[sort,setSort]=useState<{key:AllocationSort;descending:boolean}>({key:"position",descending:false});
  const allocations=useMemo(()=>publicAllocationRows(programme,poolKey),[programme,poolKey]);
  const rows=sortAllocationRows(allocations.filter(r=>r.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())&&(kind==="all"||r.kind===kind)&&(payment==="all"||(payment==="paid"?r.payment==="paid":r.payment!=="paid"))),sort.key,sort.descending);
  const columns:Array<[AllocationSort,string]>=[["position",hr?"Mjesto":"Position"],["name",hr?"Primatelj":"Recipient"],["potName",hr?"Fond utrke / lige":"Race pot"],["poolKey",hr?"Dio fonda":"Split"],["category",hr?"Kategorija":"Category"],["share",hr?"Udio mjesta":"Prize share"],["slotWei",hr?"Iznos za mjesto":"Position allocation"],["amountWei",hr?"Nagrada":"Reward"],["allocation",hr?"Dodjela":"Allocation"],["claim",hr?"Preuzimanje":"Claim"],["payment",hr?"Isplata":"Payment"],["transactionHash",hr?"Potvrda":"Receipt"]];
  return <section aria-label={hr?"Odobrene nagrade":"Approved awards"}>
    <header className={ui.splitHeading}><h2>{title??(hr?"Raspodjela nagrada":"Reward distribution")}</h2><p>{hr?"Plasman i udio vrijede unutar kategorije. Iznos za mjesto je nagradno mjesto; nagrada uključuje podjelu izjednačenih plasmana. Zahtjev i isplata odnose se na objedinjenu nagradu iz fonda.":"Positions and prize shares are within each category. Position allocation is the prize slot; Reward reflects ties. Claim and payment refer to the combined pot award."}</p></header>
    <div className={ui.filters}><input type="search" aria-label={hr?"Pretraži primatelje":"Search recipients"} placeholder={hr?"Ime sportaša ili kluba…":"Athlete or club name…"} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={hr?"Vrsta primatelja":"Recipient type"} value={kind} onChange={e=>setKind(e.target.value)}><option value="all">{hr?"Svi primatelji":"All recipients"}</option><option value="athlete">{hr?"Sportaši":"Athletes"}</option><option value="club">{hr?"Klubovi":"Clubs"}</option></select><select aria-label={hr?"Status isplate":"Payment status"} value={payment} onChange={e=>setPayment(e.target.value)}><option value="all">{hr?"Sve isplate":"All payments"}</option><option value="paid">{hr?"Isplaćeno":"Paid"}</option><option value="unpaid">{hr?"Čeka isplatu":"Awaiting payment"}</option></select></div>
    <div className={styles.scroll} tabIndex={0} role="region" aria-label={hr?"Tablica raspodjele":"Distribution table"}><table className={`${styles.table} ${ui.table} ${ui.allocationTable}`}><caption className={ui.tableCaption}>{title??(hr?"Odobrene nagrade":"Approved awards")} · test MON</caption><thead><tr>{columns.map(([key,label])=><th key={key} scope="col" aria-sort={sort.key===key?(sort.descending?"descending":"ascending"):"none"}><button className={ui.sortHeader} onClick={()=>setSort({key,descending:sort.key===key?!sort.descending:false})}>{label}<span aria-hidden="true">{sort.key===key?(sort.descending?"↓":"↑"):"↕"}</span></button></th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>
      <td>{r.position??"—"}</td><th scope="row">{r.name}</th><td><Link to={`/rewards/programmes/${programme.id}/pots/${r.potId}?branch=${encodeURIComponent(`pot:${r.potId}:${r.poolKey}`)}`}>{r.potName}</Link></td><td>{rewardPoolLabel(r.poolKey,hr)}</td><td>{r.category||"—"}</td><td>{r.share===null?"—":`${r.share}%`}</td><td>{r.slotWei===null?"—":<ReportAmount value={r.slotWei}/>}</td><td><ReportAmount value={r.amountWei}/></td><td>{hr?"Dodijeljeno":"Awarded"}</td><td>{r.claim==="submitted"?(hr?"Zahtjev predan":"Claim submitted"):(hr?"Nije zatraženo":"Not claimed")}</td><td><span className={r.payment==="paid"?ui.paid:ui.pending}>{r.payment==="paid"?(hr?"Isplaćeno":"Paid"):r.payment==="processing"?(hr?"U obradi":"Processing"):(hr?"Čeka isplatu":"Awaiting payment")}</span></td><td>{r.transactionHash?<a className={styles.textAction} href={`https://testnet.monadvision.com/tx/${r.transactionHash}`} target="_blank" rel="noreferrer">{hr?"Potvrda ↗":"Receipt ↗"}</a>:"—"}</td>
    </tr>)}</tbody>{!rows.length?<tfoot><tr><td colSpan={columns.length} className={ui.empty}>{hr?"Nema pronađenih primatelja.":"No matching recipients."}</td></tr></tfoot>:null}</table></div>
    <p className={styles.smallNote}>{hr?"Sudjelovanje prema udaljenosti nema plasman ni nagradno mjesto. Iznosi su zaokruženi na četiri decimale.":"Distance participation has no finishing position or prize slot. Amounts are rounded to four decimals."}</p>
  </section>;
}
