import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpDown,ArrowUp,ArrowDown,Clock3} from 'lucide-react';
import {PUBLIC_REWARD_PAGE_SIZE} from '@raceson/domain/rewards/public-campaign';
import {usePublicCampaignRewards,type PublicCampaignRewards} from '../model/usePublicCampaignRewards';
import {sortPublicRewards,type RewardSort} from '../model/publicDistribution';
import {publicAmount as setupAmount} from '../model/publicAmount';
import s from './Podium.module.css';
import styles from './PublicRewardTable.module.css';
export default function PublicRewardTable({id,slot,hr,refresh,title,subtitle,rewards}:{id:string;slot:number;hr:boolean;refresh:number;title?:string;subtitle?:string;rewards?:PublicCampaignRewards}) {
 const t=(en:string,local:string)=>hr?local:en;
 const ownRewards=usePublicCampaignRewards(id,slot,refresh,!rewards);
 const {page,busy,failed,retry}=rewards??ownRewards;
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all');
 const [offset,setOffset]=useState(0),[sort,setSort]=useState<RewardSort>('reference'),[direction,setDirection]=useState<'asc'|'desc'>('asc');
 const changeSort=(key:RewardSort)=>{setOffset(0);setSort(key);setDirection(key===sort?(direction==='asc'?'desc':'asc'):key==='amount'?'desc':'asc');};
 const label=page?.availability==='open'?t('Claims are open. Each recipient must claim their reward from My rewards.','Preuzimanje je otvoreno. Svaki primatelj preuzima svoju nagradu na stranici Moje nagrade.'):
 page?.availability==='paused'?t('Claims are paused. Confirmed payments remain visible below.','Preuzimanje je pauzirano. Potvrđene isplate vidljive su u nastavku.'):
 page?.availability==='closed'?t('The claim window is closed. Unclaimed rewards are not payments.','Rok za preuzimanje je zatvoren. Nepreuzete nagrade nisu isplate.'):
 t('Awards are prepared. Claims open after the remaining review and controller steps.','Nagrade su pripremljene. Preuzimanje se otvara nakon pregleda i preostalih koraka kontrolera.');
 const filtered=sortPublicRewards(page?.rows.filter(row=>(status==='all'||row.status===status)&&`${row.id} ${row.number} ${row.kind} ${row.breakdown?.map(b=>b.category).join(' ')??''}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))??[],sort,direction==='desc',hr);
 const visible=filtered.slice(offset,offset+PUBLIC_REWARD_PAGE_SIZE);
 const columns:[RewardSort,string][]=[['reference',t('Reference','Oznaka')],['reward',t('Reward / category','Nagrada / kategorija')],['amount',t('Amount','Iznos')],['status',t('Status','Stanje')]];
 return <section aria-label={t('Individual rewards','Pojedinačne nagrade')} aria-busy={busy}>
  <div className={styles.heading}><div><h2>{title??t('Rewards','Nagrade')}{page?<span className={styles.count} aria-label={`${page.total} ${t('rewards','nagrade')}`}> {page.total}</span>:null}</h2>{subtitle?<p className={styles.subtitle}>{subtitle}</p>:null}</div>{!title?<Link to="/athlete/rewards" className={s.back}>{t('Claim my rewards →','Preuzmi moje nagrade →')}</Link>:null}</div>
  {busy?<p className={styles.loading} role="status">{t('Checking reward status…','Provjera stanja nagrada…')}</p>:failed?<div className={s.notice} role="alert"><p>{t('Reward status could not be verified. No payment status is assumed.','Stanje nagrada nije moguće provjeriti. Stanje isplate nije pretpostavljeno.')}</p><button className={s.secondary} onClick={retry}>{t('Retry reward status','Ponovi provjeru nagrada')}</button></div>:page?.total===0?<div className={styles.empty}><Clock3 size={22} aria-hidden="true"/><div><strong>{t('No individual rewards yet','Pojedinačne nagrade još nisu dostupne')}</strong><p>{t('Awaiting approved results and reward allocation. Saved category budgets are below.','Čeka odobrene rezultate i raspodjelu nagrada. Spremljeni fondovi kategorija su u nastavku.')}</p></div></div>:page?<>
  <details className={styles.guidance}><summary>{page.availability==='open'?t('Claims open','Preuzimanje otvoreno'):page.availability==='paused'?t('Claims paused','Preuzimanje pauzirano'):page.availability==='closed'?t('Claims closed','Preuzimanje zatvoreno'):t('Awaiting review','Čeka pregled')}</summary><p>{label}</p></details>
  <div className={styles.filters} role="search" aria-label={t('Reward ledger filters','Filtri nagrada')}><label><span className="sr-only">{t('Search rewards','Pretraži nagrade')}</span><input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder={t('Search reference or category…','Pretraži oznaku ili kategoriju…')}/></label><label><span className="sr-only">{t('Reward status','Stanje nagrade')}</span><select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="all">{t('All statuses','Sva stanja')}</option><option value="planned">{t('Planned','Planirano')}</option><option value="unclaimed">{t('Unclaimed','Nepreuzeto')}</option><option value="claimed">{t('Claimed','Preuzeto')}</option></select></label><label><span className="sr-only">{t('Sort ledger','Poredaj nagrade')}</span><select value={`${sort}-${direction}`} onChange={e=>{const [key,order]=e.target.value.split('-');setOffset(0);setSort(key as RewardSort);setDirection(order as 'asc'|'desc');}}><option value="reference-asc">{t('Sort: reference','Poredak: oznaka')}</option><option value="reference-desc">{t('Sort: reference descending','Poredak: oznaka silazno')}</option><option value="amount-desc">{t('Sort: amount high–low','Poredak: iznos silazno')}</option><option value="amount-asc">{t('Sort: amount low–high','Poredak: iznos uzlazno')}</option><option value="reward-asc">{t('Sort: category A–Z','Poredak: kategorija A–Ž')}</option><option value="reward-desc">{t('Sort: category Z–A','Poredak: kategorija Ž–A')}</option><option value="status-asc">{t('Sort: status A–Z','Poredak: stanje A–Ž')}</option><option value="status-desc">{t('Sort: status Z–A','Poredak: stanje Ž–A')}</option></select></label>{query||status!=='all'?<button className={s.secondary} onClick={()=>{setQuery('');setStatus('all');setOffset(0);}}>{t('Clear filters','Očisti filtre')}</button>:null}</div>
  {query||status!=='all'?<p role="status" className={s.muted}>{t(`${filtered.length} matching rewards of ${page.total}.`,`${filtered.length} odgovarajućih nagrada od ${page.total}.`)}</p>:null}
  <div className={`${s.scroll} ${styles.scroll}`}><table className={`${s.table} ${styles.table}`}><caption className="sr-only">{t('Awards and claim status','Nagrade i stanje preuzimanja')}</caption><thead><tr>
  {columns.map(([key,label])=><th key={key} scope="col" aria-sort={sort===key?(direction==='asc'?'ascending':'descending'):'none'}><button disabled={busy} onClick={()=>changeSort(key)}>{label}{sort===key?(direction==='asc'?<ArrowUp size={14}/>:<ArrowDown size={14}/>):<ArrowUpDown size={14}/>}</button></th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.id}><th scope="row"><span className={styles.reference} title={row.id}>{row.id.slice(0,10)}…{row.id.slice(-6)}</span></th><td>{row.breakdown?<span className={styles.categoryLabel}>{row.breakdown.map(b=>`${b.category}${b.place?` · #${b.place}`:''}`).join(' / ')}</span>:null}<span className={styles.rewardLabel}>{row.kind==='athlete'?t('Athlete reward','Nagrada sportaša'):t('Club reward','Nagrada kluba')} {row.number}</span></td><td>{setupAmount(BigInt(row.amountWei),hr)} <small>test MON</small></td><td><span className={row.status==='claimed'?styles.claimed:row.status==='planned'?styles.planned:styles.pending}>{row.status==='claimed'?t('Claimed','Preuzeto'):row.status==='planned'?t('Planned','Planirano'):t('Unclaimed','Nepreuzeto')}</span></td></tr>)}</tbody></table></div>
  {filtered.length===0?<p role="status" className={styles.loading}>{t('No rewards match these filters.','Nema nagrada za odabrane filtre.')}</p>:null}
  <div className={styles.footer}><span>{t('Showing','Prikaz')} {filtered.length?offset+1:0}–{Math.min(offset+visible.length,filtered.length)} {t('of','od')} {filtered.length}</span>{filtered.length>PUBLIC_REWARD_PAGE_SIZE?<div><button className={s.secondary} disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-PUBLIC_REWARD_PAGE_SIZE))}>{t('Previous','Prethodno')}</button><button className={s.secondary} disabled={offset+PUBLIC_REWARD_PAGE_SIZE>=filtered.length} onClick={()=>setOffset(n=>n+PUBLIC_REWARD_PAGE_SIZE)}>{t('Next','Sljedeće')}</button></div>:null}</div>
  <details className={styles.note}><summary>{t('Verification details','Detalji provjere')}</summary><p>{t('Public reward references protect recipient account details. “Claimed” means the contract confirms payment.','Javne oznake nagrada štite podatke računa primatelja. „Preuzeto” znači da ugovor potvrđuje isplatu.')}<br/>{t('Verified','Provjereno')} {new Date(Number(page.blockTimestamp)*1000).toLocaleString(hr?'hr-HR':'en-GB')} · {t('Finalized block','Finalizirani blok')} {page.blockNumber}</p></details>
  </>:null}
 </section>;
}
