import {defaultRewardSetupPolicy,type RewardSetupPolicy as Policy} from '@raceson/domain/rewards/distribution-setup';
import s from './RewardSetup.module.css';
import exact from './SponsorExact.module.css';

export default function RewardSetupPolicy({policy,hr,disabled,onChange,compact=false}:{compact?:boolean;policy:Policy|undefined;hr:boolean;disabled:boolean;onChange:(value:Policy)=>void}){
 const value=policy??defaultRewardSetupPolicy();
 if(compact)return <section className={exact.policy} aria-label={hr?'Rok preuzimanja i povrat':'Claim period and returns'}><h2>{hr?'Rok preuzimanja i uvjeti povrata':'Claim window & return terms'}</h2><div className={exact.policyColumns}><label className={exact.field}>{hr?'Rok preuzimanja (dani)':'Claim window (days)'}<input aria-label={hr?'Rok preuzimanja (dani)':'Claim window (days)'} type="number" min="1" max="3650" step="1" value={value.claimWindowDays} disabled={disabled} onChange={e=>{if(e.target.value!==''&&e.target.validity.valid)onChange({...value,claimWindowDays:Number(e.target.value)});}}/><small className={exact.hint}>{hr?'Nakon otvaranja preuzimanja.':'After claims open.'}</small></label><fieldset className={exact.returns} disabled={disabled}><legend>{hr?'Neiskorištena ili istekla sredstva idu na':'Unused or expired funds go to'}</legend>{(['original_sender','raceson_default'] as const).map(destination=><label key={destination}><input type="radio" name="sponsor-return" value={destination} checked={value.treasuryReturn===destination} onChange={()=>onChange({...value,fewerFinishers:'selected_return',treasuryReturn:destination})}/>{destination==='original_sender'?(hr?'Povrat na novčanik sponzora':'Back to the sponsor wallet'):(hr?'RacesOn riznica':'RacesOn treasury')}</label>)}</fieldset></div><details><summary>{hr?'Ostala pravila nagrađivanja':'Other reward rules'}</summary><p className={exact.hint}>{hr?'Izjednačena mjesta dijele nagrade; više nagrada se zbraja. Zarađene nagrade ostaju rezervirane do isteka roka, uključujući primatelje bez novčanika. Sigurnosne pauze produljuju rok.':'Tied places share prizes; multiple awards add together. Earned awards remain reserved until expiry, including recipients without a wallet. Security pauses extend the deadline.'}</p>{value.fewerFinishers==='raceson_main_treasury'&&value.treasuryReturn==='original_sender'?<p className={exact.hint}>{hr?'Spremljena pravila vraćaju neiskorištena mjesta u RacesOn riznicu.':'Saved rules return unfilled places to the RacesOn treasury.'}</p>:null}</details></section>;

 return <section className={`${s.card} ${s.policyCard}`} aria-label={hr?'Pravila nagrađivanja':'Reward rules'}>
  <header className={s.cardHeader}><div><h2>{hr?'Pravila nagrađivanja i rok preuzimanja':'Reward rules and claim expiry'}</h2><p>{hr?'Ova pravila vrijede za sve grane, sportaše i klubove. Spremaju se uz postavke.':'These rules apply across branches, to athletes and clubs. They are saved with your setup.'}</p></div></header>
  <div className={s.policyBody}>
   <dl className={s.policyRules}>
    <div><dt>{hr?'Više nagrada':'Multiple awards'}</dt><dd>{hr?'Isti primatelj može dobiti ukupnu nagradu i nagradu kategorije.':'A recipient can earn both overall and age-category rewards.'}</dd></div>
    <div><dt>{hr?'Izjednačena mjesta':'Tied places'}</dt><dd>{hr?'Nagrade zauzetih mjesta zbrajaju se i dijele jednako. 15 + 10 → 12,5 svakome.':'Combine occupied-place prizes and split equally. 15 + 10 → 12.5 each.'}</dd></div>
    <div><dt>{hr?'Manje finišera':'Fewer finishers'}</dt><dd>{hr?'Neiskorištena sredstva vraćaju se u glavnu riznicu RacesOn nakon konačnog obračuna.':'Unused finishing-place allocations return to the RacesOn main treasury after final reconciliation.'}</dd></div>
   </dl>
   <div className={s.claimPolicy}>
    <label className={s.field}>{hr?'Rok preuzimanja (dani)':'Claim window (days)'}<input type="number" min="1" max="3650" step="1" value={value.claimWindowDays} disabled={disabled} onChange={e=>{if(e.target.value!==''&&e.target.validity.valid)onChange({...value,claimWindowDays:Number(e.target.value)});}}/></label>
    <span className={s.badge}>{value.claimWindowDays===365?(hr?'1 godina':'1 year'):`${value.claimWindowDays} ${hr?'dana':'days'}`}</span>
    <p className={s.small}>{hr?'Rok počinje otvaranjem preuzimanja, a ne spremanjem postavki. Sigurnosne pauze produljuju rok.':'The clock starts when claims open, not when setup is saved. Security pauses extend the deadline.'}</p>
    <p className={s.small}>{hr?'Zarađene nagrade ostaju rezervirane primatelju do isteka roka, i bez novčanika. Nakon isteka nepreuzeti dio vraća se na odabranu fiksnu adresu riznice.':'Earned rewards remain reserved for their recipient until expiry, including recipients without a wallet. After expiry, the unclaimed amount returns to the selected fixed treasury address.'}</p>
    <label className={s.field}>{hr?'Odredište povrata riznice':'Treasury return destination'}<select value={value.treasuryReturn} disabled={disabled} onChange={e=>onChange({...value,fewerFinishers:'selected_return',treasuryReturn:e.target.value as Policy['treasuryReturn']})}><option value="raceson_default">{hr?'Zadana riznica RacesOn':'RacesOn default treasury'}</option><option value="original_sender">{hr?'Izvorni pošiljatelj':'Original sender'}</option></select></label>
    <p className={s.small}>{hr?'Izvorni pošiljatelj je provjerena adresa koja financira program. Odredište se potvrđuje prije financiranja i nakon toga ostaje fiksno.':'Original sender means the verified address funding the programme. The destination is confirmed before funding and remains fixed afterward.'}</p>
   </div>
   <p className={s.notice}>{hr?'Sprema se izbor odredišta, ne nalog za prijenos. Točnu adresu treba provjeriti prije financiranja.':'This saves a destination choice, not a transfer instruction. The exact address must be verified before funding.'}</p>
  </div>
 </section>;
}
