import {requestLeaguePolicyV3} from "../data/leaguePolicyV3";
import type {LeaguePolicyViewV3} from "@raceson/domain/rewards/league-policy-view-v3";
import {useEffect,useRef,useState} from 'react';
import type {RewardSetupContext,RewardSetupNode,RewardSetupSource} from '@raceson/domain/rewards/distribution-setup';
import type {StoredRewardSnapshot} from '@raceson/domain/rewards/published-preview-v2';
import {previewSetupSource,previewSetupLeagueSource} from '@raceson/domain/rewards/distribution-setup-results';
import {readPublishedPreview} from '../data/publishedPreview';
import type {SetupEventSelection} from './RewardSetupEvent';
import {setupAmount} from '../model/setupAmount';
import {rewardSetupCopy} from '../model/rewardSetupCopy';
import s from './RewardSetup.module.css';
export default function RewardSetupEventSource({node,context,selection,slots,hr,disabled,onChange}:{node:RewardSetupNode;context:RewardSetupContext;selection:SetupEventSelection|null;slots:bigint[];hr:boolean;disabled:boolean;onChange:(source:RewardSetupSource|null)=>void}){
 const [leagueView,setLeagueView]=useState<LeaguePolicyViewV3|null>(null);
 const c=rewardSetupCopy(hr),[option,setOption]=useState(node.rule?.source?`${node.rule.source.roundId??'league'}|${node.rule.source.categoryId}`:''),[snapshot,setSnapshot]=useState<StoredRewardSnapshot|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false),generation=useRef(0);
 useEffect(()=>{const g=generation;return()=>{g.current++;};},[]);
 const workspace=selection?.record.draftId===context.draftId&&selection.workspace.catalogueHash===context.catalogueHash?selection.workspace:null,basis=node.rule?.basis,roundBasis=basis==='race_position'||basis==='club_points'&&(context.roundId!==null||node.rule?.source?.roundId!=null),target=basis==='club_points'?'club':'individual';
 const options=workspace?(roundBasis?workspace.catalogue.rounds.filter(r=>r.status!=='cancelled'&&(!context.roundId||r.id===context.roundId)).flatMap(r=>workspace.catalogue.categories.filter(c=>c.target===target&&r.races.some(race=>race.competitionId===c.competitionId)).map(c=>({value:`${r.id}|${c.id}`,label:`${r.name} · ${c.competitionName} · ${c.name}`}))):context.roundId?[]:workspace.catalogue.categories.filter(c=>c.target===target).map(c=>({value:`league|${c.id}`,label:`${c.competitionName} · ${c.name}`}))):[];
 async function preview(){if(!selection||!workspace)return;const gen=++generation.current;setBusy(true);setFailed(false);setLoaded(false);setSnapshot(null);setLeagueView(null);try{if(node.rule?.source?.roundId===null&&(basis==="league_position"||basis==="club_points")){const view=await requestLeaguePolicyV3(selection.record);if(gen===generation.current){setLeagueView(view);setLoaded(true);}return;}const p=await readPublishedPreview(selection.record,workspace);if(gen===generation.current){setSnapshot(p?.snapshot??null);setLoaded(true);}}catch{if(gen===generation.current)setFailed(true);}finally{if(gen===generation.current)setBusy(false);}}
 const result=loaded&&workspace&&node.rule?.source&&slots.length===node.rule.sharesBps.length?(node.rule.source.roundId===null?previewSetupLeagueSource(node,slots,workspace,leagueView):previewSetupSource(node,slots,workspace,snapshot)):null;
 return <div className={s.source}><p className={s.small}>{context.eventName} · {context.programmeName}</p>{!workspace?<p className={s.notice}>{hr?'Učitajte i potvrdite odabrani događaj iznad.':'Load and confirm the selected event above.'}</p>:<><label className={s.field}>{hr?'Rezultati za ovu grupu':'Results for this group'}<select value={option} disabled={disabled} onChange={e=>{setOption(e.target.value);setLoaded(false);setSnapshot(null);}}><option value="">{c.choose}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><button className={s.button} disabled={disabled||!options.some(o=>o.value===option)} onClick={()=>{const [round,categoryId]=option.split('|');onChange({draftId:context.draftId,roundId:round==='league'?null:round,categoryId,catalogueHash:context.catalogueHash});setLoaded(false);}}>{c.connect}</button></>}
 {node.rule?.source?<><p className={s.success}>{c.connected}</p><button className={s.button} disabled={disabled} onClick={()=>onChange(null)}>{c.disconnect}</button><button className={s.primary} disabled={!workspace||busy} onClick={()=>void preview()}>{busy?c.loading:(hr?'Pregledaj rezultate':'Review results')}</button></>:<p className={s.small}>{c.unconnected}</p>}
 {failed?<p className={s.notice} role="alert">{c.sourceFailed}</p>:null}
 {result?<div><h3>{c.resultPreview}</h3>{result.reason?<p className={s.notice}>{result.reason==='source_changed'?c.sourceChanged:result.reason==='review_required'?c.sourceReview:result.reason==='ambiguous_results'?c.sourceAmbiguous:c.held}</p>:<div className={s.tableWrap}><table className={s.table}><thead><tr><th>{c.rank}</th><th>{c.recipient}</th><th>{c.amount}</th></tr></thead><tbody>{result.awards.map(a=><tr key={a.beneficiaryId}><td>{a.place}</td><td>{a.name??a.beneficiaryId}</td><td>{setupAmount(a.amountWei,hr)}</td></tr>)}</tbody></table></div>}<p className={s.small}>{c.remaining}: {setupAmount(result.unusedWei,hr)} test MON</p><p className={s.small}>{c.sourceSnapshot}</p></div>:null}
 </div>;
}
