import {walletBalanceAmount} from "../model/setupAmount";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {useEffect,useRef,useState} from 'react';
import {formatUnits,parseUnits} from 'viem';
import {decodeSupportSettings,type SupportSettings} from '@raceson/domain/rewards/operations';
import {readSupportSettings,reviewSupportSettings,saveSupportSettings} from '../data/operations';
import s from './RewardOperations.module.css';
import ReceiveTestMon from './ReceiveTestMon';

type Snapshot=Awaited<ReturnType<typeof readSupportSettings>>;
const mon=(wei:string)=>formatUnits(BigInt(wei),18);
function wei(text:string){if(!/^(0|[1-9][0-9]{0,6})(\.[0-9]{1,18})?$/.test(text.trim()))throw Error('amount');return parseUnits(text.trim(),18).toString();}
export default function RewardSupportSettings({area,hr}:{area:'gas'|'support';hr:boolean}){
 const [data,setData]=useState<Snapshot|null>(null),[alert,setAlert]=useState(''),[wallet,setWallet]=useState(''),[limit,setLimit]=useState('0'),[review,setReview]=useState<Awaited<ReturnType<typeof reviewSupportSettings>>|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(false),[saved,setSaved]=useState(false),[reload,setReload]=useState(0);
 const active=useRef(true),flight=useRef(false),requestId=useRef('');
 const t=(en:string,local:string)=>hr?local:en;
 function assign(v:Snapshot){setData(v);setAlert(v.settings.gasAlertWei===null?'':mon(v.settings.gasAlertWei));setWallet(v.settings.supportWallet??'');setLimit(mon(v.settings.supportLimitWei));}
 useEffect(()=>{let current=true;active.current=true;setData(null);setError(false);setReview(null);void readSupportSettings().then(v=>{if(current)assign(v);}).catch(()=>{if(current)setError(true);});return()=>{current=false;active.current=false;};},[reload]);
 async function run(task:()=>Promise<void>){if(flight.current)return;flight.current=true;setBusy(true);setError(false);setSaved(false);try{await task();}catch{if(active.current)setError(true);}finally{flight.current=false;if(active.current)setBusy(false);}}
 let candidate:SupportSettings|null=null;
 try{if(data)candidate=decodeSupportSettings({...data.settings,...(area==='gas'?{gasAlertWei:alert.trim()?wei(alert):null}:{supportWallet:wallet.trim()?wallet.trim().toLowerCase():null,supportLimitWei:wei(limit)})});}catch{/* Invalid inputs cannot be reviewed. */}
 const dirty=!!candidate&&JSON.stringify(candidate)!==JSON.stringify(data?.settings);
 function edited(){setReview(null);setConfirmed(false);setSaved(false);requestId.current='';}
 return <div className={s.support}><section className={s.panel} aria-label={area==='gas'?t('Gas balance alerts','Upozorenja o plinu'):t('Recipient payment support','Podrška isplatama primatelja')}>
 <h2 className={s.srOnly}>{area==='gas'?t('Gas balance alerts','Upozorenja o plinu'):t('Recipient payment support','Podrška isplatama primatelja')}</h2>
 <p>{area==='gas'?t('Pays gas when sponsors create reward contracts. Not part of any prize budget.','Plaća plin kada sponzori stvaraju ugovore za nagrade. Nije dio fonda nagrada.'):t('Record the wallet and limit for recipient payment support. Separate from creation gas and controller authority.','Zabilježite novčanik i ograničenje za podršku isplatama primatelja. Odvojeno od plina za stvaranje i ovlasti kontrolora.')}</p>
 {error&&!review?<p role="alert">{t('Settings could not be confirmed. Reload to check current values, or retry the same save.','Postavke nije moguće potvrditi. Osvježite za provjeru trenutnih vrijednosti ili ponovite isto spremanje.')}</p>:null}
 {saved?<p role="status" className={s.status}>{t('Settings saved. No funds were moved.','Postavke spremljene. Sredstva nisu prenesena.')}</p>:null}
 {!data&&!error?<p role="status">{t('Loading settings…','Učitavanje postavki…')}</p>:null}
 {error?<button className={s.secondary} disabled={busy} onClick={()=>setReload(v=>v+1)}>{t('Reload support settings','Osvježi postavke podrške')}</button>:null}
 {data?<>
 {area==='gas'?<p className={`${s.status} ${data.gas?.low?s.warning:''}`} role="status">{data.gas?<>{data.gas.low?t('Low creation-gas balance','Nisko stanje plina za stvaranje'):t('Creation-gas balance','Stanje plina za stvaranje')}: <strong>{walletBalanceAmount(BigInt(data.gas.balanceWei),hr)} test MON</strong><br/><small>{data.gas.address}</small></>:t('Gas balance is unavailable. Reload to check the current wallet.','Stanje plina nije dostupno. Osvježite za provjeru trenutnog novčanika.')}</p>:null}
 {area==='gas'&&data.gas?<ReceiveTestMon key={data.gas.address} address={data.gas.address} chainId={10143} hr={hr}/>:null}
 <form className={s.form} onSubmit={e=>{e.preventDefault();if(candidate)void run(async()=>{const value=await reviewSupportSettings(data.revision,candidate!);if(active.current){setReview(value);setConfirmed(false);setReason('');requestId.current=crypto.randomUUID();}});}}>
 {area==='gas'?<label className={s.field}>{t('Low-balance alert (test MON)','Upozorenje niskog stanja (test MON)')}<input aria-label={t('Low-balance alert (test MON)','Upozorenje niskog stanja (test MON)')} inputMode="decimal" value={alert} onChange={e=>{setAlert(e.target.value);edited();}} disabled={busy} placeholder={t('Not configured','Nije postavljeno')}/><small>{t('Shown here when the current creation wallet is below this threshold. Leave blank to disable.','Prikazuje se ovdje kada je stanje novčanika za stvaranje ispod praga. Ostavite prazno za isključivanje.')}</small></label>:<><label className={s.field}>{t('Support wallet address','Adresa novčanika za podršku')}<input value={wallet} onChange={e=>{setWallet(e.target.value);edited();}} disabled={busy} autoComplete="off" spellCheck={false} placeholder="0x…" maxLength={42}/></label><label className={s.field}>{t('Support limit (test MON)','Ograničenje podrške (test MON)')}<input inputMode="decimal" value={limit} onChange={e=>{setLimit(e.target.value);edited();}} disabled={busy}/></label><p>{t('This records a support policy. Payments still require their own review and wallet authorization; saving an address does not prove control of it.','Ovo bilježi pravila podrške. Isplate i dalje zahtijevaju zaseban pregled i odobrenje novčanika; spremanje adrese ne potvrđuje kontrolu nad njom.')}</p></>}
 {!candidate?<p role="status">{t('Enter a valid wallet and non-negative amount with up to 18 decimal places. An empty wallet requires a zero support limit.','Unesite valjani novčanik i nenegativan iznos s najviše 18 decimala. Prazan novčanik zahtijeva ograničenje podrške od nula.')}</p>:null}
 <button className={s.primary} disabled={busy||!dirty}>{t('Review change','Pregledaj promjenu')}</button>
 </form>
 {review?<Dialog open onOpenChange={open=>{if(!open&&!busy)setReview(null);}}><DialogContent className={`${s.review} ${s.dialog}`} onInteractOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{if(busy)e.preventDefault();}}><DialogTitle>{area==='gas'?t('Confirm creation gas change','Potvrdi promjenu plina za stvaranje'):t('Confirm recipient payment support change','Potvrdi promjenu podrške isplatama primatelja')}</DialogTitle><DialogDescription>{t('Review the changed settings. Existing contracts keep their original terms.','Pregledajte promijenjene postavke. Postojeći ugovori zadržavaju izvorne uvjete.')}</DialogDescription>{error?<p role="alert">{t('The save could not be confirmed. Retry this exact change, or cancel and reload settings.','Spremanje nije potvrđeno. Ponovite istu promjenu ili odustanite i osvježite postavke.')}</p>:null}<dl>{(area==='gas'?[['gasAlertWei',t('Low-balance alert','Upozorenje niskog stanja')]]:[['supportWallet',t('Support wallet','Novčanik za podršku')],['supportLimitWei',t('Support limit','Ograničenje podrške')]]).map(([key,label])=>{const field=key as keyof SupportSettings,format=(v:string|null)=>v===null?t('Not configured','Nije postavljeno'):field==='supportWallet'?v:`${mon(v)} test MON`;return <div key={key}><dt>{label}</dt><dd>{format(data.settings[field])} → <strong>{format(review.settings[field])}</strong></dd></div>;})}</dl><label className={s.field}>{t('Reason for change','Razlog promjene')}<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} minLength={8} maxLength={500} disabled={busy}/></label><label className={s.confirm}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>{t('I reviewed these settings and understand this does not authorize a transfer.','Pregledao/la sam ove postavke i razumijem da time ne odobravam prijenos.')}</label><div className={s.actions}><button className={s.secondary} disabled={busy} onClick={()=>setReview(null)}>{t('Cancel','Odustani')}</button><button className={s.primary} disabled={busy||!confirmed||reason.trim().length<8} onClick={()=>void run(async()=>{const next=await saveSupportSettings(review,reason.trim(),requestId.current);if(active.current){assign({...next,gas:null});setReview(null);setSaved(true);}})}>{busy?t('Saving…','Spremanje…'):t('Save change','Spremi promjenu')}</button></div></DialogContent></Dialog>:null}
 </>:null}</section>
 {data?<section className={s.audit}><h2>{t('Audit history','Povijest promjena')}</h2><p>{t('Latest 50 changes','Posljednjih 50 promjena')} · {t('revision','revizija')} {data.revision}</p>{data.history.length?<div className={s.table} role="region" aria-label={t('Support settings history','Povijest postavki podrške')} tabIndex={0}><table><thead><tr>{[t('Date','Datum'),t('Changed by','Promijenio/la'),t('Change','Promjena')].map(text=><th key={text}>{text}</th>)}</tr></thead><tbody>{data.history.map(h=><tr key={h.revision}><td><time dateTime={h.changedAt}>{new Date(h.changedAt).toLocaleString(hr?'hr-HR':'en-GB')}</time></td><td>{h.changedBy}</td><td>{h.reason}<details><summary>{t('View settings','Prikaži postavke')}</summary><dl><dt>{t('Gas alert','Upozorenje za plin')}</dt><dd>{h.settings.gasAlertWei===null?'—':`${mon(h.settings.gasAlertWei)} test MON`}</dd><dt>{t('Support wallet','Novčanik za podršku')}</dt><dd>{h.settings.supportWallet??'—'}</dd><dt>{t('Support limit','Ograničenje podrške')}</dt><dd>{mon(h.settings.supportLimitWei)} test MON</dd></dl></details></td></tr>)}</tbody></table></div>:<p>{t('No support settings changes recorded.','Nema zabilježenih promjena postavki podrške.')}</p>}</section>:null}
 </div>;
}
