
import {lazy,Suspense,useEffect,useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '@/lib/auth';
import {type RewardEventCatalogue,type RewardEventSummary} from '@raceson/domain/rewards/setup-event';
import {type RewardDistributionSetup,type RewardSetupContext,type RewardSetupNode} from '@raceson/domain/rewards/distribution-setup';
import {listSetupEvents,readSetupEvent} from '../data/setupEvents';
import RewardSetupEvent,{type SetupEventSelection} from './RewardSetupEvent';
import s from './RewardSetup.module.css';
const LeagueMetrics=lazy(()=>import('./RewardLeagueMetrics'));
const SeasonPicker=lazy(()=>import('../screens/CreateRewardProgramme'));
export default function RewardSetupJourney({step,onStep:goToSetupStep,configuration,disabled,hr,initialProgramme,onChange,onLoaded,selection,onContext}:{step:number;onStep:(step:number)=>void;configuration:RewardDistributionSetup;disabled:boolean;hr:boolean;initialProgramme:string|null;onChange:(c:RewardDistributionSetup)=>void;onLoaded:(s:SetupEventSelection|null)=>void;selection:SetupEventSelection|null;onContext:(c:RewardSetupContext)=>void}){
 const [showSeasons,setShowSeasons]=useState(false),[addedProgramme,setAddedProgramme]=useState<string|null>(null);
 const auth=useAuth(),kind=configuration.programmeKind??(configuration.context||initialProgramme?'league':null);
 const [events,setEvents]=useState<RewardEventSummary[]|null>(null),[catalogue,setCatalogue]=useState<RewardEventCatalogue|null>(null),[search,setSearch]=useState(''),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 const picking=useRef(0),latest=useRef(configuration),blocked=useRef(disabled),commit=useRef(onChange);latest.current=configuration;blocked.current=disabled;commit.current=onChange;
 useEffect(()=>()=>{picking.current++;},[]);
 const missingText=(text:string)=>hr?({'Invalid classification':'Neispravna kategorija','Invalid category eligibility':'Neispravni uvjeti kategorije','Overall ranking is not configured':'Ukupni poredak nije postavljen','Club ranking is not configured':'Klupski poredak nije postavljen','This route has no competitive standings':'Ova ruta nema natjecateljski poredak','Distance is missing':'Udaljenost nije navedena'}[text]??text):text;
 const eventId=configuration.event?.editionId;
 useEffect(()=>{if(!auth.account?.hasOrganizerAccess||kind!=='event')return;let active=true;setFailed(false);void listSetupEvents().then(items=>{if(active)setEvents(items);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[auth.account?.hasOrganizerAccess,kind,retry]);
 useEffect(()=>{if(!eventId||!auth.account?.hasOrganizerAccess){setCatalogue(null);return;}let active=true;setCatalogue(null);setFailed(false);void readSetupEvent(eventId).then(event=>{if(active)setCatalogue(event);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[eventId,auth.account?.hasOrganizerAccess,retry]);
 function chooseType(next:'event'|'league'){picking.current++;if(next===kind)return;if((configuration.context||configuration.event)&&!window.confirm(hr?'Promijeniti izvor? Grane i udjeli ostaju sačuvani; kategorije treba ponovno povezati.':'Change source type? Branches and percentages stay intact; categories will need reconnecting.'))return;const clear=(node:RewardSetupNode):RewardSetupNode=>({...node,children:node.children.map(clear),rule:node.rule?{...node.rule,source:null}:null});onChange({...configuration,version:4,programmeKind:next,event:null,context:null,root:clear(configuration.root)});}
 async function chooseEvent(id:string){if(disabled)return;if(id===eventId){goToSetupStep(3);return;}const generation=++picking.current;if(configuration.event&&configuration.event.editionId!==id&&!window.confirm(hr?'Promijeniti događaj? Grane ostaju, kategorije treba ponovno povezati.':'Change event? Your branches remain; categories will need reconnecting.'))return;setFailed(false);try{const event=await readSetupEvent(id);if(generation!==picking.current||blocked.current)return;commit.current({...latest.current,version:4,programmeKind:'event',context:null,event:{editionId:id,name:event.name.slice(0,100),date:event.date,catalogueHash:event.catalogueHash,choices:[]},root:latest.current.root});setCatalogue(event);goToSetupStep(3);}catch{if(generation===picking.current)setFailed(true);}}
 const league=selection?.workspace,ctx=configuration.context;
 return <>
 <section hidden={step!==1} id="setup-step-1" className={`${s.card} ${s.journeySection}`}><span className={s.eyebrow}>1 · {hr?'Novi program':'Create programme'}</span><h2>{hr?'Što želite nagraditi?':'What are you rewarding?'}</h2><label className={s.field}>{hr?'Naziv programa':'Programme name'}<input value={configuration.name} maxLength={100} disabled={disabled} onChange={e=>onChange({...configuration,name:e.target.value})}/></label><div className={s.typeChoices} role="group" aria-label={hr?'Vrsta programa':'Programme type'}>{(['event','league'] as const).map(type=><button key={type} className={s.typeChoice} aria-pressed={kind===type} disabled={disabled} onClick={()=>chooseType(type)}><strong>{type==='event'?(hr?'Jedan događaj':'Single event'):(hr?'Liga / sezona':'League / season')}</strong><span>{type==='event'?(hr?'Samostalni događaj, bez lige.':'An independent event. No league needed.'):(hr?'Više kola i ukupni poredak.':'Multiple rounds and season standings.')}</span></button>)}</div><button className={s.primary} disabled={disabled||!configuration.name.trim()||!kind} onClick={()=>goToSetupStep(2)}>{hr?'Nastavi na događaj':'Continue to event'}</button></section>
 <section hidden={step!==2} id="setup-step-2" className={`${s.card} ${s.journeySection}`}><span className={s.eyebrow}>2 · {kind==='league'?(hr?'Odaberite sezonu':'Choose a season'):(hr?'Odaberite izdanje':'Choose an event edition')}</span>{!kind?<p>{hr?'Najprije odaberite vrstu programa. Postojeća raspodjela ostaje sačuvana.':'Choose a programme type first. Your existing distribution is preserved.'}</p>:kind==='league'?<><RewardSetupEvent key={addedProgramme??'current'} context={ctx??null} initialProgramme={addedProgramme??initialProgramme} disabled={disabled} hr={hr} onChange={onContext} onLoaded={onLoaded}/>{ctx?<button className={s.primary} onClick={()=>goToSetupStep(3)}>{hr?'Pregledaj strukturu':'Review structure'}</button>:null}<button className={s.button} onClick={()=>setShowSeasons(v=>!v)}>{showSeasons?(hr?'Zatvori':'Close'):(hr?'Poveži drugu sezonu':'Connect another season')}</button>{showSeasons?<Suspense fallback={<p>{hr?'Učitavanje…':'Loading…'}</p>}><SeasonPicker onSelected={draftId=>{setAddedProgramme(draftId);setShowSeasons(false);}}/></Suspense>:null}</>:<><h2>{hr?'Vaši RacesOn događaji':'Your RacesOn events'}</h2><p className={s.small}>{hr?'Prikazuju se događaji kojima upravljate u ovom izoliranom demonstracijskom sustavu. Uvoz iz produkcije još nije povezan.':'Events you can manage in this isolated demo. Import from production RacesOn is not connected yet.'}</p>{!auth.account?.hasOrganizerAccess?<p>{hr?'Prijavite se kao organizator kako biste odabrali događaj.':'Sign in as an organizer to choose an event.'}</p>:<><label className={s.field}>{hr?'Pretraži naziv ili datum':'Search by name or date'}<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={hr?'Naziv ili 2026-10…':'Name or 2026-10…'}/></label>{events===null&&!failed?<p role="status">{hr?'Učitavanje događaja…':'Loading events…'}</p>:null}<div className={s.eventOptions}>{events?.filter(e=>`${e.name} ${e.date} ${e.organizationName}`.toLowerCase().includes(search.toLowerCase())).map(e=><button className={s.eventOption} key={e.id} disabled={disabled} aria-pressed={eventId===e.id} onClick={()=>void chooseEvent(e.id)}><strong>{e.name}</strong><span>{e.date} · {e.organizationName}</span><span>{eventId===e.id?(hr?'Odabrano':'Selected'):(hr?'Odaberi izdanje':'Select edition')}</span></button>)}</div>{events?.length===0?<p>{hr?'Nema dostupnih događaja. Dodajte događaj u demonstracijskom portalu.':'No events are available. Add an event in the demo portal.'} <Link to="/organizer/events">{hr?'Upravljaj događajima':'Manage events'}</Link></p>:events&&!events.some(e=>`${e.name} ${e.date} ${e.organizationName}`.toLowerCase().includes(search.toLowerCase()))?<p>{hr?'Nema podudaranja.':'No matching events.'}</p>:null}</>}{failed?<p role="alert">{hr?'Događaji nisu dostupni.':'Events could not be loaded.'} <button className={s.button} onClick={()=>setRetry(n=>n+1)}>{hr?'Pokušaj ponovno':'Try again'}</button></p>:null}</>}</section>
 <section hidden={step!==3} id="setup-step-3" className={`${s.card} ${s.journeySection}`}><span className={s.eyebrow}>3 · {hr?'Pregled strukture':'Review event structure'}</span><h2>{hr?'Utrke, uvjeti i službene kategorije':'Routes, eligibility and official categories'}</h2>{kind==='event'?catalogue?<><div className={s.eventOptions}>{catalogue.races.map(r=><div key={r.id} className={s.structureRace}><h3>{r.name} · {r.distanceKm??'—'} km</h3><p>{hr?'Dob':'Age'}: {r.minimumAge??'—'}–{r.maximumAge??'—'} · {hr?'Spol':'Sex'}: {r.genders.join(', ')||'—'}</p><p>{r.groups.map(g=>g.label).join(' · ')|| (hr?'Nema kategorija':'No categories')}</p>{r.missing.map(m=><p key={m} className={s.notice}>{missingText(m)}</p>)}</div>)}</div>{catalogue.catalogueHash!==configuration.event?.catalogueHash?<p role="alert" className={s.notice}>{hr?'Struktura događaja se promijenila. Osvježite kategorije i ponovno provjerite uvjete grana.':'The event structure changed. Refresh the categories and review each branch’s eligibility again.'}<button className={s.button} disabled={disabled} onClick={()=>{if(configuration.event)onChange({...configuration,event:{...configuration.event,catalogueHash:catalogue.catalogueHash,name:catalogue.name.slice(0,100),date:catalogue.date,choices:configuration.event.choices.map(c=>({...c,approved:false}))}});}}>{hr?'Osvježi kategorije':'Refresh categories'}</button></p>:null}<p className={s.small}>{hr?'Popis klubova ne određuje njihov poredak. Klupske nagrade dostupne su samo kada je način bodovanja definiran.':'A list of participating clubs does not define standings. Club rewards require a configured ranking method.'}</p><button className={s.primary} onClick={()=>goToSetupStep(4)}>{hr?'Odaberi nagrade':'Choose what to reward'}</button></>:<p>{hr?'Najprije odaberite izdanje događaja.':'Select an event edition first.'}</p>:league?<><p>{league.catalogue.rounds.map(r=>`${r.name} · ${r.date}`).join(' / ')}</p><p>{league.catalogue.categories.map(c=>`${c.competitionName} · ${c.name}`).join(' / ')}</p>{step===3&&selection&&ctx&&ctx.draftId===selection.record.draftId&&ctx.catalogueHash===selection.workspace.catalogueHash?<Suspense fallback={<p>{hr?'Učitavanje…':'Loading…'}</p>}><LeagueMetrics selection={selection} hr={hr}/></Suspense>:null}<button className={s.primary} onClick={()=>goToSetupStep(4)}>{hr?'Odaberi nagrade':'Choose what to reward'}</button></>:<p>{hr?'Najprije povežite sezonu.':'Connect a season first.'}</p>}</section>

 </>;
}
