import CategoryResultTables from './CategoryResultTables';
import {sortResultRows,type ResultSort} from '../model/resultSorting';
import ResultSortHeader from './ResultSortHeader';
import ClubResultsTable from './ClubResultsTable';
import {useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,Search,Users,Coins,Gift} from 'lucide-react';
import type {ResultDisplay} from '../data/resultDisplay';
import {setupAmount} from '../model/setupAmount';
import s from './RewardResultsTable.module.css';
import {resultTime} from '../model/resultTime';
export default function RewardResultsTable({data,budgetWei,approved=false,hr=false,groupByCategory=false}:{groupByCategory?:boolean;data:ResultDisplay;budgetWei:string;approved?:boolean;hr?:boolean}){
 const [grouped,setGrouped]=useState(groupByCategory);
 const [race,setRace]=useState(''),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0);
 const [sort,setSort]=useState<ResultSort>('official'),[descending,setDescending]=useState(false);
 const changeSort=(key:ResultSort)=>{setSort(key);setDescending(sort===key?!descending:false);setPage(0);};
 const t=(en:string,local:string)=>hr?local:en,athletes=data.rows.filter(r=>r.kind==='athlete'),clubs=data.rows.filter(r=>r.kind==='club');
 const races=[...new Set(athletes.map(r=>r.race))],categories=[...new Set(athletes.flatMap(r=>r.categories))].sort();
 const filtered=useMemo(()=>sortResultRows(data.rows.filter(r=>r.kind==='athlete'&&(!race||r.race===race)&&(!category||r.categories.includes(category))&&(!query||`${r.name??''} ${r.club??''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))),sort,descending),[data,race,category,query,sort,descending]);
 const hasFilters=Boolean(race||category||query);
 const clearFilters=()=>{setRace('');setCategory('');setQuery('');setPage(0);};
 const pages=Math.max(1,Math.ceil(filtered.length/8)),current=Math.min(page,pages-1),visible=filtered.slice(current*8,current*8+8);
 const reward=(v:string|null)=>v===null?t('Pending review','Čeka pregled'):`${setupAmount(BigInt(v),hr)} test MON`;
 return <section className={s.results} aria-label={t('Official results and rewards','Službeni rezultati i nagrade')}>
  <div className={s.toolbar}><div className={s.summary}><span><Users size={18}/>{athletes.length} {t('results','rezultata')}</span><span><Coins size={18}/>{t('Prize budget','Fond nagrada')} <strong>{setupAmount(BigInt(budgetWei),hr)} test MON</strong></span><span><Gift size={18}/>{data.estimated?t('Estimated rewards','Procjena nagrada'):approved?t('Approved rewards','Odobrene nagrade'):t('Proposed rewards','Predložene nagrade')}</span></div>
  <div className={s.filters}><select aria-label={t('Race','Utrka')} value={race} onChange={e=>{setRace(e.target.value);setPage(0);}}><option value="">{t('All races','Sve utrke')}</option>{races.map(r=><option key={r}>{r}</option>)}</select><select aria-label={t('Category','Kategorija')} value={category} onChange={e=>{setCategory(e.target.value);setPage(0);}}><option value="">{t('All categories','Sve kategorije')}</option>{categories.map(c=><option key={c}>{c}</option>)}</select><label className={s.search}><Search size={16}/><input aria-label={t('Find an athlete','Pronađi sportaša')} placeholder={t('Find an athlete…','Pronađi sportaša…')} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label></div></div>
  {hasFilters?<div className={s.filterStatus}><span aria-live="polite">{t(`${filtered.length} of ${athletes.length} results match your filters`,`${filtered.length} od ${athletes.length} rezultata odgovara filtrima`)}</span><button type="button" onClick={clearFilters}>{t('Clear athlete filters','Očisti filtre sportaša')}</button></div>:null}
  {groupByCategory?<div className={s.viewToggle} role="group" aria-label={t('Results view','Prikaz rezultata')}><button aria-pressed={grouped} onClick={()=>setGrouped(true)}>{t('Category tables','Tablice kategorija')}</button><button aria-pressed={!grouped} onClick={()=>setGrouped(false)}>{t('All results','Svi rezultati')}</button></div>:null}
  {data.estimated?<p className={s.note}>{t('Estimated from the published results and saved reward rules. Confirm the source to calculate the awards for approval.','Procjena prema objavljenim rezultatima i spremljenim pravilima. Potvrdite izvor za izračun nagrada za odobravanje.')}</p>:null}
  {grouped?<CategoryResultTables key={JSON.stringify([race,category,query])} rows={filtered} scope={data.scope} hr={hr}/>:<><p className={s.scrollHint}>{t("Scroll the table sideways to see times and rewards.","Pomaknite tablicu vodoravno za vremena i nagrade.")}</p><div className={s.scroll} tabIndex={0} role="region" aria-label={t("Scrollable results table","Pomična tablica rezultata")}><table><caption className={s.caption}>{data.scope==='league'?t('League awards combine the approved standings categories; a single race place or finish time does not apply.','Nagrade lige zbrajaju odobrene kategorije poretka; nema jednog mjesta ili vremena utrke.'):t('Rank is the official place within each race. Reward amounts combine the athlete’s eligible categories for this round.','Poredak je službeno mjesto unutar utrke. Iznos uključuje nagrade iz svih pripadajućih kategorija ovog kola.')}</caption><thead><tr>{([['rank',t('Rank','Poredak')],['name',t('Athlete','Sportaš')],['club',t('Club','Klub')],['category',t('Category','Kategorija')],['time',t('Finish time','Vrijeme')],['reward',approved?t('Reward','Nagrada'):t('Proposed reward','Predložena nagrada')]] as [ResultSort,string][]).map(([key,label])=><ResultSortHeader key={key} column={key} label={label} current={sort} descending={descending} onSort={changeSort}/>)}</tr></thead><tbody>{visible.map(r=><tr key={r.key}><td>{r.rank??'—'}</td><th scope="row">{r.name??t('Name unavailable','Ime nije dostupno')}{races.length>1?<small>{r.race}</small>:null}</th><td>{r.club||'—'}</td><td>{r.categories.join(' · ')||'—'}</td><td className={s.time}>{resultTime(r.timeMs,r.status)}</td><td className={s.amount}>{reward(r.amountWei)}</td></tr>)}</tbody></table></div>
  </>}
  {!filtered.length?<p role="status" className={s.empty}>{t('No matching results.','Nema odgovarajućih rezultata.')}</p>:null}
  {!grouped?<div className={s.pagination}><span>{filtered.length?t(`Showing ${current*8+1}–${Math.min((current+1)*8,filtered.length)} of ${filtered.length}`,`Prikaz ${current*8+1}–${Math.min((current+1)*8,filtered.length)} od ${filtered.length}`):t('0 results','0 rezultata')}</span><div><button aria-label={t('Previous results','Prethodni rezultati')} disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={18}/></button><span>{current+1} / {pages}</span><button aria-label={t('Next results','Sljedeći rezultati')} disabled={current===pages-1} onClick={()=>setPage(current+1)}><ChevronRight size={18}/></button></div></div>:null}
  {clubs.length?(grouped?[...new Set(clubs.flatMap(row=>row.categories.length?row.categories:['']))].sort().map(category=><ClubResultsTable key={category} rows={clubs.filter(row=>category?row.categories.includes(category):!row.categories.length)} approved={approved} hr={hr} title={`${t('Club standings','Klupski poredak')} · ${category||t('No classification listed','Kategorija nije navedena')}`}/>):<ClubResultsTable rows={clubs} approved={approved} hr={hr}/>):null}
  <p className={s.totals}>{t('Full pot','Cijeli fond')}: {t('Allocated','Raspoređeno')} <strong>{reward(data.allocatedWei)}</strong> · {t('Reserved','Rezervirano')} <strong>{reward(data.retainedWei)}</strong>{data.estimated?` · ${t('estimate only','samo procjena')}`:''}</p>
 </section>;
}
