import {useEffect,useState} from 'react';
import type {RewardSetupEventContext,RewardEventCatalogue,RewardEventChoice} from '@raceson/domain/rewards/setup-event';
import type {RewardSetupNode} from '@raceson/domain/rewards/distribution-setup';
import {readSetupEvent} from '../data/setupEvents';
import RewardSetupEventResults from './RewardSetupEventResults';
import s from './RewardSetup.module.css';
export default function RewardSetupDirectSource({event,node,slots,hr,disabled,onConnect}:{event:RewardSetupEventContext;node:RewardSetupNode;slots:bigint[];hr:boolean;disabled:boolean;onConnect:(choice:RewardEventChoice,basis:'race_position'|'club_points')=>void}){
 const [catalogue,setCatalogue]=useState<RewardEventCatalogue|null>(null),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);const existing=event.choices.find(c=>c.nodeId===node.id);
 const [value,setValue]=useState(existing?`${existing.raceId}|${existing.groupKey}`:''),[approved,setApproved]=useState(existing?.approved??false);
 useEffect(()=>{let active=true;setFailed(false);void readSetupEvent(event.editionId).then(c=>{if(active)setCatalogue(c);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[event.editionId,retry]);
 const options=catalogue?.races.flatMap(r=>r.groups.map(g=>({key:`${r.id}|${g.key}`,label:`${r.name} · ${g.label}`,race:r,group:g})))??[],selected=options.find(o=>o.key===value),fresh=catalogue?.catalogueHash===event.catalogueHash;
 return <div className={s.source}><label className={s.field}>{hr?'Kategorija ove grane':'Category for this branch'}<select disabled={disabled||!fresh} value={value} onChange={e=>{setValue(e.target.value);setApproved(false);}}><option value="">{hr?'Odaberite…':'Choose…'}</option>{options.map(o=><option key={o.key} value={o.key}>{o.label}</option>)}</select></label>{selected?<p className={s.small}>{selected.group.gender??(hr?'Svi spolovi':'All sexes')} · {hr?'Dob':'Age'} {selected.group.minimumAge??selected.race.minimumAge??'—'}–{selected.group.maximumAge??selected.race.maximumAge??'—'} · {selected.group.kind==='club'?(hr?'Službeni klupski poredak':'Configured club standings'):(hr?'Službeni plasman':'Official finish order')}</p>:null}<label><input type="checkbox" disabled={disabled||!fresh} checked={approved} onChange={e=>setApproved(e.target.checked)}/> {hr?'Uvjeti pregledani':'Eligibility reviewed'}</label><button className={s.button} disabled={disabled||!selected||!fresh} onClick={()=>{if(selected)onConnect({nodeId:node.id,raceId:selected.race.id,groupKey:selected.group.key,approved},selected.group.kind==='club'?'club_points':'race_position');}}>{hr?'Poveži kategoriju':'Connect category'}</button>{failed?<p role="alert">{hr?'Kategorije nisu dostupne.':'Categories could not be loaded.'} <button className={s.button} onClick={()=>setRetry(n=>n+1)}>{hr?'Pokušaj ponovno':'Try again'}</button></p>:catalogue&&!fresh?<p className={s.notice}>{hr?'Struktura se promijenila. Pregledajte događaj u koraku 3.':'The event structure changed. Review the event in step 3.'}</p>:null}<RewardSetupEventResults key={`${existing?.raceId}:${existing?.groupKey}:${existing?.approved}`} event={event} node={node} slots={slots} hr={hr}/></div>;
}
