import {useEffect,useState} from 'react';
import {previewEventGroup,type EventRewardResults,type RewardSetupEventContext} from '@raceson/domain/rewards/setup-event';
import type {RewardSetupNode} from '@raceson/domain/rewards/distribution-setup';
import {readSetupEventResults} from '../data/setupEvents';
import {setupAmount} from '../model/setupAmount';
import s from './RewardSetup.module.css';
export default function RewardSetupEventResults({event,node,slots,hr}:{event:RewardSetupEventContext;node:RewardSetupNode;slots:bigint[];hr:boolean}){
 const choice=event.choices.find(c=>c.nodeId===node.id),[results,setResults]=useState<EventRewardResults|null>(null),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);
 const raceId=choice?.raceId;
 useEffect(()=>{if(!raceId)return;let active=true;setResults(null);setFailed(false);void readSetupEventResults(event.editionId,raceId).then(r=>{if(active)setResults(r);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[event.editionId,raceId,attempt]);
 const preview=results?previewEventGroup(event,node,slots,results):null;
 return <section className={s.source} aria-label={`${node.name} ${hr?'rezultati':'results'}`}><h3>{node.name}</h3><p className={s.small}>{event.name} · {event.date}</p>{!choice?<p className={s.notice}>{hr?'Povežite ovu granu s kategorijom u koraku 4.':'Connect this branch to a category in step 4.'}</p>:failed?<p role="alert">{hr?'Rezultati nisu dostupni.':'Results could not be loaded.'}</p>:!results?<p role="status">{hr?'Učitavanje objavljenih rezultata…':'Loading published results…'}</p>:preview?.issue?<p className={s.notice}>{preview.issue==='distribution_incomplete'?(hr?'Dovršite raspodjelu prije izračuna nagrada.':'Complete the distribution before calculating rewards.'):preview.issue==='awaiting_publication'?(hr?'Čeka se službena objava rezultata. Postavke su sačuvane.':'Waiting for official results. Your setup is saved.'):preview.issue==='source_changed'?(hr?'Struktura događaja se promijenila. Pregledajte postavke prije rezultata.':'The event structure changed. Review setup before calculating rewards.'):preview.issue==='eligibility_review'?(hr?'Potrebna je provjera uvjeta kategorije ili podataka sudionika.':'Category eligibility or participant information needs review.'):(hr?'Rezultati nisu potpuni ili sadrže neusklađene zapise.':'Results are incomplete or contain conflicting records.')}</p>:preview?<><p className={s.small}>{hr?'Objavljeno':'Published'}: {results.publishedAt} · {results.publicationState}</p><div className={s.tableWrap}><table className={s.table}><thead><tr><th>{hr?'Mjesto':'Place'}</th><th>{hr?'Predloženi primatelj':'Proposed recipient'}</th><th>test MON</th></tr></thead><tbody>{preview.awards.filter(a=>a.amountWei>0n).map(a=><tr key={a.beneficiaryId}><td>{a.place}</td><td>{a.name}</td><td>{setupAmount(a.amountWei,hr)}</td></tr>)}</tbody></table></div><p>{hr?'Neiskorišteno → RacesOn riznica':'Unspent → RacesOn treasury'}: {setupAmount(preview.unusedWei,hr)} test MON</p></>:null}{choice?<button className={s.button} onClick={()=>setAttempt(n=>n+1)}>{hr?'Osvježi rezultate':'Refresh results'}</button>:null}<p className={s.small}>{hr?'Prijedlog za pregled. Odobrenje, objava nagrada i isplate slijede kasnije.':'A proposal for review. Approval, reward publication and payment are later steps.'}</p></section>;
}
