import {useEffect,useRef,useState} from "react";
import {setupNodes, setupPath, type RewardDistributionSetup} from "@raceson/domain/rewards/distribution-setup";
import {convertToGuidedSetup, inspectGuidedConversion, type GuidedConversionChoice} from "@raceson/domain/rewards/guided-setup-conversion";
import {GUIDED_REWARD_TYPES, isParticipationType, type GuidedRewardType} from "@raceson/domain/rewards/guided-setup";
import {setupAmount} from "../model/setupAmount";
import s from "./RewardSetup.module.css";
import g from "./GuidedRewardSetup.module.css";

type Props={source:RewardDistributionSetup;revision:number;hr:boolean;busy:boolean;uncertain:boolean;error:string|null;
  onCancel:()=>void;onCreate:(configuration:RewardDistributionSetup)=>void};
export default function RewardSetupConversion({source,revision,hr,busy,uncertain,error,onCancel,onCreate}:Props) {
  const t=(en:string,local:string)=>hr?local:en;
  const [step,setStep]=useState(1),[potIds,setPotIds]=useState<string[]>(Array(6).fill(""));
  const [choices,setChoices]=useState<Record<string,Partial<GuidedConversionChoice>>>({}),[accepted,setAccepted]=useState(false);
  const page=useRef<HTMLElement>(null);
  useEffect(()=>{page.current?.focus({preventScroll:true});page.current?.scrollIntoView?.({block:"start"});},[step]);
  const disabled=busy||uncertain;
  const labels:Record<GuidedRewardType,string>={athlete_standings:t("Athlete standings","Poredak sportaša"),club_standings:t("Club standings","Klupski poredak"),athlete_finishes:t("Athlete finishes","Broj završetaka"),athlete_metres:t("Athlete kilometres","Kilometri sportaša"),club_metres:t("Club kilometres","Kilometri klubova")};
  const candidates=setupNodes(source.root).filter(n=>n.id!==source.root.id&&!n.rule);
  let inspected:ReturnType<typeof inspectGuidedConversion>|null=null,proposal:ReturnType<typeof convertToGuidedSetup>|null=null,problem="";
  try {inspected=inspectGuidedConversion(source,potIds);}catch {problem=t("Choose six separate pots covering every existing group. Pots cannot contain one another or have overallocated branches.","Odaberite šest zasebnih fondova koji pokrivaju sve postojeće grupe. Fondovi ne mogu sadržavati jedni druge ni prekomjerno raspoređene grane.");}
  if(inspected)try{proposal=convertToGuidedSetup(source,potIds,Object.values(choices) as GuidedConversionChoice[]);}catch(e){
    problem=e instanceof Error&&e.message==="reward_conversion_precision"?t("This tree cannot be flattened without changing exact amounts. Keep the original and adjust its structure explicitly before converting.","Ovo stablo nije moguće pojednostaviti bez promjene točnih iznosa. Zadržite izvornik i izričito prilagodite strukturu prije pretvorbe."):
      t("Choose a reward type for every group. Unfinished groups also need a prize count and distribution. Participation types can appear only once each in the league pot.","Odaberite vrstu nagrade za svaku grupu. Nedovršene grupe trebaju broj mjesta i raspodjelu. Svaka vrsta sudjelovanja može se pojaviti samo jednom u fondu lige.");
  }
  function choose(nodeId:string,change:Partial<GuidedConversionChoice>){setAccepted(false);setChoices(old=>({...old,[nodeId]:{...old[nodeId],nodeId,...change}}));}
  return <article ref={page} tabIndex={-1} aria-label={t("Create guided copy","Stvori vođenu kopiju")} className={`${s.page} ${g.page}`}>
    <header className={s.heading}><div><span className={s.eyebrow}>{t("Guided setup · New copy","Vođeno postavljanje · Nova kopija")}</span><h1>{t("Keep your distribution. Simplify setup.","Zadržite raspodjelu. Pojednostavite postavljanje.")}</h1><p>{source.name} · {t("Original version","Izvorna verzija")} {revision} · {source.budgetMon} test MON</p></div><button className={s.button} disabled={disabled} onClick={onCancel}>{t("Back to original","Natrag na izvornik")}</button></header>
    <p>{t("Your original stays saved. This creates a separate draft with the same pot amounts, group names and existing prize distributions. Results connections and eligibility will need a fresh review.","Izvornik ostaje spremljen. Stvara se zaseban nacrt s istim iznosima fondova, nazivima grupa i postojećom raspodjelom mjesta. Poveznice rezultata i uvjeti trebaju novi pregled.")}</p>
    <ol className={`${s.workflow} ${g.steps}`} aria-label={t("Conversion progress","Koraci pretvorbe")}>{[t("Choose pots","Odaberi fondove"),t("Confirm reward rules","Potvrdi pravila nagrada"),t("Compare and create","Usporedi i stvori")].map((label,i)=><li key={label}><button disabled={disabled||i+1>step} aria-current={step===i+1?"step":undefined} onClick={()=>{setStep(i+1);setAccepted(false);}}><span>{i+1}</span>{label}</button></li>)}</ol>
    {error?<p role="alert" className={s.notice}>{error}</p>:null}
    <section className={`${s.card} ${g.body}`}>
      {step===1?<><h2>{t("Identify the league and five round pots","Odredite fond lige i pet kola")}</h2><p>{t("Choose by the full branch path. Grouping branches such as “Races” become an overview rather than another pot.","Odaberite prema punoj putanji grane. Zbirne grane poput „Utrke” postaju pregled umjesto dodatnog fonda.")}</p><div className={g.potGrid}>{potIds.map((value,slot)=>{const label=slot===0?t("League pot","Fond lige"):`${t("Round","Kolo")} ${slot}`;return <label key={slot} className={s.field}>{label}<select value={value} disabled={disabled} onChange={e=>{setPotIds(old=>old.map((id,i)=>i===slot?e.target.value:id));setChoices({});setAccepted(false);}}><option value="">{t("Choose existing branch…","Odaberite postojeću granu…")}</option>{candidates.map(n=><option key={n.id} value={n.id}>{setupPath(source.root,n.id).slice(1).map(n=>n.name).join(" / ")}</option>)}</select></label>;})}</div>{!inspected?<p className={s.notice}>{problem}</p>:null}<button className={s.primary} disabled={disabled||!inspected} onClick={()=>setStep(2)}>{t("Continue to reward rules","Nastavi na pravila nagrada")}</button></>:null}
      {step===2&&inspected?<><h2>{t("Confirm what each group rewards","Potvrdite što svaka grupa nagrađuje")}</h2><p>{t("Names alone do not define a rule. Existing prize counts and shares are preserved. You can change the method later in the guided form.","Sam naziv ne definira pravilo. Postojeći broj mjesta i udjeli ostaju isti. Metodu kasnije možete promijeniti u vođenom obrascu.")}</p>{inspected.pots.map((pot,slot)=>{
        const groups=inspected!.groups.filter(row=>row.potId===pot.id),types=GUIDED_REWARD_TYPES.filter(type=>slot===0||!isParticipationType(type));
        return <details className={g.details} key={pot.id} open><summary>{pot.name} · {groups.length} {t("groups","grupa")}</summary>
          {groups.length>1?<label className={s.field}>{t("Set type for all groups in","Postavi vrstu svih grupa u")} {pot.name}<select disabled={disabled} value="" onChange={e=>{if(e.target.value)for(const {node} of groups)choose(node.id,{type:e.target.value as GuidedRewardType});}}><option value="">{t("Choose a shared type…","Odaberite zajedničku vrstu…")}</option>{types.filter(type=>!isParticipationType(type)).map(type=><option value={type} key={type}>{labels[type]}</option>)}</select></label>:null}
          {groups.map(({node,path})=><section key={node.id} className={g.reward} aria-label={path}><h3>{node.name}</h3><p className={s.small}>{path}</p><div className={g.controls}><label className={s.field}>{t("Reward type","Vrsta nagrade")} · {node.name}<select disabled={disabled} value={choices[node.id]?.type??""} onChange={e=>choose(node.id,{type:e.target.value as GuidedRewardType})}><option value="">{t("Choose explicitly…","Izričito odaberite…")}</option>{types.map(type=><option key={type} value={type}>{labels[type]}</option>)}</select></label>
            {node.rule?<p>{t("Keep","Zadrži")} {node.rule.sharesBps.length} {t("prize positions and their exact shares","nagrađenih mjesta i njihove točne udjele")}</p>:<><label className={s.field}>{t("Prize positions","Nagrađena mjesta")} · {node.name}<input type="number" min="1" max="100" step="1" disabled={disabled} value={choices[node.id]?.newPrizeCount??""} onChange={e=>choose(node.id,{newPrizeCount:e.target.value?Number(e.target.value):undefined})}/></label><label className={s.field}>{t("New distribution","Nova raspodjela")} · {node.name}<select disabled={disabled} value={choices[node.id]?.newPrizeCurve??""} onChange={e=>choose(node.id,{newPrizeCurve:e.target.value as "equal"|"descending"})}><option value="">{t("Choose distribution…","Odaberite raspodjelu…")}</option><option value="equal">{t("Equal prizes","Jednake nagrade")}</option><option value="descending">{t("Weighted prizes","Ponderirane nagrade")}</option></select></label></>}
          </div></section>)}
        </details>;
      })}{!proposal?<p className={s.notice}>{problem}</p>:null}<button className={s.primary} disabled={disabled||!proposal} onClick={()=>setStep(3)}>{t("Compare distributions","Usporedi raspodjele")}</button></>:null}
      {step===3&&proposal?<><h2>{t("Compare before creating the copy","Usporedite prije stvaranja kopije")}</h2><p>{t("Every pot and group keeps its exact amount. Existing prize shares stay unchanged. Newly configured groups now assign their previously unused budget to the prize positions you chose.","Svaki fond i grupa zadržavaju točan iznos. Postojeći udjeli mjesta ostaju isti. Novo postavljene grupe raspoređuju prethodno neiskorišten fond na odabrana mjesta.")}</p>
        <div className={s.tableWrap}><table className={s.table}><caption>{t("Original and guided allocation","Izvorna i vođena raspodjela")} · test MON</caption><thead><tr><th>{t("Original branch","Izvorna grana")}</th><th>{t("Before","Prije")}</th><th>{t("After","Poslije")}</th><th>{t("Guided rule","Vođeno pravilo")}</th></tr></thead><tbody>{proposal.comparison.map(row=><tr key={row.nodeId}><td>{row.path}</td><td>{setupAmount(row.beforeWei,hr)}</td><td>{setupAmount(row.afterWei,hr)}</td><td>{row.type?`${labels[row.type]} · ${row.beforeShares.length||t("Unconfigured","Nepostavljeno")} → ${row.afterShares.length} ${t("prize positions","nagrađenih mjesta")}`:t("Pot","Fond")}</td></tr>)}</tbody></table></div>
        <p>{t("Unallocated across the programme","Neraspoređeno u programu")}: {setupAmount(proposal.retainedBeforeWei,hr)} → {setupAmount(proposal.retainedAfterWei,hr)} test MON</p>
        {proposal.removedContainers.length?<p>{t("Grouping headings replaced by the overview","Zbirni naslovi zamijenjeni pregledom")}: {proposal.removedContainers.map(n=>n.name).join(", ")}</p>:null}
        <p className={s.notice}>{t("Reconnect the league's event editions and official categories in the new copy. Review one finish per athlete per round, race-day club attribution and eligibility before finishing setup. This copy cannot change funded allocations or release rewards.","U novoj kopiji ponovno povežite izdanja događaja i službene kategorije lige. Prije dovršetka pregledajte jedan završetak po sportašu u kolu, pripadnost klubu na dan utrke i uvjete. Kopija ne mijenja financirane raspodjele ni objavljuje nagrade.")}</p>
        <label className={g.check}><input type="checkbox" checked={accepted} disabled={disabled} onChange={e=>setAccepted(e.target.checked)}/>{t("I reviewed the mapped rules and new prize choices","Pregledao/la sam povezana pravila i nove izbore mjesta")}</label>
        <button className={s.primary} disabled={busy||!accepted} onClick={()=>onCreate(proposal.configuration)}>{busy?t("Creating…","Stvaranje…"):uncertain?t("Retry creating the same copy","Ponovi stvaranje iste kopije"):t("Create guided copy","Stvori vođenu kopiju")}</button>
      </>:null}
    </section>
  </article>;
}
