import {useEffect,useState} from 'react';
import {useAuth} from '@/lib/auth';
import {listPlanningDrafts,readPlanningDraft} from '../data/planningDrafts';
import {readSourceMapping} from '../data/sourceMapping';
import type {SavedRewardPlanningDraft} from '@raceson/domain/rewards/programme-draft-v2';
import type {RewardMappingWorkspaceV2} from '@raceson/domain/rewards/source-mapping-v2';
import type {RewardSetupContext} from '@raceson/domain/rewards/distribution-setup';
import s from './RewardSetup.module.css';
export type SetupEventSelection={record:SavedRewardPlanningDraft;workspace:RewardMappingWorkspaceV2};
export default function RewardSetupEvent({context,initialProgramme,disabled,hr,onChange,onLoaded,leagueOnly=false,preferSibenik=false,compact=false}:{compact?:boolean;preferSibenik?:boolean;leagueOnly?:boolean;context:RewardSetupContext|null;initialProgramme:string|null;disabled:boolean;hr:boolean;onChange:(context:RewardSetupContext)=>void;onLoaded:(selection:SetupEventSelection|null)=>void}){
 const auth=useAuth(),[programmes,setProgrammes]=useState<SavedRewardPlanningDraft[]|null>(null),[draftId,setDraftId]=useState(initialProgramme??context?.draftId??''),[roundId,setRoundId]=useState(context?.roundId??'league'),[selection,setSelection]=useState<SetupEventSelection|null>(null),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!auth.account?.hasOrganizerAccess)return;let active=true;setFailed(false);void listPlanningDrafts().then(rows=>{if(active)setProgrammes(rows);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[auth.account?.hasOrganizerAccess,retry]);
 useEffect(()=>{if(!preferSibenik||draftId||context||initialProgramme||!programmes)return;const matches=programmes.filter(p=>p.seasonName.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().includes("siben"));if(matches.length===1)setDraftId(matches[0].draftId);},[preferSibenik,draftId,context,initialProgramme,programmes]);
 useEffect(()=>{let active=true;setSelection(null);onLoaded(null);const record=programmes?.find(p=>p.draftId===draftId);if(!record)return;setFailed(false);
  void readPlanningDraft(record).then(async fresh=>({record:fresh,workspace:await readSourceMapping(fresh)})).then(result=>{if(active){setSelection(result);onLoaded(result);}}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};
 },[draftId,programmes,retry,onLoaded]);
 const rounds=selection?.workspace.catalogue.rounds.filter(r=>r.status!=='cancelled')??[],round=rounds.find(r=>r.id===roundId);
 return <section className={compact?s.compactEvent:`${s.card} ${s.eventCard}`} aria-label={hr?'Događaj za nagrade':'Reward event'}>{!compact?<header className={s.cardHeader}><div><span className={s.eyebrow}>{hr?'Liga / sezona':'League / season'}</span><h2>{context?.eventName??(leagueOnly?(hr?'Odaberite ligu / sezonu':'Choose a league / season'):(hr?'Odaberite događaj ili ligu':'Choose an event or league'))}</h2><p>{hr?'Ovaj izbor povezuje nagrade s istom sezonom i rezultatima.':'This connects the rewards to the same season and its results.'}</p></div>{context?<span className={s.badge}>{context.programmeName}</span>:null}</header>:null}
 <div className={s.eventFields}>{auth.account?.hasOrganizerAccess?<><label className={s.field}>{compact?(hr?'Liga':'League'):(hr?'Liga / program':'League / programme')}<select disabled={disabled||programmes===null} value={draftId} onChange={e=>{setDraftId(e.target.value);setRoundId('league');}}><option value="">{hr?'Odaberite…':'Choose…'}</option>{programmes?.map(p=><option key={p.draftId} value={p.draftId}>{p.organizationName} · {p.seasonName}</option>)}</select></label><label hidden={leagueOnly} className={s.field}>{hr?'Događaj':'Event'}<select value={roundId} disabled={disabled||!selection} onChange={e=>setRoundId(e.target.value)}><option value="league">{hr?'Cijela liga / sezona':'Whole league / season'}</option>{rounds.map(r=><option key={r.id} value={r.id}>{r.name} · {r.date}</option>)}</select></label><button className={s.button} disabled={disabled||!selection||(roundId!=='league'&&!round)} onClick={()=>{if(!selection)return;onChange({draftId:selection.record.draftId,roundId:round?.id??null,editionId:round?.editionId??null,catalogueHash:selection.workspace.catalogueHash,programmeName:selection.record.seasonName.slice(0,100),eventName:(round?.name??selection.record.seasonName).slice(0,100)});}}>{leagueOnly?(hr?'Odaberi ligu':'Select league'):(hr?'Poveži događaj':'Use selected event')}</button></>:<p className={s.small}>{hr?'Prijavite se kao organizator za povezivanje događaja. Raspodjelu možete osmisliti i prije prijave.':'Sign in as an organizer to connect an event. You can design the distribution before signing in.'}</p>}
 {failed?<p role="alert" className={s.notice}>{hr?'Događaji nisu dostupni.':'Events could not be loaded.'} <button className={s.button} onClick={()=>setRetry(n=>n+1)}>{hr?'Pokušaj ponovno':'Try again'}</button></p>:null}
 {auth.account?.hasOrganizerAccess&&programmes?.length===0?<p>{hr?'Nema dostupnih liga.':'No leagues available.'}</p>:null}
 </div></section>;
}
