import {useEffect,useMemo,useRef,useState} from 'react';
import {setupNodes,setupPath,type RewardSetupNode,type SetupPreviewRow} from '@raceson/domain/rewards/distribution-setup';
import {rewardSetupCopy} from '../model/rewardSetupCopy';
import {clampBranchOffset,rewardSetupLayout,type SetupPoint} from '../model/rewardSetupLayout';
import {rewardSetupNodeSizes} from '../model/rewardSetupNodeSize';
import {useRewardSetupMotion} from '../model/useRewardSetupMotion';
import {setupCanvasPoint,zoomSetupView,type SetupView as View,type ScreenPoint} from '../model/rewardSetupViewport';
import {setupAmount} from '../model/setupAmount';
import s from './RewardSetup.module.css';
const palette=['#7c62bc','#2589a0','#c18143','#549174','#b66287','#627fc4'];
export default function RewardSetupChart({root,selected,selectedRank=null,rows,onSelect,hr,onAddChild,canAddChild,initialShowPrizes=true,readOnly=false,inspectorId="reward-setup-inspector"}:{readOnly?:boolean;inspectorId?:string;initialShowPrizes?:boolean;root:RewardSetupNode;selected:string;selectedRank?:number|null;rows:SetupPreviewRow[];onSelect:(id:string,rank?:number|null)=>void;hr:boolean;onAddChild?:(id:string)=>void;canAddChild?:(id:string)=>boolean}){
 const c=rewardSetupCopy(hr),[mode,setMode]=useState('graph'),[collapsed,setCollapsed]=useState<Set<string>>(new Set()),[prizes,setPrizes]=useState(initialShowPrizes),[camera,setCamera]=useState<View|null>(null);
 const [offsets,setOffsets]=useState<Record<string,number>>({}),[moving,setMoving]=useState(false),[hovered,setHovered]=useState<string|null>(null);
 const [highlightedLevel,setHighlightedLevel]=useState<number|null>(null),[canvasSize,setCanvasSize]=useState({width:800,height:650});
 const branchDrag=useRef<{id:string;angle:number;offset:number;travel:number;x:number;y:number}|null>(null),suppressClick=useRef(false);
 const drag=useRef<{x:number;y:number;camera:View;moved:boolean}|null>(null),svg=useRef<SVGSVGElement>(null);
 const touches=useRef(new Map<number,ScreenPoint>()),pinch=useRef<{distance:number;center:ScreenPoint;view:View}|null>(null);
 const all=useMemo(()=>setupNodes(root),[root]),totalPlaces=all.reduce((n,v)=>n+(v.rule?.sharesBps.length??0),0),showPrizes=prizes&&totalPlaces<=2000;
 const target=useMemo(()=>{const result=rewardSetupLayout(root,collapsed,showPrizes,offsets);return readOnly?{...result,points:result.points.filter(p=>p.rank===null||(rows.find(r=>r.id===p.owner.id)?.slots[p.rank-1]??0n)>0n)}:result;},[root,collapsed,showPrizes,offsets,readOnly,rows]);
 const layout=useRewardSetupMotion(target,moving);
 const view=camera??layout.bounds,byId=new Map(layout.points.map(p=>[p.id,p])),amounts=new Map(rows.map(r=>[r.id,r])),selectedPath=new Set([...setupPath(root,(hovered?byId.get(hovered)?.owner.id:null)??selected).map(n=>n.id),...(hovered?[hovered]:selectedRank!==null?[`${selected}:place:${selectedRank}`]:[])]);
 useEffect(()=>{const element=svg.current;if(!element||typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(([entry])=>{if(entry)setCanvasSize({width:entry.contentRect.width,height:entry.contentRect.height});});observer.observe(element);return()=>observer.disconnect();},[mode]);
 const levels=layout.radii.slice(1).flatMap((radius,index)=>{const depth=index+1,points=layout.points.filter(p=>p.depth===depth);if(!points.length)return[];const angles=points.map(p=>p.angle).sort((a,b)=>a-b);let gap=0,labelAngle=0;angles.forEach((angle,i)=>{const next=angles[i+1]??angles[0]+Math.PI*2;if(next-angle>gap){gap=next-angle;labelAngle=angle+gap/2;}});return[{depth,radius,count:points.length,labelAngle}];});
 const activeLevel=levels.some(l=>l.depth===highlightedLevel)?highlightedLevel:null,labelScale=Math.max(view.width/Math.max(canvasSize.width,1),view.height/Math.max(canvasSize.height,1));
 const nodeSizes=useMemo(()=>rewardSetupNodeSizes(layout.points,labelScale),[layout.points,labelScale]);
 const detailPoint=byId.get(hovered??(selectedRank!==null?`${selected}:place:${selectedRank}`:selected));
 function focusSelection(){const point=byId.get(selectedRank!==null?`${selected}:place:${selectedRank}`:selected);if(!point)return;const family=[point,...layout.points.filter(p=>p.parentId===point.id)],xs=family.map(p=>p.x),ys=family.map(p=>p.y),width=Math.max(360,(Math.max(...xs)-Math.min(...xs))*1.3+240,(Math.max(...ys)-Math.min(...ys))*1.3+240);setCamera({x:(Math.min(...xs)+Math.max(...xs)-width)/2,y:(Math.min(...ys)+Math.max(...ys)-width)/2,width,height:width});}
 const levelName=(depth:number)=>`${hr?'Razina':'Level'} ${depth}`;
 useEffect(()=>{const element=svg.current;if(!element)return;const wheel=(event:WheelEvent)=>{event.preventDefault();const delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?element.clientHeight:1);setCamera(old=>{const current=old??layout.bounds,anchor=setupCanvasPoint({x:event.clientX,y:event.clientY},current,element.getBoundingClientRect());return zoomSetupView(current,Math.exp(Math.max(-1,Math.min(1,delta*.002))),layout.bounds.width*2,anchor);});};element.addEventListener('wheel',wheel,{passive:false});return()=>element.removeEventListener('wheel',wheel);},[layout.bounds,mode]);
 function zoom(factor:number){setCamera(v=>zoomSetupView(v??layout.bounds,factor,layout.bounds.width*2));}
 function startTouch(e:React.PointerEvent<SVGSVGElement>){if(e.pointerType!=='touch')return;touches.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.current.size===2){const [a,b]=[...touches.current.values()];pinch.current={distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},view};branchDrag.current=null;drag.current=null;suppressClick.current=true;setMoving(false);for(const id of touches.current.keys())e.currentTarget.setPointerCapture(id);}}
 function movePinch(e:React.PointerEvent<SVGSVGElement>){if(touches.current.has(e.pointerId))touches.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const initial=pinch.current;if(!initial)return false;if(touches.current.size<2)return true;const [a,b]=[...touches.current.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2},rect=e.currentTarget.getBoundingClientRect(),anchor=setupCanvasPoint(initial.center,initial.view,rect),next=zoomSetupView(initial.view,initial.distance/Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),layout.bounds.width*2,anchor),scale=Math.max(next.width/rect.width,next.height/rect.height);setCamera({...next,x:next.x-(center.x-initial.center.x)*scale,y:next.y-(center.y-initial.center.y)*scale});return true;}
 function toggle(id:string){setCollapsed(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);return next;});}
 function select(id:string,rank:number|null=null){onSelect(id,rank);setCollapsed(previous=>{const next=new Set(previous);setupPath(root,id).forEach(n=>next.delete(n.id));return next;});}
 function pointerAngle(x:number,y:number){const matrix=svg.current?.getScreenCTM();if(!matrix)return null;const p=new DOMPoint(x,y).matrixTransform(matrix.inverse());return Math.atan2(p.y,p.x);}
 function startBranch(e:React.PointerEvent<SVGGElement>,p:SetupPoint){if(readOnly||pinch.current)return;suppressClick.current=false;if(e.button!==0||!p.parentId||p.rank!==null)return;const angle=pointerAngle(e.clientX,e.clientY);if(angle===null)return;e.stopPropagation();suppressClick.current=false;branchDrag.current={id:p.id,angle,offset:offsets[p.id]??0,travel:p.travel,x:e.clientX,y:e.clientY};}
 function endDrag(e:React.PointerEvent<SVGSVGElement>){touches.current.delete(e.pointerId);if(!touches.current.size)pinch.current=null;if(branchDrag.current&&moving){suppressClick.current=true;}branchDrag.current=null;drag.current=null;setMoving(false);}
 function moveBranch(id:string,delta:number){setOffsets(old=>({...old,[id]:clampBranchOffset((old[id]??0)+delta)}));}
 const number=(v:number)=>new Intl.NumberFormat(hr?'hr':'en',{maximumFractionDigits:2}).format(v);
 return <section id="reward-setup-chart" tabIndex={-1} className={`${s.card} ${readOnly?s.reviewCard:''}`} aria-label={c.graph}>
 <header className={s.cardHeader}><div><h2>{c.graph}</h2><p>{hr?'Kliknite krug za detalje. Kotačićem ili s dva prsta povećajte prikaz.':'Click a circle for details. Scroll or pinch to zoom.'}</p></div><div className={s.tabs} style={{margin:0}} role="tablist" aria-label={c.graph}><button role="tab" aria-selected={mode==='graph'} onClick={()=>setMode('graph')}>{c.graph}</button><button role="tab" aria-selected={mode==='list'} onClick={()=>setMode('list')}>{c.tree}</button></div></header>
 <nav className={s.crumbs} aria-label={hr?'Putanja fonda':'Pot path'}>{setupPath(root,selected).map((n,i)=><span key={n.id}>{i?' / ':''}<button onClick={()=>select(n.id)}>{n.name}</button></span>)}</nav>
 {mode==='graph'?<><div className={s.graphControls}><div className={s.actions}><button className={s.icon} aria-label={hr?'Približi':'Zoom in'} onClick={()=>zoom(.7)}>+</button><button className={s.icon} aria-label={hr?'Udalji':'Zoom out'} onClick={()=>zoom(1.4)}>−</button><output className={s.zoomReadout} aria-label={hr?'Povećanje grafikona':'Chart zoom'}>{Math.round(layout.bounds.width/view.width*100)}%</output><button className={s.button} onClick={focusSelection}>{hr?'Približi odabrano':'Zoom to selection'}</button><button className={s.button} onClick={()=>setCamera(null)}>{hr?'Prikaži sve':'Fit all'}</button>{!readOnly?<button className={s.button} onClick={()=>{setOffsets({});setCamera(null);}}>{hr?'Vrati položaje':'Reset positions'}</button>:null}<button className={s.button} onClick={()=>{setCollapsed(new Set());setCamera(null);}}>{hr?'Proširi sve grane':'Expand all branches'}</button></div><label className={s.small}><input type="checkbox" checked={showPrizes} disabled={totalPlaces>2000} onChange={e=>{setPrizes(e.target.checked);setCamera(null);}}/> {hr?'Nagrađena mjesta':'Prize places'}</label></div>
 {!readOnly?<div className={s.levelGuide} role="group" aria-label={hr?'Istakni razinu':'Highlight a level'}><span>{hr?'Isti prsten = ista razina':'Same ring = same level'}</span><div className={s.levelChips}><button aria-pressed={activeLevel===null} onClick={()=>setHighlightedLevel(null)}>{hr?'Sve razine':'All levels'}</button>{levels.map(level=><button key={level.depth} aria-pressed={activeLevel===level.depth} onClick={()=>setHighlightedLevel(activeLevel===level.depth?null:level.depth)}><b aria-hidden="true">{level.depth}</b>{levelName(level.depth)}<small aria-label={hr?`${level.count} čvorova`:`${level.count} nodes`}>{level.count}</small></button>)}</div><span className={s.levelHelp}>{hr?'Boja prati granu · broj označava razinu':'Colour follows the branch · number identifies the level'}</span></div>:null}
 <div className={`${s.networkCanvas} ${readOnly?s.reviewCanvas:''}`}><svg ref={svg} viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} role="group" aria-label={c.graph}
 onPointerDownCapture={startTouch}
 onPointerDown={e=>{if(pinch.current||e.button!==0||(e.target as Element).closest('[role=button]'))return;drag.current={x:e.clientX,y:e.clientY,camera:view,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={e=>{if(movePinch(e))return;const b=branchDrag.current;if(b){if(Math.hypot(e.clientX-b.x,e.clientY-b.y)<4&&!moving)return;const angle=pointerAngle(e.clientX,e.clientY);if(angle!==null){const delta=Math.atan2(Math.sin(angle-b.angle),Math.cos(angle-b.angle));svg.current?.setPointerCapture(e.pointerId);setMoving(true);suppressClick.current=true;setOffsets(old=>({...old,[b.id]:clampBranchOffset(b.offset+delta/b.travel)}));}return;}const d=drag.current;if(!d||!svg.current)return;const rect=svg.current.getBoundingClientRect(),scale=Math.max(d.camera.width/rect.width,d.camera.height/rect.height);d.moved=true;setCamera({...d.camera,x:d.camera.x-(e.clientX-d.x)*scale,y:d.camera.y-(e.clientY-d.y)*scale});}}
 onPointerUp={endDrag} onPointerCancel={endDrag} onLostPointerCapture={e=>{if(e.target===e.currentTarget)endDrag(e);}} onDoubleClick={e=>{if((e.target as Element).closest('[role=button]'))return;const anchor=setupCanvasPoint({x:e.clientX,y:e.clientY},view,e.currentTarget.getBoundingClientRect());setCamera(zoomSetupView(view,.5,layout.bounds.width*2,anchor));}}>
 {levels.map(({depth,radius})=><g key={`ring:${depth}`} pointerEvents="none" opacity={activeLevel===null||activeLevel===depth?1:.25}><circle r={radius} fill="none" stroke={activeLevel===depth?'#bfded3':'#deebe5'} strokeWidth={activeLevel===depth?22:14} vectorEffect="non-scaling-stroke" opacity=".55"/><circle data-depth-ring={depth} r={radius} fill="none" stroke={activeLevel===depth?'#087f65':'#88a79b'} strokeDasharray={depth%2===0?'5 5':undefined} strokeWidth={activeLevel===depth?2:1} vectorEffect="non-scaling-stroke"/></g>)}
 {layout.points.filter(p=>p.parentId).map(p=>{const parent=byId.get(p.parentId!)!;return <line key={`edge:${p.id}`} x1={parent.x} y1={parent.y} x2={p.x} y2={p.y} stroke={palette[p.branch%palette.length]} vectorEffect="non-scaling-stroke" strokeWidth={selectedPath.has(p.id)?2:p.rank?.65:1.3} opacity={activeLevel!==null&&p.depth!==activeLevel?.12:selectedPath.has(p.id)?.85:.35}/>;})}
 {layout.points.map(p=>{const isRoot=p.id===root.id,isPrize=p.rank!==null,isSelected=selected===p.owner.id&&(isPrize?selectedRank===p.rank:selectedRank===null),colour=isRoot?'#087f65':palette[p.branch%palette.length],row=amounts.get(p.owner.id),amount=isPrize?row?.slots[p.rank!-1]:row?.amountWei,label=isPrize?`${c.rank} ${p.rank}`:p.owner.name,r=isRoot?53:isPrize?19:32,size=nodeSizes.get(p.id)!,glyphScale=size.scale,compactRoot=isRoot&&size.radius/labelScale<27,nodeFont=isRoot?11:isPrize?9:Math.min(10,(size.radius/labelScale*1.7)/(`${number(p.shareBps/100)}%`.length*.6));return <g key={p.id} data-node-id={p.id} data-depth={p.depth} data-level-highlight={activeLevel===null?undefined:p.depth===activeLevel} opacity={activeLevel===null||p.depth===activeLevel||isRoot?1:.4} transform={`translate(${p.x} ${p.y})`}>
  <g transform={`scale(${glyphScale})`} className={s.chartNode} role="button" tabIndex={0} aria-label={`${readOnly&&isPrize?`${p.owner.name} · `:''}${label}, ${number(p.shareBps/100)}%, ${setupAmount(amount??null,hr)} test MON`} aria-pressed={isSelected} aria-controls={inspectorId} onPointerDown={e=>startBranch(e,p)} onPointerEnter={()=>setHovered(p.id)} onPointerLeave={()=>setHovered(null)} onFocus={()=>setHovered(p.id)} onBlur={()=>setHovered(null)} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return;}select(p.owner.id,p.rank);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(p.owner.id,p.rank);}else if(!readOnly&&!isRoot&&!isPrize&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();moveBranch(p.id,e.key==='ArrowLeft'?-.2:.2);}}} aria-description={`${isRoot?(hr?'Središte · glavni fond':'Centre · main pot'):levelName(p.depth)}. ${!readOnly&&!isRoot&&!isPrize?(hr?'Povucite ili koristite lijevu i desnu strelicu za pomicanje na prstenu.':'Drag or use Left and Right arrows to move along the ring.'):''}`}>
   <circle r={r+4} fill="transparent"/>
   <circle r={r+6} fill={colour} opacity={isSelected?.18:.05}/><circle r={r} fill={isRoot?colour:'white'} stroke={colour} vectorEffect="non-scaling-stroke" strokeWidth={isSelected?2.5:1.2}/>
   {size.detail&&nodeFont>=8?<text textAnchor="middle" y={(isRoot&&!compactRoot?-4:4)*labelScale/glyphScale} fontSize={nodeFont*labelScale/glyphScale} fontWeight="700" fill={isRoot?'white':colour}>{isRoot?(compactRoot?(hr?'Fond':'Pot'):c.home):isPrize?`#${p.rank}`:`${number(p.shareBps/100)}%`}</text>:null}
   {isRoot&&!compactRoot?<text textAnchor="middle" y={15*labelScale/glyphScale} fill="white" fontSize={10*labelScale/glyphScale}>{setupAmount(amount??null,hr)}</text>:null}
   {!isRoot&&(size.labels||(p.depth===1&&canvasSize.width>=480))?<g transform={`scale(${labelScale/glyphScale})`}><text textAnchor="middle" y={p.depth===1?-size.radius/labelScale-12:size.radius/labelScale+19} fontSize="12" fontWeight="600" fill="#193536" stroke="#f5faf7" strokeWidth="3" paintOrder="stroke">{isPrize?`${number(p.shareBps/100)}%`:readOnly&&label.includes(' · ')?label.split(' · ').map((part,i)=><tspan key={i} x="0" dy={i?13:0}>{part.length>20?`${part.slice(0,19)}…`:part}</tspan>):label.length>25?`${label.slice(0,24)}…`:label}</text>{size.labels&&p.depth!==1?<text textAnchor="middle" y={size.radius/labelScale+34} fontSize="11" fill="#526f68" stroke="#f5faf7" strokeWidth="3" paintOrder="stroke">{setupAmount(amount??null,hr)} test MON</text>:null}</g>:null}<title>{`${hr?'Otvori detalje':'Open details'}: ${label} · ${number(p.shareBps/100)}% · ${setupAmount(amount??null,hr)} test MON`}</title>
  </g>
  {!readOnly&&!isRoot&&size.detail?<g pointerEvents="none" aria-hidden="true" transform={`translate(${-size.radius*.7-3*labelScale} ${-size.radius*.7-3*labelScale}) scale(${labelScale})`}><circle r="8" fill={activeLevel===p.depth?'#087f65':'#193f35'} stroke="white" strokeWidth="1.5"/><text textAnchor="middle" y="3" fontSize="9" fontWeight="700" fill="white">{p.depth}</text></g>:null}
  {!isPrize&&isSelected&&onAddChild&&canAddChild?.(p.owner.id)?<g className={s.chartNode} role="button" tabIndex={0} aria-label={`${hr?'Dodaj podfond u':'Add subpot to'} ${label}`} transform={`translate(${size.radius+10*labelScale} ${size.radius}) scale(${labelScale})`} onClick={()=>{setCollapsed(previous=>{const next=new Set(previous);next.delete(p.owner.id);return next;});onAddChild(p.owner.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setCollapsed(previous=>{const next=new Set(previous);next.delete(p.owner.id);return next;});onAddChild(p.owner.id);}}}><circle r="18" fill="#087f65" stroke="white" strokeWidth="2"/><text textAnchor="middle" y="6" fontSize="23" fill="white">+</text></g>:null}
  {!isPrize&&(p.owner.children.length>0||(showPrizes&&p.owner.rule))?<g className={s.chartNode} role="button" tabIndex={0} aria-label={`${collapsed.has(p.id)?(hr?'Proširi':'Expand'):(hr?'Sažmi':'Collapse')}: ${label}`} aria-expanded={!collapsed.has(p.id)} transform={`translate(${size.radius+9*labelScale} ${-size.radius}) scale(${Math.min(labelScale,glyphScale*1.3)})`} onClick={()=>toggle(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle(p.id);}}}><circle r="13" fill="white" stroke={colour}/><text textAnchor="middle" y="5" fontSize="18" fill={colour}>{collapsed.has(p.id)?'+':'−'}</text></g>:null}
 </g>;})}
 {!readOnly?levels.map(({depth,radius,labelAngle})=><g key={`label:${depth}`} aria-hidden="true" pointerEvents="none" transform={`translate(${Math.cos(labelAngle)*radius} ${Math.sin(labelAngle)*radius}) scale(${labelScale})`} opacity={activeLevel===null||activeLevel===depth?1:.4}><rect x={canvasSize.width<480?-18:-36} y="-12" width={canvasSize.width<480?36:72} height="24" rx="12" fill={activeLevel===depth?'#087f65':'#f5faf7'} stroke={activeLevel===depth?'#087f65':'#88a79b'}/><text textAnchor="middle" y="4" fontSize="11" fontWeight="700" fill={activeLevel===depth?'white':'#315d4f'}>{canvasSize.width<480?`${hr?'R':'L'}${depth}`:levelName(depth)}</text></g>):null}
 </svg>{detailPoint?<div className={s.chartDetails} aria-live="polite"><strong>{detailPoint.owner.name}{detailPoint.rank!==null?` · ${c.rank} ${detailPoint.rank}`:''}</strong><span>{detailPoint.depth?levelName(detailPoint.depth):c.home} · {number(detailPoint.shareBps/100)}% · {setupAmount(detailPoint.rank!==null?amounts.get(detailPoint.owner.id)?.slots[detailPoint.rank-1]??null:amounts.get(detailPoint.owner.id)?.amountWei??null,hr)} test MON</span></div>:null}{!root.children.length?<p className={s.empty}>{c.initial}</p>:null}</div><p className={s.graphHint}>{readOnly?(hr?'Odaberite krug za pregled iznosa. Povećajte prikaz ili povucite pozadinu.':'Select a circle to inspect amounts. Zoom or drag the background to explore.'):hr?'Kotačićem ili s dva prsta povećajte prikaz. Kliknite krug za detalje. Povucite pozadinu za pomicanje ili granu duž prstena. Postotci se odnose na roditeljski fond.':'Scroll or pinch to zoom. Click a circle to open its details. Drag the background to pan; drag branches along their rings. Percentages refer to the immediate parent pot.'}{totalPlaces>2000? (hr?' Veliki program: mjesta su prikazana u bočnom panelu.':' Large programme: prize places are listed in the side panel.'):''}</p></>:<div className={s.list}>{all.map(n=><button key={n.id} aria-current={selected===n.id} style={{paddingLeft:Math.min(setupPath(root,n.id).length-1,6)*16}} onClick={()=>select(n.id)}><span>{n.name}</span><span>{number(n.shareBps/100)}% · {setupAmount(amounts.get(n.id)?.amountWei??null,hr)}</span></button>)}</div>}
 <footer className={s.chartFooter}><button className={s.button} onClick={()=>{select(root.id);setCamera(null);}}>{c.home}</button><span className={s.small}>{all.length} {hr?'grana':'branches'} · {readOnly?rows.reduce((count,row)=>count+row.slots.filter(amount=>amount>0n).length,0):totalPlaces} {c.slots}</span></footer>
 </section>;
}
