import {useState,type ReactNode} from 'react';
import {previewRewardSetup,type RewardDistributionSetup} from '@raceson/domain/rewards/distribution-setup';
import {sponsorPotBranches,splitSponsorSections,splitSponsorRoundsEqually,setSponsorRoundShare} from '../model/sponsorBudget';
import {setupAmount} from '../model/setupAmount';
import RewardSetupPolicy from './RewardSetupPolicy';
import s from './SponsorExact.module.css';
import SponsorAllocationRow from './SponsorAllocationRow';
type Props={configuration:RewardDistributionSetup;onChange:(value:RewardDistributionSetup)=>void;stage:'pot'|'rounds';raceSlot?:number;allocation?:ReactNode;onNavigate:(target:'pot'|'rounds'|number)=>void;disabled:boolean;readOnly?:boolean;hr:boolean};
export default function SponsorFundingWorkspace({configuration:c,onChange,disabled,hr,raceSlot,allocation}:Props){
 const t=(a:string,b:string)=>hr?b:a,[error,setError]=useState('');
 const {league,rounds,roundsBps}=sponsorPotBranches(c),locked=disabled||c.root.children.some(n=>n.locked);
 let preview:ReturnType<typeof previewRewardSetup>|null=null;try{preview=previewRewardSetup(c);}catch{/* Keep invalid input editable. */}
 const apply=(fn:()=>RewardDistributionSetup)=>{if(locked)return;try{onChange(fn());setError('');}catch{setError(t('Check the amount and available pot.','Provjerite iznos i raspoloživi fond.'));}};
 const nodes=[league,...rounds];
 return <section id="funding-inspector" aria-label={t('Sponsor pot setup','Postavljanje sponzorskog fonda')}><div className={s.fields}><label className={s.field}>{t('Campaign name','Naziv kampanje')}<input aria-label={t('Campaign name','Naziv kampanje')} maxLength={100} value={c.name} disabled={disabled} onChange={e=>onChange({...c,name:e.target.value})}/><small className={s.hint}>{t('Shown on your public campaign.','Prikazano na javnoj kampanji.')}</small></label><label className={s.field}>{t('Selected prize pool','Odabrani fond nagrada')}<span><input aria-label={t('Total budget · test MON','Ukupni fond · test MON')} inputMode="decimal" placeholder="0" value={c.budgetMon} disabled={disabled} onChange={e=>onChange({...c,budgetMon:e.target.value})}/><b>test MON</b></span><small className={s.hint}>{t('The exact prize amount you will deposit. RacesOn pays creation gas.','Točan fond koji ćete uplatiti. RacesOn plaća izradu.')}</small></label></div>{allocation}{!raceSlot?<><div className={s.sectionHeading}><div><h2>{t('Allocate the prize pool','Raspodijelite fond nagrada')}</h2><p className={s.hint}>{t('Each percentage is a share of the','Svaki postotak je udio u fondu od')} <strong>{setupAmount(preview?.budgetWei??null,hr)} test MON</strong>. {t('Use the slider, percentage or test MON amount. Amounts round to 0.01% of the pool.','Koristite klizač, postotak ili iznos test MON. Iznosi se zaokružuju na 0,01% fonda.')}</p></div>{allocation}{!raceSlot?<button className={s.outline} disabled={locked} onClick={()=>apply(()=>splitSponsorRoundsEqually(c))}>{t('Split rounds equally','Podijeli kola jednako')}</button>:null}</div><div className={s.allocation}><p className={s.allocationLabel}>{t('League & races','Liga i utrke')}</p>{nodes.map(n=><SponsorAllocationRow key={n.id} name={n.name} shareBps={n.shareBps} amountWei={preview?.rows.find(r=>r.id===n.id)?.amountWei??null} budgetMon={c.budgetMon} maxShareBps={n.id===league.id?10000:roundsBps} disabled={locked} hr={hr} onToggle={checked=>apply(()=>n.id===league.id?splitSponsorSections(c,checked?5000:0):setSponsorRoundShare(c,n.id,checked?Math.floor(10000/rounds.length):0))} onShare={shareBps=>apply(()=>n.id===league.id?splitSponsorSections(c,shareBps):setSponsorRoundShare(c,n.id,roundsBps?Math.round(shareBps*10000/roundsBps):0))}/>)}<div className={s.allocated}><span>{t('Allocated','Raspoređeno')}</span><span>{(league.shareBps+roundsBps)/100}% ✓</span></div></div></>:null}<RewardSetupPolicy compact hr={hr} policy={c.policy} disabled={disabled} onChange={policy=>onChange({...c,policy})}/>{error?<p role="alert">{error}</p>:null}</section>;
}
