import DirectClubClaims from "./DirectClubClaims";
import {publicEnv} from '@/lib/public-env';
import {getHostedClubAwards} from '../data/hostedClubClaims';
import {walletActionLabel} from "../model/walletActionLabel";
import SponsorClaimTerms from "./SponsorClaimTerms";
import RewardClaimDialog from "./RewardClaimDialog";
import RewardClaimProgress from "./RewardClaimProgress";
import RewardClaimFilters,{type ClaimFilter} from "./RewardClaimFilters";
import roleStyle from "./RewardRoleWorkspace.module.css";
import {useCallback,useEffect,useRef,useState} from "react";
import type {Hex} from "viem";
import {sponsorClubAwards,sponsorClubClaim,type SponsorClubAward,type SponsorClubClaim} from "../data/sponsorClubClaims";
import {getClubTreasuryHistory} from "../data/clubTreasuries";
import {combineSponsorClubSignatures,signSponsorClubConsent} from "../data/sponsorClubWallet";
import {signProgrammeClaim,sendProgrammeTransaction} from "../data/sponsorProgrammeWallet";
import type {DetectedRewardWallet} from "../data/browserWallet";
import SponsorWallet from "./SponsorWallet";
import {setupAmount} from "../model/setupAmount";
import s from "./SponsorLaunch.module.css";
type Role="recipient"|"operator";
export default function SponsorClubClaims({role,approvalId,hr,chainId,onAccessError}:{role:Role;approvalId?:string;hr:boolean;chainId:number;onAccessError?:(error:unknown)=>void}){
 const hosted=!!publicEnv.hostedOperations&&role==='recipient';
 const [cursor,setCursor]=useState<string|null>(null);
 const [sort,setSort]=useState("pot"),[filter,setFilter]=useState<ClaimFilter>("all");
 const [awards,setAwards]=useState<SponsorClubAward[]>([]),[nominations,setNominations]=useState<Awaited<ReturnType<typeof getClubTreasuryHistory>>["items"]>([]);
 const [selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 const active=useRef(true),flight=useRef(false),requests=useRef(new Map<string,string>()),t=(en:string,local:string)=>hr?local:en;
 const failed=useCallback((e:unknown)=>{if(active.current){setError(true);if(e&&typeof e==="object"&&"status"in e&&[401,403].includes(Number(e.status)))onAccessError?.(e);}},[onAccessError]);
 const load=useCallback(async(after:string|null=null)=>{setBusy(true);setError(false);setCursor(null);if(after===null)setAwards([]);try{const page=hosted?await getHostedClubAwards(after):{items:await sponsorClubAwards(role,approvalId),nextCursor:null};const a=page.items,all:typeof nominations=[];
  if(role==="recipient"&&a.some(item=>item.protocolVersion!==5)){let cursor:string|null=null;do{const page=await getClubTreasuryHistory(cursor);all.push(...page.items);cursor=page.nextCursor;}while(cursor&&active.current);}
  if(active.current){setAwards(old=>after?[...old,...a]:a);setCursor(page.nextCursor);setNominations(all);}}catch(e){if(active.current){setAwards([]);setCursor(null);}failed(e);}finally{if(active.current)setBusy(false);}},[role,approvalId,failed,hosted]);
 useEffect(()=>{active.current=true;void load();return()=>{active.current=false;};},[load]);
 async function request(a:SponsorClubAward,requestId:string){if(flight.current)return;flight.current=true;setBusy(true);setError(false);
  const key=`${a.entitlementId}:${requestId}`;if(!requests.current.has(key))requests.current.set(key,crypto.randomUUID());const id=requests.current.get(key)!;
  try{await sponsorClubClaim(role,id,{action:"request",approvalId:a.approvalId,entitlementId:a.entitlementId,requestId});requests.current.delete(key);if(active.current){setSelected(id);await load();}}
  catch(e){failed(e);}finally{flight.current=false;if(active.current)setBusy(false);}}
 const ordered=awards.filter(a=>a.protocolVersion!==5).sort((a,b)=>{if(sort==="amount"){const x=BigInt(a.amountWei),y=BigInt(b.amountWei);if(x!==y)return x>y?-1:1;}if(sort==="unclaimed"){const delta=Number(a.claims.some(c=>c.paid))-Number(b.claims.some(c=>c.paid));if(delta)return delta;}return a.slot-b.slot||a.entitlementId.localeCompare(b.entitlementId);});
 const visible=ordered.filter(a=>filter==="all"||(filter==="paid")===a.claims.some(c=>c.paid));
 return <section className={`${s.card} ${roleStyle.awards}`} aria-label={t("Sponsor club rewards","Sponzorske klupske nagrade")}><div className={s.claimHeading}><h2>{t("Club reward claims","Preuzimanje klupskih nagrada")}</h2>

 <div className={s.claimTools}><label>{t("Sort","Poredaj")}<select aria-label={t("Sort club rewards","Poredaj klupske nagrade")} value={sort} onChange={e=>setSort(e.target.value)}><option value="pot">{t("Prize pot","Fond nagrada")}</option><option value="amount">{t("Highest reward","Najveća nagrada")}</option><option value="unclaimed">{t("Unclaimed first","Nepreuzeto prvo")}</option></select></label><button className={s.secondary} disabled={busy} onClick={()=>void load()}>{t("Refresh club claims","Osvježi klupska preuzimanja")}</button></div></div>
 {awards.some(a=>a.protocolVersion===5)?<DirectClubClaims awards={awards.filter(a=>a.protocolVersion===5)} hr={hr} onRefresh={load} onAccessError={onAccessError}/>:null}
 {ordered.length?<details className={s.details}><summary>{t("Wallet & consent requirements","Uvjeti novčanika i pristanka")}</summary><p>{t("Awards stay in the contract until claimed. The club owner requests a claim; two of the three reviewed Safe owners give consent. The controller confirms the payment.","Nagrade ostaju u ugovoru do preuzimanja. Vlasnik kluba podnosi zahtjev; dva od tri potvrđena vlasnika Safea daju pristanak. Kontrolor potvrđuje isplatu.")}</p></details>:null}
 {error?<p role="alert">{t("Club claims could not be verified. Refresh to try again.","Klupska preuzimanja nije moguće potvrditi. Osvježite za novi pokušaj.")}</p>:null}
 {!busy&&!error&&!awards.length?<p>{t("No published club awards for this account yet.","Još nema objavljenih klupskih nagrada za ovaj račun.")}</p>:null}
 <RewardClaimFilters value={filter} onChange={setFilter} total={ordered.length} paid={ordered.filter(a=>a.claims.some(c=>c.paid)).length} hr={hr}/><div className={s.claimRows}>{visible.map(a=>{const matching=nominations.filter(n=>n.clubId===a.clubId&&n.chainId===chainId&&n.status==="pending_review");return <div className={s.claimRow} key={a.entitlementId}>
 <div><strong>{a.slot===0?t("League","Liga"):`${t("Round","Kolo")} ${a.slot}`}</strong><span className={s.claimAmount}>{setupAmount(BigInt(a.amountWei),hr)} <small>test MON</small></span><span className={s.claimState} data-paid={a.claims.some(c=>c.paid)}>{a.claims.some(c=>c.paid)?t("Paid","Isplaćeno"):t("Unclaimed","Nepreuzeto")}</span></div><div className={s.claimActions}>
 {a.claims.map(c=><button className={s.secondary} key={c.id} disabled={busy} onClick={()=>setSelected(c.id)}>{c.paid?t("View payment","Pregledaj isplatu"):c.consented?t("Club consent recorded · view claim","Klupski pristanak spremljen · pregledaj"):c.prepared?t("Review & sign club consent","Pregledaj i potpiši klupski pristanak"):t("Awaiting treasury review","Čeka provjeru riznice")}</button>)}
 {role==="recipient"&&!a.claims.some(c=>c.paid)?matching.length?matching.map(n=><button key={n.requestId} className={s.primary} disabled={busy} onClick={()=>void request(a,n.requestId)}>{t("Request to club Safe","Zatraži na klupski Safe")} {n.candidate.safeAddress.slice(0,8)}…{n.candidate.safeAddress.slice(-4)}</button>):<p>{t("Nominate your club’s 2-of-3 Safe in Club and treasury. Your award stays reserved.","Predložite klupski Safe s dva od tri potpisa u odjeljku Klub i riznica. Nagrada ostaje rezervirana.")}</p>:null}
 </div></div>;})}</div>
 {!busy&&!error&&ordered.length>0&&!visible.length?<p role="status" className={roleStyle.empty}>{t("No rewards in this view. Choose All awards to see the rest.","Nema nagrada u ovom prikazu. Odaberite Sve nagrade za ostale.")}</p>:null}
 {cursor&&!error?<button className={s.secondary} disabled={busy} onClick={()=>void load(cursor)}>{t('Load more club rewards','Učitaj još klupskih nagrada')}</button>:null}
 {selected?<RewardClaimDialog club hr={hr} onClose={()=>{setSelected(null);void load();}}>{onBusy=><SponsorClubClaimDetail key={selected} id={selected} role={role} hr={hr} chainId={chainId} onAccessError={onAccessError} onBusy={onBusy} onDone={()=>{setSelected(null);void load();}}/>}</RewardClaimDialog>:null}</section>;
}
export function SponsorClubClaimDetail({id,role,hr,chainId,onAccessError,onDone,onBusy,claimRequest,reviewerOnly=false}:{claimRequest?:(id:string,body?:unknown)=>Promise<SponsorClubClaim>;reviewerOnly?:boolean;id:string;role:Role;hr:boolean;chainId:number;onAccessError?:(error:unknown)=>void;onDone?:()=>void;onBusy?:(busy:boolean)=>void}){
 const request=useCallback((body?:unknown)=>claimRequest?claimRequest(id,body):sponsorClubClaim(role,id,body),[claimRequest,id,role]);
 const [view,setView]=useState<SponsorClubClaim|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[ack,setAck]=useState(false);
 const [wallet,setWallet]=useState<{wallet:DetectedRewardWallet;address:string}|null>(null),[proofs,setProofs]=useState<{signer:string;signature:Hex}[]>([]),[pending,setPending]=useState<string|null>(null);
 const [evidence,setEvidence]=useState({factoryAddress:"",deploymentTransactionHash:"",authorityEvidenceRef:"",controlEvidenceRef:"",recoveryEvidenceRef:"",executionHistoryEvidenceRef:""});
 const active=useRef(true),flight=useRef(false),walletRef=useRef(wallet),signature=useRef<string|null>(null);walletRef.current=wallet;
 useEffect(()=>{onBusy?.(busy);},[busy,onBusy]);
 const t=(en:string,local:string)=>hr?local:en,storage=`raceson:sponsor-club-claim:${chainId}:${id}`;
 const choose=useCallback((w:typeof wallet)=>{setWallet(w);setAck(false);},[]);
 const load=useCallback(async()=>{const v=await request();if(active.current){setView(v);setAck(false);setProofs([]);signature.current=null;}},[request]);
 const run=useCallback(async(work:()=>Promise<void>)=>{if(flight.current)return;flight.current=true;setBusy(true);setError(false);try{await work();}catch(e){if(active.current){setView(null);setAck(false);setProofs([]);signature.current=null;setError(true);if(e&&typeof e==="object"&&"status"in e&&[401,403].includes(Number(e.status)))onAccessError?.(e);}}finally{flight.current=false;if(active.current)setBusy(false);}},[onAccessError]);
 useEffect(()=>{active.current=true;try{const h=sessionStorage.getItem(storage);if(h&&/^0x[0-9a-f]{64}$/.test(h))setPending(h);}catch{/* Optional recovery. */}void run(load);return()=>{active.current=false;};},[load,run,storage]);
 async function fresh(){const v=await request();if(!view||JSON.stringify(v.claim)!==JSON.stringify(view.claim)||JSON.stringify(v.signing)!==JSON.stringify(view.signing)||JSON.stringify(v.owners)!==JSON.stringify(view.owners)||!v.current)throw Error("claim_changed");return v;}
 async function sign(){if(!wallet||!ack)return;const v=await fresh();
  if(role==="recipient"){if(proofs.some(p=>p.signer===wallet.address)||proofs.length>=2)throw Error("club_duplicate_signer");const proof=await signSponsorClubConsent(wallet.wallet.provider,v,wallet.address,()=>active.current&&walletRef.current===wallet);
   await fresh();if(active.current){setProofs(old=>[...old,{signer:wallet.address,signature:proof}]);setAck(false);}}
  else{signature.current??=await signProgrammeClaim(wallet.wallet.provider,v,()=>active.current&&walletRef.current===wallet);const next=await request({action:"operator",signature:signature.current});if(active.current){signature.current=null;setView(next);setAck(false);}}}
 async function submitConsent(){const v=await fresh(),signature=await combineSponsorClubSignatures(v,proofs);await fresh();const next=await request({action:"recipient",signature});if(active.current){setView(next);setProofs([]);setAck(false);}}
 async function send(){if(!view||!wallet||pending)return;const v=await fresh();if(JSON.stringify(v.transaction)!==JSON.stringify(view.transaction))throw Error("claim_changed");
  const hash=await (wallet.wallet.sendProgrammeTransaction?wallet.wallet.sendProgrammeTransaction(v,()=>active.current&&walletRef.current===wallet):sendProgrammeTransaction(wallet.wallet.provider,v,()=>active.current&&walletRef.current===wallet));
  try{sessionStorage.setItem(storage,hash);}catch{/* Keep receipt visible. */}if(active.current)setPending(hash);}
 return <section className={s.card}><h3>{t("Club claim details","Podaci klupskog preuzimanja")}</h3>
 <button className={s.secondary} disabled={busy} onClick={()=>void run(load)}>{t("Refresh claim","Osvježi preuzimanje")}</button>
 {error?<p role="alert">{t("The claim or wallet could not be verified. Refresh before continuing.","Preuzimanje ili novčanik nije moguće potvrditi. Osvježite prije nastavka.")}</p>:null}
 {view?<><dl className={roleStyle.claimFacts}>{view.claim?<div><dt>{t("Exact reward","Točna nagrada")}</dt><dd className={roleStyle.amount}>{setupAmount(BigInt(view.claim.amount),hr)} <small>test MON</small></dd></div>:null}<div><dt>{t("Club treasury","Klupska riznica")}</dt><dd className={s.address}>{view.address}</dd></div><div><dt>{t("Network","Mreža")}</dt><dd>{chainId===31337?t("Local simulation · 31337","Lokalna simulacija · 31337"):"Monad testnet · 10143"}</dd></div></dl><RewardClaimProgress view={view} pending={pending} hr={hr} club/><SponsorClaimTerms view={view} hr={hr}/>
 <p role="status">{({awaiting_review:t("Treasury review pending","Čeka provjeru riznice"),held:t("On hold · award reserved","Na čekanju · nagrada rezervirana"),awaiting_consent:t("Waiting for two Safe owner signatures","Čeka potpise dva vlasnika Safea"),awaiting_operator:t("Club consent recorded · waiting for controller","Klupski pristanak spremljen · čeka kontrolora"),ready_to_pay:t("Ready for confirmed payment","Spremno za potvrđenu isplatu"),paid:t("Payment confirmed","Isplata potvrđena")})[view.status]}</p>
 {role==="operator"&&view.status==="awaiting_review"?<details open><summary>{t("Review the club treasury","Provjeri klupsku riznicu")}</summary><p>{t("Reference existing club authority, independent owner control, recovery and Safe execution-history reviews. The original Safe deployment and current 2-of-3 configuration are verified on chain.","Navedite postojeće provjere klupske ovlasti, neovisne kontrole vlasnika, oporavka i povijesti izvršenja Safea. Izvorno postavljanje Safea i trenutno pravilo dva od tri potpisa provjeravaju se na lancu.")}</p>
 {Object.entries(evidence).map(([key,value])=><label className={s.field} key={key}>{({factoryAddress:t("Safe factory address","Adresa tvornice Safea"),deploymentTransactionHash:t("Safe creation transaction","Transakcija stvaranja Safea"),authorityEvidenceRef:t("Club authority review reference","Referenca provjere klupske ovlasti"),controlEvidenceRef:t("Owner control review reference","Referenca provjere kontrole vlasnika"),recoveryEvidenceRef:t("Recovery review reference","Referenca provjere oporavka"),executionHistoryEvidenceRef:t("Execution history review reference","Referenca provjere povijesti izvršenja")})[key]}<input value={value} onChange={e=>setEvidence({...evidence,[key]:e.target.value.trim()})}/></label>)}
 <button className={s.primary} disabled={busy||Object.values(evidence).some(v=>!v)} onClick={()=>void run(async()=>{const next=await request({action:"prepare",sourceStamp:view.sourceStamp,profileFingerprint:view.profileFingerprint,attestation:evidence});if(active.current)setView(next);})}>{t("Verify & prepare club claim","Provjeri i pripremi klupsko preuzimanje")}</button></details>:null}
 {!reviewerOnly&&view.current&&(view.signing||view.transaction)?<><SponsorWallet compact purpose={role} requiredAddress={role==="operator"?view.operatorAddress:undefined} chainId={chainId} hr={hr} onWallet={choose}/>
 {view.signing?<><label className={roleStyle.consent}><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>{role==="recipient"?t("I consent to this exact reward being paid to the club Safe.","Pristajem na isplatu ove točne nagrade na klupski Safe."):t("I approve this exact club reward and Safe destination.","Odobravam ovu točnu klupsku nagradu i Safe odredište.")}</label>
 <button className={s.primary} disabled={busy||!ack||!wallet||(role==="recipient"?!view.owners.includes(wallet.address)||proofs.some(p=>p.signer===wallet.address)||proofs.length>=2:wallet.address!==view.operatorAddress)} onClick={()=>void run(sign)}>{walletActionLabel(role==="recipient"?t("Sign as Safe owner","Potpiši kao vlasnik Safea"):t("Sign controller approval","Potpiši odobrenje kontrolora"),wallet?.wallet)}</button>
 {role==="recipient"?<><p>{proofs.length}/2 {t("owner signatures collected. Connect a different reviewed owner for the second signature.","potpisa vlasnika prikupljeno. Povežite drugog potvrđenog vlasnika za drugi potpis.")}</p><ul className={roleStyle.ownerList} aria-label={t("Safe owner signatures","Potpisi vlasnika Safea")}>{view.owners.map((owner,index)=><li key={owner}><div><strong>{t("Safe owner","Vlasnik Safea")} {index+1}</strong><code>{owner.slice(0,8)}…{owner.slice(-6)}</code></div><span data-signed={proofs.some(p=>p.signer===owner)}>{proofs.some(p=>p.signer===owner)?t("Signature collected","Potpis prikupljen"):t("Not signed here","Ovdje nije potpisano")}</span></li>)}</ul><button className={s.primary} disabled={busy||proofs.length!==2} onClick={()=>void run(submitConsent)}>{t("Submit club consent","Pošalji klupski pristanak")}</button></>:null}</>:null}
 {view.transaction?<button className={s.primary} disabled={busy||!wallet||!!pending||wallet.address!==view.operatorAddress} onClick={()=>void run(send)}>{walletActionLabel(t("Confirm club reward payment","Potvrdi isplatu klupske nagrade"),wallet?.wallet)}</button>:null}</>:null}
 {role==="operator"&&view.current&&view.status!=="paid"?<button className={s.secondary} disabled={busy} onClick={()=>void run(async()=>{const next=await request({action:"revoke"});if(active.current)setView(next);})}>{t("Hold this claim","Zaustavi ovo preuzimanje")}</button>:null}
 {view.receipt?<div className={roleStyle.receipt}><details><summary>{t("Receipt details","Podaci potvrde")}</summary><p className={s.address}>{t("Confirmed transaction","Potvrđena transakcija")}: {view.receipt.transactionHash} · {t("block","blok")} {view.receipt.blockNumber}</p></details>{view.status==="paid"&&onDone?<button type="button" className={s.primary} disabled={busy} onClick={onDone}>{t("Done","Gotovo")}</button>:null}</div>:null}</>:null}
 {!reviewerOnly&&pending?<div role="status" className={roleStyle.pending}><p>{t("Transaction submitted · payment not yet confirmed","Transakcija poslana · isplata još nije potvrđena")}</p><p className={s.address}>{pending}</p><button className={s.secondary} disabled={busy} onClick={()=>void run(async()=>{const next=await request({action:"receipt",transactionHash:pending});try{sessionStorage.removeItem(storage);}catch{/* Optional recovery. */}if(active.current){setView(next);setPending(null);}})}>{t("Verify payment receipt","Provjeri potvrdu isplate")}</button></div>:null}
 </section>;
}
