import {Link,useSearchParams} from "react-router-dom";
import type {useSponsorSource} from "../model/useSponsorSource";
import {sponsorDiscoveryLink} from "../model/sponsorOpportunities";
export default function SponsorSourceStatus({state,hr,readOnly=false}:{state:ReturnType<typeof useSponsorSource>;hr:boolean;readOnly?:boolean}) {
 const t=(en:string,local:string)=>hr?local:en;
 const [search]=useSearchParams();
 if(state.status==="ready")return <div><p>{t("Official event catalogue available.","Službeni katalog događaja je dostupan.")}</p><p>{readOnly?t("The official category catalogue is available for reference. Saved reward rules cannot be changed.","Službeni katalog kategorija dostupan je za pregled. Spremljena pravila nagrađivanja nije moguće mijenjati."):t("To connect an existing standings reward, open Rewards, select its existing group, then open Rules & prize breakdown and choose its Official category. Matching a category preserves that group’s budget and prizes. Participation rewards use the league’s contribution rules and do not need a category.","Za povezivanje postojeće nagrade za poredak otvorite Nagrade, odaberite postojeću grupu, zatim otvorite Pravila i iznosi nagrada i odaberite Službenu kategoriju. Povezivanje čuva fond i nagrade te grupe. Nagrade za sudjelovanje koriste pravila doprinosa lige i ne trebaju kategoriju.")}</p></div>;
 if(state.status==="unselected")return <p><Link to={sponsorDiscoveryLink(search.get("setup"))}>{t("Choose an event to sponsor","Odaberite događaj za sponzorstvo")}</Link></p>;
 if(state.status==="signin")return <p>{t("Sign in to verify this event’s current categories.","Prijavite se za provjeru aktualnih kategorija ovog događaja.")}</p>;
 if(state.status==="loading")return <p role="status">{t("Loading the selected event’s official categories…","Učitavanje službenih kategorija odabranog događaja…")}</p>;
 if(state.status==="unpublished")return <p role="status">{t("This event’s sponsorship catalogue is not available yet. You can save your event selection and budget. RacesOn must publish its source mapping before contract creation.","Katalog sponzorstva ovog događaja još nije dostupan. Možete spremiti odabir događaja i fond. RacesOn mora objaviti poveznice izvora prije stvaranja ugovora.")} <button onClick={state.retry}>{t("Check again","Provjeri ponovno")}</button></p>;
 if(state.status==="settings")return <p role="alert">{t("Enter a valid campaign budget and name to finish connecting this event.","Unesite valjan fond i naziv kampanje za dovršetak povezivanja događaja.")}</p>;
 return <p role="alert">{state.status==="changed"||state.status==="locked"?t("The saved campaign’s source needs review. Its existing rules have been preserved.","Izvor spremljene kampanje treba pregled. Postojeća pravila su sačuvana."):state.status==="invalid"?t("This event link is incomplete. Open the event from the catalogue.","Poveznica događaja nije potpuna. Otvorite događaj iz kataloga."):t("This event’s official categories could not be loaded.","Službene kategorije ovog događaja nije moguće učitati.")}{state.status!=="invalid"?<button onClick={state.retry}>{t("Try again","Pokušaj ponovno")}</button>:null}</p>;
}
