import PodiumPrizeCurve from "./PodiumPrizeCurve";
import {identifySponsorCurve,sponsorPrizeShares,type SponsorPrizeCurve} from "../model/sponsorPrizeCurves";
import {setupAmount} from "../model/setupAmount";
import s from "./RewardSetup.module.css";
import g from "./GuidedRewardSetup.module.css";

export default function SponsorPrizeEditor({name,shares,slots,disabled,hr,onChange}:{name:string;shares:number[];slots:bigint[];disabled:boolean;hr:boolean;onChange:(shares:number[])=>void}){
  const curve=identifySponsorCurve(shares),t=(en:string,local:string)=>hr?local:en;
  return <div className={g.prizeEditor}><div className={g.controls}><label className={s.field}>{t("Number of winners","Broj dobitnika")}<input aria-label={`${name} ${t("prize positions","nagrađena mjesta")}`} type="number" min="1" max="100" step="1" value={shares.length} disabled={disabled} onChange={e=>{if(e.target.value!==""&&e.target.validity.valid)onChange(sponsorPrizeShares(Number(e.target.value),curve==="custom"?"descending":curve));}}/></label><label className={s.field}>{t("Winner distribution","Raspodjela dobitnicima")}<select aria-label={`${name} ${t("winner distribution","raspodjela dobitnicima")}`} disabled={disabled} value={curve} onChange={e=>{if(e.target.value!=="custom")onChange(sponsorPrizeShares(shares.length,e.target.value as SponsorPrizeCurve));}}><option value="equal">{t("Equal prizes","Jednake nagrade")}</option><option value="descending">{t("Gradually decreasing","Postupno opadajuće")}</option><option value="exponential">{t("Larger top prizes","Veće nagrade vodećima")}</option><option value="custom" disabled>{t("Custom percentages","Prilagođeni postoci")}</option></select></label></div><PodiumPrizeCurve shares={shares} slots={slots} hr={hr}/><details className={g.details}><summary>{t("Preview prizes","Pregled nagrada")}</summary><ol className={g.prizePreview} aria-label={`${name} ${t("prize preview","pregled nagrada")}`}>{shares.slice(0,5).map((share,i)=><li key={i}><span>#{i+1}</span><div><span style={{width:`${share/Math.max(...shares,1)*100}%`}}/></div><strong>{share/100}%</strong><span>{setupAmount(slots[i]??null,hr)} test MON</span></li>)}</ol>{shares.length>5?<p className={s.small}>+ {shares.length-5} {t("places in exact distribution","mjesta u točnoj raspodjeli")}</p>:null}</details></div>;
}
