import PodiumPrizeCurve from "./PodiumPrizeCurve";
import {BarChart3,Equal,TrendingDown,Trash2,ArrowUpDown} from "lucide-react";
import {useState} from "react";
import {previewRewardSetup,type RewardDistributionSetup,type RewardSetupNode,type SetupPreviewRow} from "@raceson/domain/rewards/distribution-setup";
import {categoryAllocationLimit} from "../model/sponsorCategoryAllocation";
import {sponsorAmountShare,sponsorBudgetAmount} from "../model/sponsorBudget";
import type {GuidedRewardGroup} from "@raceson/domain/rewards/guided-setup";
import {isParticipationType} from "@raceson/domain/rewards/guided-setup";
import type {RewardSourceCatalogueV2} from "@raceson/domain/rewards/source-mapping-v2";
import {guidedCategories} from "@raceson/domain/rewards/guided-setup-editor";
import {identifySponsorCurve,sponsorPrizeShares,type SponsorPrizeCurve} from "../model/sponsorPrizeCurves";
import {setupAmount} from "../model/setupAmount";
import s from "./SponsorStudio.module.css";

export default function SponsorGroupEditor({node,group,configuration,catalogue,roundId,row,hr,disabled,onNode,onGroup,onMethod,onConnect,onRemove,rulesOnly=false}:{node:RewardSetupNode;group:GuidedRewardGroup;configuration:RewardDistributionSetup;catalogue:RewardSourceCatalogueV2|null;roundId:string|null;row:SetupPreviewRow|undefined;hr:boolean;disabled:boolean;onNode:(update:(n:RewardSetupNode)=>RewardSetupNode)=>void;onGroup:(update:Partial<GuidedRewardGroup>)=>void;onMethod:(method:GuidedRewardGroup["method"])=>void;onConnect:(id:string|null)=>void;onRemove:()=>void;rulesOnly?:boolean}){
 const t=(en:string,local:string)=>hr?local:en,shares=node.rule!.sharesBps;
 const [sort,setSort]=useState<'place'|'share'|'amount'>('place'),[descending,setDescending]=useState(false);
 const changeSort=(key:typeof sort)=>{setSort(key);setDescending(sort===key?!descending:false);};
 const prizeRows=shares.map((share,i)=>({share,i})).sort((a,b)=>{const x=sort==='place'?a.i:sort==='share'?a.share:row?.slots[a.i]??0n,y=sort==='place'?b.i:sort==='share'?b.share:row?.slots[b.i]??0n;return (descending?-1:1)*(x<y?-1:x>y?1:0)||a.i-b.i;});
 const sortButton=(key:typeof sort,label:string)=><button type="button" aria-pressed={sort===key} aria-label={`${t("Sort prizes by", "Poredaj nagrade po")} ${label}`} onClick={()=>changeSort(key)}>{label}<ArrowUpDown size={13}/></button>;
 const curve=shares.length?identifySponsorCurve(shares):"equal";
 const setCount=(count:number)=>onNode(n=>({...n,rule:{...n.rule!,sharesBps:sponsorPrizeShares(count,curve==="custom"?"descending":curve)}}));
 const participation=isParticipationType(group.type);
 const [amountError,setAmountError]=useState(false),parent=configuration.root.children.find(n=>n.children.some(child=>child.id===node.id));
 const allocationMax=categoryAllocationLimit(parent?.children??[],node.id),allocationFixed=node.locked||(parent?.children.filter(n=>!n.locked).length??0)<2;
 let parentAmount:bigint|null=null;try{parentAmount=previewRewardSetup(configuration).rows.find(n=>n.id===parent?.id)?.amountWei??null;}catch{/* Keep invalid input editable. */}
 return <section className={s.groupEditor} aria-label={node.name} id={`sponsor-group-editor-${node.id}`} tabIndex={-1}>
  <div className={s.sectionTitle}><h3>{node.name}</h3>{!rulesOnly?<button className={s.iconButton} disabled={disabled||node.locked} aria-label={`${t("Remove","Ukloni")} ${node.name}`} onClick={onRemove}><Trash2 size={18}/></button>:null}</div>
  {!rulesOnly&&parent?.children.length===1&&node.shareBps===10000?<div className={s.singleCategoryBudget}><span>{t("This category receives 100%","Ova kategorija prima 100%")}</span><strong>{setupAmount(row?.amountWei??null,hr)} test MON</strong><p>{parent.name} · {t("Include another category to split this prize budget.","Uključite još jednu kategoriju za podjelu ovog fonda.")}</p></div>:null}
  {!rulesOnly&&(parent?.children.length!==1||node.shareBps!==10000)?<><div className={s.groupBudget}><label>{t("Category budget","Fond kategorije")}<span className={s.unit}><input aria-label={`${node.name} ${t("budget","fond")} %`} type="number" min="0" max={allocationMax/100} step="0.01" disabled={disabled||allocationFixed} value={node.shareBps/100} onChange={e=>{if(e.target.value!==""&&Number.isFinite(e.target.valueAsNumber))onNode(n=>({...n,shareBps:Math.round(e.target.valueAsNumber*100)}));}}/><span>%</span></span></label><label className={s.categoryAmount}><input aria-label={`${node.name} test MON`} inputMode="decimal" key={String(row?.amountWei)} defaultValue={sponsorBudgetAmount(row?.amountWei??null)} disabled={disabled||allocationFixed||!parentAmount||row?.amountWei==null} onBlur={e=>{const input=e.currentTarget;if(input.value===input.defaultValue)return;try{const shareBps=sponsorAmountShare(input.value,sponsorBudgetAmount(parentAmount));onNode(n=>({...n,shareBps}));setAmountError(false);}catch{setAmountError(true);}input.value=input.defaultValue;}}/><span>test MON</span></label></div>
  <div className={s.allocationControl}><label><span>{t("Share of this pot","Udio ovog fonda")} <b>{node.shareBps/100}%</b></span><input className={s.allocationSlider} type="range" min="0" max={allocationMax} step="1" value={node.shareBps} aria-label={`${node.name} ${t("allocation slider","klizač udjela")}`} aria-valuetext={`${node.shareBps/100}%`} disabled={disabled||allocationFixed} onChange={e=>onNode(n=>({...n,shareBps:Number(e.target.value)}))}/></label><button disabled={disabled||allocationFixed} onClick={()=>onNode(n=>({...n,shareBps:allocationMax}))}>{t("Use available","Iskoristi dostupno")}</button></div>
  {amountError?<p role="alert" className={s.notice}>{t("Enter an amount within this pot.","Unesite iznos unutar ovog fonda.")}</p>:null}
  </>:null}
  {participation?<div className={s.controls}><label>{t("Distribution","Raspodjela")}<select disabled={disabled} value={group.method} onChange={e=>onMethod(e.target.value as GuidedRewardGroup["method"])}><option value="proportional">{t("Share by contribution","Prema doprinosu")}</option><option value="ranked">{t("Reward highest totals","Najveći rezultati")}</option></select></label><label>{t("Minimum completed rounds","Najmanje završenih kola")}<select disabled={disabled} value={group.minimumFinishes} onChange={e=>onGroup({minimumFinishes:Number(e.target.value),eligibilityApproved:false})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label></div>:null}
  {group.method==="ranked"?<div className={s.prizeControls}><div><span className={s.label}>{t("Winners","Dobitnici")}</span><div className={s.presets} role="group" aria-label={`${node.name} ${t("winners","dobitnici")}`}>{[3,5,10,25].map(count=><button key={count} disabled={disabled} aria-pressed={shares.length===count} onClick={()=>setCount(count)}>{count}</button>)}</div><label className={s.customCount}>{t("Custom","Prilagođeno")}<input aria-label={`${node.name} ${t("prize positions","nagrađena mjesta")}`} type="number" min="1" max="100" value={shares.length} disabled={disabled} onChange={e=>{if(e.target.value!==""&&e.target.validity.valid)setCount(Number(e.target.value));}}/></label></div><div><span className={s.label}>{t("Prize split","Raspodjela nagrada")}</span><div className={s.curves} role="group" aria-label={`${node.name} ${t("prize split","raspodjela nagrada")}`}>{([["equal",t("Equal prizes","Jednake nagrade"),Equal],["descending",t("Gradually decreasing","Postupno opadajuće"),BarChart3],["exponential",t("Larger top prizes","Veće nagrade vodećima"),TrendingDown]] as const).map(([value,label,Icon])=><button key={value} disabled={disabled} aria-pressed={curve===value} onClick={()=>onNode(n=>({...n,rule:{...n.rule!,sharesBps:sponsorPrizeShares(shares.length,value as SponsorPrizeCurve)}}))}><Icon size={30}/><span>{label}</span></button>)}</div>{curve==="custom"?<small>{t("Custom percentages","Prilagođeni postoci")}</small>:null}</div></div>:null}
  {group.method==="ranked"?<div className={s.visiblePrizes}>
   <div className={s.prizeHeading}><h4>{t("Prizes by place","Nagrade po mjestu")}</h4><span data-invalid={shares.reduce((a,b)=>a+b,0)!==10000}>{shares.reduce((a,b)=>a+b,0)/100}% {t("allocated","raspoređeno")}</span></div>
   <div className={s.prizeSort} role="group" aria-label={t("Prize order","Redoslijed nagrada")}>{sortButton('place',t('Place','Mjesto'))}{sortButton('share','%')}{!rulesOnly?sortButton('amount','test MON'):null}</div>
   <div className={s.prizeGrid}>{prizeRows.map(({share,i})=><label className={s.prizeTile} key={i} data-podium={i<3}>
    <span className={s.prizeRank}>#{i+1}</span><span className={s.prizeInput}><input aria-label={`${node.name} #${i+1} %`} type="number" min="0" max="100" step="0.01" disabled={disabled} value={share/100} onChange={e=>{if(e.target.value!==""&&e.target.validity.valid)onNode(n=>({...n,rule:{...n.rule!,sharesBps:shares.map((v,j)=>i===j?Math.round(Number(e.target.value)*100):v)}}));}}/><span>%</span></span>
    {!rulesOnly?<strong>{setupAmount(row?.slots[i]??null,hr)} <small>test MON</small></strong>:null}
   </label>)}</div>
   <p className={s.hint}>{t("Ties share the combined prizes for occupied places.","Izjednačeni dijele zbroj nagrada zauzetih mjesta.")}</p>
   <details className={s.details}><summary>{t("View prize curve","Prikaži krivulju nagrada")}</summary><PodiumPrizeCurve shares={shares} slots={rulesOnly?undefined:row?.slots} hr={hr}/></details>
  </div>:<p className={s.hint}>{t("The pool is shared by verified contribution. No winner limit.","Fond se dijeli prema potvrđenom doprinosu. Bez ograničenja dobitnika.")}</p>}
  <details className={s.details}><summary>{t("Rules & prize breakdown","Pravila i iznosi nagrada")}</summary>
   {!rulesOnly?(!participation&&catalogue?<label>{t("Official category","Službena kategorija")}<select disabled={disabled||!catalogue} value={node.rule?.source?.categoryId??""} onChange={e=>onConnect(e.target.value||null)}><option value="">{t("Choose category","Odaberi kategoriju")}</option>{catalogue?guidedCategories(catalogue,roundId,group.type).map(cat=><option key={cat.id} value={cat.id}>{cat.competitionName} · {cat.name}</option>):null}</select></label>:!participation?<p>{t("The organizer connects official categories and reviews eligibility before launch.","Organizator povezuje službene kategorije i pregledava uvjete prije pokretanja.")}</p>:<p>{t("One approved finish per athlete per round. Club distance follows the represented club at each finish.","Jedan odobren završetak po sportašu u kolu. Klupska udaljenost pripada klubu zastupanom pri završetku.")}</p>):null}

  </details>
 </section>;
}
