import {useState} from 'react';
import {previewRewardSetup,type RewardDistributionSetup} from '@raceson/domain/rewards/distribution-setup';
import {sponsorPotBranches,splitSponsorSections,splitSponsorRoundsEqually,setSponsorRoundShare} from '../model/sponsorBudget';
import {setupAmount} from '../model/setupAmount';
import RewardSetupPolicy from './RewardSetupPolicy';
import s from './SponsorExact.module.css';
type Props={configuration:RewardDistributionSetup;onChange:(value:RewardDistributionSetup)=>void;stage:'pot'|'rounds';raceSlot?:number;eventName?:string;onNavigate:(target:'pot'|'rounds'|number)=>void;disabled:boolean;readOnly?:boolean;hr:boolean};
export default function SponsorFundingWorkspace({configuration:c,onChange,disabled,hr,raceSlot}:Props){
 const t=(a:string,b:string)=>hr?b:a,[error,setError]=useState('');
 const {league,rounds,roundsBps}=sponsorPotBranches(c),locked=disabled||c.root.children.some(n=>n.locked);
 let preview:ReturnType<typeof previewRewardSetup>|null=null;try{preview=previewRewardSetup(c);}catch{/* Keep invalid input editable. */}
 const apply=(fn:()=>RewardDistributionSetup)=>{if(locked)return;try{onChange(fn());setError('');}catch{setError(t('Check the amount and available pot.','Provjerite iznos i raspoloživi fond.'));}};
 const nodes=raceSlot?rounds.filter(n=>c.guided!.pots.find(p=>p.nodeId===n.id)?.slot===raceSlot):[league,...rounds];
 return <section id="funding-inspector" aria-label={t('Sponsor pot setup','Postavljanje sponzorskog fonda')}><div className={s.fields}><label className={s.field}>{t('Campaign name','Naziv kampanje')}<input aria-label={t('Campaign name','Naziv kampanje')} maxLength={100} value={c.name} disabled={disabled} onChange={e=>onChange({...c,name:e.target.value})}/><small className={s.hint}>{t('Shown on your public campaign.','Prikazano na javnoj kampanji.')}</small></label><label className={s.field}>{t('Selected prize pool','Odabrani fond nagrada')}<span><input aria-label={t('Total budget · test MON','Ukupni fond · test MON')} inputMode="decimal" placeholder="0" value={c.budgetMon} disabled={disabled} onChange={e=>onChange({...c,budgetMon:e.target.value})}/><b>test MON</b></span><small className={s.hint}>{t('The exact prize amount you will deposit. RacesOn pays creation gas.','Točan fond koji ćete uplatiti. RacesOn plaća izradu.')}</small></label></div><div className={s.sectionHeading}><div><h2>{t('Allocate the prize pool','Raspodijelite fond nagrada')}</h2><p className={s.hint}>{t('Each percentage is a share of the','Svaki postotak je udio u fondu od')} <strong>{setupAmount(preview?.budgetWei??null,hr)} test MON</strong>.</p></div>{!raceSlot?<button className={s.outline} disabled={locked} onClick={()=>apply(()=>splitSponsorRoundsEqually(c))}>{t('Split rounds equally','Podijeli kola jednako')}</button>:null}</div><div className={s.allocation}><p className={s.allocationLabel}>{raceSlot?t('Race rewards','Nagrade utrke'):t('League & races','Liga i utrke')}</p>{nodes.map(n=><div className={s.allocationRow} key={n.id}><label><input type="checkbox" checked={n.shareBps>0} disabled={locked||Boolean(raceSlot)} onChange={e=>apply(()=>n.id===league.id?splitSponsorSections(c,e.target.checked?5000:0):setSponsorRoundShare(c,n.id,e.target.checked?Math.floor(10000/rounds.length):0))}/>{n.name}</label><label><input type="number" aria-label={`${n.name} %`} min="0" max="100" step="0.01" value={n.shareBps/100} disabled={locked||Boolean(raceSlot)} onChange={e=>{if(e.target.value!==''&&e.target.validity.valid)apply(()=>n.id===league.id?splitSponsorSections(c,Math.round(Number(e.target.value)*100)):setSponsorRoundShare(c,n.id,roundsBps?Math.round(Number(e.target.value)*1000000/roundsBps):0));}}/>%</label><strong>{setupAmount(preview?.rows.find(r=>r.id===n.id)?.amountWei??null,hr)} <small>test MON</small></strong></div>)}<div className={s.allocated}><span>{t('Allocated','Raspoređeno')}</span><span>{(league.shareBps+roundsBps)/100}% ✓</span></div></div><RewardSetupPolicy compact hr={hr} policy={c.policy} disabled={disabled} onChange={policy=>onChange({...c,policy})}/>{error?<p role="alert">{error}</p>:null}</section>;
}
