import {walletActionLabel} from "../model/walletActionLabel";
import SponsorClaimTerms from "./SponsorClaimTerms";
import RewardClaimDialog from "./RewardClaimDialog";
import RewardClaimProgress from "./RewardClaimProgress";
import RewardClaimFilters,{type ClaimFilter} from "./RewardClaimFilters";
import roleStyle from "./RewardRoleWorkspace.module.css";
import {useCallback,useEffect,useRef,useState} from "react";
import {sponsorAwards,sponsorClaim,type SponsorAward,type SponsorClaim} from "../data/sponsorProgramme";
import {getOwnRewardDestinations} from "../data/athleteDestinations";
import {signProgrammeClaim,sendProgrammeTransaction} from "../data/sponsorProgrammeWallet";
import type {DetectedRewardWallet} from "../data/browserWallet";
import SponsorWallet from "./SponsorWallet";
import {setupAmount} from "../model/setupAmount";
import s from "./SponsorLaunch.module.css";
type SharedAwards={awards:SponsorAward[];destinations:Awaited<ReturnType<typeof getOwnRewardDestinations>>["items"];refresh:()=>Promise<void>};
export default function SponsorClaims({role,approvalId,hr,chainId,shared,onAccessError}:{role:"recipient"|"operator";approvalId?:string;hr:boolean;chainId:number;shared?:SharedAwards;onAccessError?:(error:unknown)=>void}){
 const [sort,setSort]=useState("pot"),[filter,setFilter]=useState<ClaimFilter>("all");
 const [awards,setAwards]=useState<SponsorAward[]>([]),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false);
 const [destinations,setDestinations]=useState<Awaited<ReturnType<typeof getOwnRewardDestinations>>["items"]>([]);
 const active=useRef(true),flight=useRef(false),requests=useRef(new Map<string,string>()),t=(en:string,local:string)=>hr?local:en;
 async function load(){setFailed(false);setAwards([]);setBusy(true);try{if(shared){await shared.refresh();return;}const a=await sponsorAwards(role,approvalId);const d=role==="recipient"?await getOwnRewardDestinations():null;
  if(active.current){setAwards(a);setDestinations(d?.items??[]);}}catch(e){if(active.current){setFailed(true);if(e&&typeof e==="object"&&"status"in e&&[401,403].includes(Number(e.status)))onAccessError?.(e);}}finally{if(active.current)setBusy(false);}}
 useEffect(()=>{active.current=true;if(!shared)void load();return()=>{active.current=false;};},[role,approvalId]);
 async function request(a:SponsorAward,destinationId:string){if(flight.current)return;flight.current=true;setBusy(true);setFailed(false);
  const key=`${a.entitlementId}:${destinationId}`;if(!requests.current.has(key))requests.current.set(key,crypto.randomUUID());const id=requests.current.get(key)!;
  try{await sponsorClaim(role,id,{action:"request",approvalId:a.approvalId,entitlementId:a.entitlementId,destinationId});requests.current.delete(key);if(active.current){setSelected(id);await load();}}
  catch(e){if(active.current){setFailed(true);if(e&&typeof e==="object"&&"status"in e&&[401,403].includes(Number(e.status)))onAccessError?.(e);}}finally{flight.current=false;if(active.current)setBusy(false);}}
 const ordered=[...(shared?.awards??awards)].sort((a,b)=>{
  if(sort==="amount"){const x=BigInt(a.amountWei),y=BigInt(b.amountWei);if(x!==y)return x>y?-1:1;}
  if(sort==="unclaimed"){const delta=Number(a.claims.some(c=>c.paid))-Number(b.claims.some(c=>c.paid));if(delta)return delta;}
  return a.slot-b.slot||a.entitlementId.localeCompare(b.entitlementId);
 });
 const visible=ordered.filter(a=>filter==="all"||(filter==="paid")===a.claims.some(c=>c.paid));
 return <section className={`${s.card} ${roleStyle.awards}`} aria-label={t("Sponsor campaign rewards","Nagrade sponzorskih kampanja")}><div className={s.claimHeading}><h2>{role==="recipient"?t("Your sponsored rewards","Vaše sponzorirane nagrade"):t("Recipient claims","Preuzimanja primatelja")}</h2>
 <div className={s.claimTools}><label>{t("Sort","Poredaj")}<select aria-label={t("Sort sponsored rewards","Poredaj sponzorirane nagrade")} value={sort} onChange={e=>setSort(e.target.value)}><option value="pot">{t("Prize pot","Fond nagrada")}</option><option value="amount">{t("Highest reward","Najveća nagrada")}</option><option value="unclaimed">{t("Unclaimed first","Nepreuzeto prvo")}</option></select></label><button className={s.secondary} disabled={busy} onClick={()=>{setSelected(null);void load();}}>{t("Refresh claims","Osvježi preuzimanja")}</button></div></div>
 {failed?<p role="alert">{t("Claims could not be loaded or saved. Refresh to recover the current status.","Preuzimanja nije moguće učitati ili spremiti. Osvježite za trenutno stanje.")}</p>:null}
 {!busy&&!failed&&!(shared?.awards??awards).length?<p>{t("No published sponsor awards yet.","Još nema objavljenih sponzorskih nagrada.")}</p>:null}
 <RewardClaimFilters value={filter} onChange={setFilter} total={(shared?.awards??awards).length} paid={(shared?.awards??awards).filter(a=>a.claims.some(c=>c.paid)).length} hr={hr}/><div className={s.claimRows}>{visible.map(a=>{const matching=(shared?.destinations??destinations).filter(d=>d.athleteProfileId===a.athleteProfileId&&d.chainId===chainId&&d.status==="pending_review");return <div className={s.claimRow} key={a.entitlementId}>
 <div><strong>{a.slot===0?t("League","Liga"):`${t("Round","Kolo")} ${a.slot}`}</strong><span className={s.claimAmount}>{setupAmount(BigInt(a.amountWei),hr)} <small>test MON</small></span><span className={s.claimState} data-paid={a.claims.some(c=>c.paid)}>{a.claims.some(c=>c.paid)?t("Paid","Isplaćeno"):t("Unclaimed","Nepreuzeto")}</span></div><div className={s.claimActions}>
 {a.claims.map(c=><button className={s.secondary} key={c.id} disabled={busy} onClick={()=>setSelected(c.id)}>{c.paid?t("View payment","Pregledaj isplatu"):c.approved?t("Operator signed · view claim","Operator potpisao · pregledaj"):c.consented?t("Recipient signed · view claim","Primatelj potpisao · pregledaj"):c.prepared?t("Review claim","Pregledaj preuzimanje"):t("Awaiting readiness review","Čeka provjeru primatelja")}</button>)}
 {role==="recipient"&&!a.claims.some(c=>c.paid)?(matching.length?matching.map(d=><button className={s.primary} key={d.requestId} disabled={busy} onClick={()=>void request(a,d.requestId)}>{a.claims.length?t("New wallet request to","Novi zahtjev za novčanik"):t("Request reward to","Zatraži nagradu na")} {d.address.slice(0,6)}…{d.address.slice(-4)}</button>):<div><p>{t("Verify and select your reward wallet. Your award stays reserved.","Potvrdite i odaberite novčanik za nagrade. Nagrada ostaje rezervirana.")}</p><a className={s.secondary} href="#reward-wallet">{t("Set up reward wallet","Postavi novčanik za nagrade")}</a></div>):null}
 </div></div>;})}</div>
 {!busy&&!failed&&ordered.length>0&&!visible.length?<p role="status" className={roleStyle.empty}>{t("No rewards in this view. Choose All awards to see the rest.","Nema nagrada u ovom prikazu. Odaberite Sve nagrade za ostale.")}</p>:null}
 {selected?<RewardClaimDialog hr={hr} onClose={()=>{setSelected(null);void load();}}>{onBusy=><ClaimDetail key={selected} id={selected} role={role} hr={hr} chainId={chainId} onAccessError={onAccessError} onBusy={onBusy} onDone={()=>{setSelected(null);void load();}}/>}</RewardClaimDialog>:null}
 </section>;
}
export function ClaimDetail({id,role,hr,chainId,onAccessError,onDone,onBusy,claimRequest,reviewerOnly=false}:{id:string;role:"recipient"|"operator";hr:boolean;chainId:number;onAccessError?:(error:unknown)=>void;onDone?:()=>void;onBusy?:(busy:boolean)=>void;claimRequest?:(id:string,body?:unknown)=>Promise<SponsorClaim>;reviewerOnly?:boolean}){
 const request=claimRequest??((claimId:string,body?:unknown)=>body===undefined?sponsorClaim(role,claimId):sponsorClaim(role,claimId,body));
 const [view,setView]=useState<SponsorClaim|null>(null),[wallet,setWallet]=useState<{wallet:DetectedRewardWallet;address:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[ack,setAck]=useState(false);
 useEffect(()=>{onBusy?.(busy);},[busy,onBusy]);
 const walletRef=useRef(wallet);walletRef.current=wallet;
 const [pending,setPending]=useState<string|null>(null),[privyPolicy,setPrivyPolicy]=useState(false),[evidence,setEvidence]=useState({verifiedDateOfBirth:"",identityEvidenceRef:"",adultEvidenceRef:"",walletMfaEvidenceRef:"",walletRecoveryEvidenceRef:""});
 const active=useRef(true),flight=useRef(false),signature=useRef<string|null>(null),t=(en:string,local:string)=>hr?local:en,storage=`raceson:sponsor-claim:${chainId}:${id}`;
 const chooseWallet=useCallback((value:{wallet:DetectedRewardWallet;address:string}|null)=>{setWallet(value);setAck(false);signature.current=null;},[]);
 async function load(){setView(null);setAck(false);const v=await request(id);if(active.current)setView(v);}
 async function run(task:()=>Promise<void>){if(flight.current)return;flight.current=true;setBusy(true);setError(false);try{await task();}catch(e){if(active.current){setView(null);setError(true);if(e&&typeof e==="object"&&"status"in e&&[401,403].includes(Number(e.status)))onAccessError?.(e);}}finally{flight.current=false;if(active.current)setBusy(false);}}
 useEffect(()=>{active.current=true;try{const h=sessionStorage.getItem(storage);if(h&&/^0x[0-9a-f]{64}$/.test(h))setPending(h);}catch{/* Optional recovery. */}void run(load);return()=>{active.current=false;};},[id,role]);
 async function prepare(){if(!view)return;const v=await request(id,{action:"prepare",sourceStamp:view.sourceStamp,profileFingerprint:view.profileFingerprint,attestation:privyPolicy?{schemaVersion:2,policy:"operator-observed-privy-testnet-no-mfa-v1",chainId:10143,privyAppId:"cmtx921we00fu0cifaab7exez",verifiedDateOfBirth:evidence.verifiedDateOfBirth,identityEvidenceRef:evidence.identityEvidenceRef,adultEvidenceRef:evidence.adultEvidenceRef,walletProviderEvidenceRef:evidence.walletMfaEvidenceRef,walletRecoveryEvidenceRef:evidence.walletRecoveryEvidenceRef}:{schemaVersion:1,policy:"operator-observed-external-wallet-v1",...evidence}});if(active.current)setView(v);}
 async function sign(){if(!view||!wallet||!ack)return;const fresh=await request(id);if(JSON.stringify(fresh.signing)!==JSON.stringify(view.signing))throw Error("changed");
  signature.current??=await signProgrammeClaim(wallet.wallet.provider,fresh,()=>active.current&&walletRef.current===wallet);
  const v=await request(id,{action:role,signature:signature.current});if(active.current){signature.current=null;setView(v);setAck(false);}}
 async function send(){if(!view||!wallet||pending)return;const fresh=await request(id);if(JSON.stringify(fresh.transaction)!==JSON.stringify(view.transaction))throw Error("changed");
  const hash=await (wallet.wallet.sendProgrammeTransaction ? wallet.wallet.sendProgrammeTransaction(fresh,()=>active.current&&walletRef.current===wallet) : sendProgrammeTransaction(wallet.wallet.provider,fresh,()=>active.current&&walletRef.current===wallet));try{sessionStorage.setItem(storage,hash);}catch{/* Keep hash visible. */}if(active.current)setPending(hash);}
 async function verify(){if(!pending)return;const v=await request(id,{action:"receipt",transactionHash:pending});try{sessionStorage.removeItem(storage);}catch{/* Optional recovery. */}if(active.current){setView(v);setPending(null);}}
 return <section className={s.card}><h3>{t("Claim details","Podaci preuzimanja")}</h3><button className={s.secondary} disabled={busy} onClick={()=>void run(load)}>{t("Refresh status","Osvježi stanje")}</button>
 {error?<p role="alert">{t("The claim changed or could not be verified. Refresh before continuing.","Preuzimanje je izmijenjeno ili nije potvrđeno. Osvježite prije nastavka.")}</p>:null}
 {view?<> <RewardClaimProgress view={view} pending={pending} hr={hr}/><dl className={roleStyle.claimFacts}>{view.claim?<div><dt>{t("Exact reward","Točna nagrada")}</dt><dd className={roleStyle.amount}>{setupAmount(BigInt(view.claim.amount),hr)} <small>test MON</small></dd></div>:null}<div><dt>{t("Reward destination","Odredište nagrade")}</dt><dd className={s.address}>{view.address}</dd></div><div><dt>{t("Network","Mreža")}</dt><dd>{chainId===31337?t("Local simulation · 31337","Lokalna simulacija · 31337"):"Monad testnet · 10143"}</dd></div></dl><SponsorClaimTerms view={view} hr={hr}/>
 <p role="status">{({held:t("On hold · reward remains reserved","Na čekanju · nagrada ostaje rezervirana"),paid:t("Payment confirmed","Isplata potvrđena"),awaiting_review:t("Recipient readiness review pending","Čeka provjeru primatelja"),awaiting_consent:t("Waiting for recipient consent","Čeka pristanak primatelja"),awaiting_operator:t("Waiting for operator approval","Čeka odobrenje operatora"),ready_to_pay:t("Ready for payment","Spremno za isplatu")})[view.status]}</p>
 {role==="operator"&&view.status==="awaiting_review"?<details open><summary>{t("Recipient readiness evidence","Dokazi spremnosti primatelja")}</summary><p>{t("Reference existing identity, adult status and wallet-security evidence.","Navedite postojeće dokaze identiteta, punoljetnosti i sigurnosti novčanika.")}</p>
 {chainId===10143?<label className={s.field}>{t("Wallet readiness policy","Pravila provjere novčanika")}<select value={privyPolicy?"privy":"external"} onChange={e=>{setPrivyPolicy(e.target.value==="privy");setEvidence({...evidence,walletMfaEvidenceRef:""});}}><option value="external">{t("External wallet · MFA & recovery","Vanjski novčanik · MFA i oporavak")}</option><option value="privy">{t("Privy · approved testnet policy","Privy · odobrena testnet pravila")}</option></select></label>:null}
 {privyPolicy?<p>{t("Testnet-only provider and recovery evidence; this does not attest MFA.","Dokazi pružatelja i oporavka samo za testnet; ovo nije potvrda MFA.")}</p>:null}
 {Object.entries(evidence).map(([key,value])=><label className={s.field} key={key}>{({verifiedDateOfBirth:t("Verified date of birth","Potvrđen datum rođenja"),identityEvidenceRef:t("Identity evidence reference","Referenca dokaza identiteta"),adultEvidenceRef:t("Adult status reference","Referenca punoljetnosti"),walletMfaEvidenceRef:privyPolicy?t("Privy provider evidence reference","Referenca dokaza Privy pružatelja"):t("Wallet MFA reference","Referenca MFA novčanika"),walletRecoveryEvidenceRef:t("Wallet recovery reference","Referenca oporavka novčanika")})[key]}<input type={key==="verifiedDateOfBirth"?"date":"text"} value={value} onChange={e=>setEvidence({...evidence,[key]:e.target.value})}/></label>)}
 <button className={s.primary} disabled={busy||Object.values(evidence).some(v=>!v)} onClick={()=>void run(prepare)}>{t("Verify & prepare claim","Provjeri i pripremi preuzimanje")}</button></details>:null}
 {!reviewerOnly&&(view.signing||view.transaction)&&view.current?<><SponsorWallet compact purpose={role} requiredAddress={role === "operator" ? view.operatorAddress : view.address} chainId={chainId} hr={hr} onWallet={chooseWallet}/>
 {view.signing?<><label className={roleStyle.consent}><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>{role==="recipient"?t("I agree to receive this exact reward at this address.","Pristajem primiti ovu nagradu na navedenu adresu."):t("I approve this exact recipient and reward.","Odobravam ovog primatelja i nagradu.")}</label><button className={s.primary} disabled={busy||!wallet||!ack||wallet.address!==(role === "operator" ? view.operatorAddress : view.address)} onClick={()=>void run(sign)}>{walletActionLabel(role==="recipient"?t("Sign reward consent","Potpiši pristanak"):t("Sign operator approval","Potpiši odobrenje operatora"),wallet?.wallet)}</button></>:null}
 {view.transaction?<button className={s.primary} disabled={busy||!wallet||!!pending||wallet.address!==view.transaction.from} onClick={()=>void run(send)}>{walletActionLabel(t("Pay exact reward","Isplati točnu nagradu"),wallet?.wallet)}</button>:null}
 </>:null}
 {role==="operator"&&view.current&&view.status!=="paid"?<button className={s.secondary} disabled={busy} onClick={()=>void run(async()=>{const held=await request(id,{action:"revoke"});if(active.current)setView(held);})}>{t("Hold this claim","Zaustavi ovo preuzimanje")}</button>:null}
 {view.receipt?<div className={roleStyle.receipt}><details><summary>{t("Receipt details","Podaci potvrde")}</summary><p className={s.address}>{t("Confirmed transaction","Potvrđena transakcija")}: {view.receipt.transactionHash} · {t("block","blok")} {view.receipt.blockNumber}</p></details>{view.status==="paid"&&onDone?<button type="button" className={s.primary} disabled={busy} onClick={onDone}>{t("Done","Gotovo")}</button>:null}</div>:null}
 </>:null}
 {!reviewerOnly&&pending?<div role="status" className={roleStyle.pending}><p>{t("Transaction submitted · payment not yet confirmed","Transakcija poslana · isplata još nije potvrđena")}</p><p className={s.address}>{pending}</p><button className={s.secondary} disabled={busy} onClick={()=>void run(verify)}>{t("Verify payment receipt","Provjeri potvrdu isplate")}</button></div>:null}
 </section>;
}
